import type { GicsSectorId } from "./gics";

export type CatalogStock = {
  symbol: string;
  market: "JP" | "US";
  name: string;
  aliases?: string[];
  sector: GicsSectorId;
  /** "stock" by default. ETFs/funds are tagged "etf" and shown on /etfs. */
  type?: "stock" | "etf";
  /** For ETFs only — themed category for grouping on /etfs page. */
  etfCategory?:
    | "broad"
    | "sector"
    | "international"
    | "bond"
    | "commodity"
    | "thematic"
    | "dividend"
    | "leveraged";
};

export const STOCKS_CATALOG: CatalogStock[] = [
  // ===== Information Technology / 情報技術 =====
  { symbol: "AAPL", market: "US", name: "Apple", sector: "information-technology" },
  { symbol: "MSFT", market: "US", name: "Microsoft", sector: "information-technology" },
  { symbol: "NVDA", market: "US", name: "NVIDIA", sector: "information-technology" },
  { symbol: "AVGO", market: "US", name: "Broadcom", sector: "information-technology" },
  { symbol: "ORCL", market: "US", name: "Oracle", sector: "information-technology" },
  { symbol: "CRM", market: "US", name: "Salesforce", sector: "information-technology" },
  { symbol: "ADBE", market: "US", name: "Adobe", sector: "information-technology" },
  { symbol: "AMD", market: "US", name: "Advanced Micro Devices", sector: "information-technology" },
  { symbol: "CSCO", market: "US", name: "Cisco Systems", sector: "information-technology" },
  { symbol: "INTC", market: "US", name: "Intel", sector: "information-technology" },
  { symbol: "IBM", market: "US", name: "IBM", sector: "information-technology" },
  { symbol: "NOW", market: "US", name: "ServiceNow", sector: "information-technology" },
  { symbol: "INTU", market: "US", name: "Intuit", sector: "information-technology" },
  { symbol: "QCOM", market: "US", name: "Qualcomm", sector: "information-technology" },
  { symbol: "TXN", market: "US", name: "Texas Instruments", sector: "information-technology" },
  { symbol: "AMAT", market: "US", name: "Applied Materials", sector: "information-technology" },
  { symbol: "MU", market: "US", name: "Micron Technology", sector: "information-technology" },
  { symbol: "PANW", market: "US", name: "Palo Alto Networks", sector: "information-technology" },
  { symbol: "KLAC", market: "US", name: "KLA Corporation", sector: "information-technology" },
  { symbol: "LRCX", market: "US", name: "Lam Research", sector: "information-technology" },
  { symbol: "ADI", market: "US", name: "Analog Devices", sector: "information-technology" },
  { symbol: "SNPS", market: "US", name: "Synopsys", sector: "information-technology" },
  { symbol: "CDNS", market: "US", name: "Cadence Design Systems", sector: "information-technology" },
  { symbol: "ANET", market: "US", name: "Arista Networks", sector: "information-technology" },
  { symbol: "FTNT", market: "US", name: "Fortinet", sector: "information-technology" },
  { symbol: "ACN", market: "US", name: "Accenture", sector: "information-technology" },
  { symbol: "HPE", market: "US", name: "Hewlett Packard Enterprise", sector: "information-technology" },
  { symbol: "HPQ", market: "US", name: "HP Inc.", sector: "information-technology" },
  { symbol: "DELL", market: "US", name: "Dell Technologies", sector: "information-technology" },
  { symbol: "PLTR", market: "US", name: "Palantir Technologies", sector: "information-technology" },
  { symbol: "SMCI", market: "US", name: "Super Micro Computer", sector: "information-technology" },
  { symbol: "WDAY", market: "US", name: "Workday", sector: "information-technology" },
  { symbol: "CRWD", market: "US", name: "CrowdStrike", sector: "information-technology" },
  { symbol: "SNOW", market: "US", name: "Snowflake", sector: "information-technology" },
  { symbol: "NET", market: "US", name: "Cloudflare", sector: "information-technology" },
  { symbol: "DDOG", market: "US", name: "Datadog", sector: "information-technology" },
  { symbol: "ZS", market: "US", name: "Zscaler", sector: "information-technology" },
  { symbol: "OKTA", market: "US", name: "Okta", sector: "information-technology" },
  { symbol: "MDB", market: "US", name: "MongoDB", sector: "information-technology" },

  { symbol: "6758.T", market: "JP", name: "ソニーグループ", aliases: ["Sony", "ソニー"], sector: "information-technology" },
  { symbol: "6861.T", market: "JP", name: "キーエンス", aliases: ["Keyence"], sector: "information-technology" },
  { symbol: "8035.T", market: "JP", name: "東京エレクトロン", aliases: ["Tokyo Electron", "TEL"], sector: "information-technology" },
  { symbol: "6098.T", market: "JP", name: "リクルートホールディングス", aliases: ["Recruit", "リクルート"], sector: "information-technology" },
  { symbol: "6920.T", market: "JP", name: "レーザーテック", aliases: ["Lasertec"], sector: "information-technology" },
  { symbol: "6857.T", market: "JP", name: "アドバンテスト", aliases: ["Advantest"], sector: "information-technology" },
  { symbol: "6971.T", market: "JP", name: "京セラ", aliases: ["Kyocera"], sector: "information-technology" },
  { symbol: "6981.T", market: "JP", name: "村田製作所", aliases: ["Murata"], sector: "information-technology" },
  { symbol: "6701.T", market: "JP", name: "NEC", aliases: ["日本電気"], sector: "information-technology" },
  { symbol: "6702.T", market: "JP", name: "富士通", aliases: ["Fujitsu"], sector: "information-technology" },
  { symbol: "6724.T", market: "JP", name: "セイコーエプソン", aliases: ["Epson", "エプソン"], sector: "information-technology" },
  { symbol: "7751.T", market: "JP", name: "キヤノン", aliases: ["Canon", "キャノン"], sector: "information-technology" },
  { symbol: "4307.T", market: "JP", name: "野村総合研究所", aliases: ["NRI", "野村総研"], sector: "information-technology" },
  { symbol: "9613.T", market: "JP", name: "NTTデータ", aliases: ["NTT Data"], sector: "information-technology" },
  { symbol: "4768.T", market: "JP", name: "大塚商会", aliases: ["Otsuka Shokai"], sector: "information-technology" },
  { symbol: "6770.T", market: "JP", name: "アルプスアルパイン", aliases: ["Alps Alpine"], sector: "information-technology" },
  { symbol: "6963.T", market: "JP", name: "ローム", aliases: ["ROHM"], sector: "information-technology" },
  { symbol: "6532.T", market: "JP", name: "ベイカレント・コンサルティング", aliases: ["Baycurrent"], sector: "information-technology" },
  { symbol: "3659.T", market: "JP", name: "ネクソン", aliases: ["Nexon"], sector: "communication-services" },

  // ===== Communication Services / コミュニケーション =====
  { symbol: "GOOGL", market: "US", name: "Alphabet (Google)", aliases: ["Google"], sector: "communication-services" },
  { symbol: "META", market: "US", name: "Meta Platforms", aliases: ["Facebook"], sector: "communication-services" },
  { symbol: "NFLX", market: "US", name: "Netflix", sector: "communication-services" },
  { symbol: "DIS", market: "US", name: "Walt Disney", sector: "communication-services" },
  { symbol: "VZ", market: "US", name: "Verizon Communications", sector: "communication-services" },
  { symbol: "T", market: "US", name: "AT&T", sector: "communication-services" },
  { symbol: "CMCSA", market: "US", name: "Comcast", sector: "communication-services" },
  { symbol: "TMUS", market: "US", name: "T-Mobile US", sector: "communication-services" },
  { symbol: "EA", market: "US", name: "Electronic Arts", sector: "communication-services" },
  { symbol: "TTWO", market: "US", name: "Take-Two Interactive", sector: "communication-services" },
  { symbol: "WBD", market: "US", name: "Warner Bros. Discovery", sector: "communication-services" },
  { symbol: "PARA", market: "US", name: "Paramount Global", sector: "communication-services" },
  { symbol: "CHTR", market: "US", name: "Charter Communications", sector: "communication-services" },
  { symbol: "ROKU", market: "US", name: "Roku", sector: "communication-services" },
  { symbol: "SPOT", market: "US", name: "Spotify", sector: "communication-services" },
  { symbol: "PINS", market: "US", name: "Pinterest", sector: "communication-services" },
  { symbol: "SNAP", market: "US", name: "Snap", aliases: ["Snapchat"], sector: "communication-services" },

  { symbol: "9984.T", market: "JP", name: "ソフトバンクグループ", aliases: ["ソフトバンク", "SoftBank"], sector: "communication-services" },
  { symbol: "9432.T", market: "JP", name: "日本電信電話", aliases: ["NTT"], sector: "communication-services" },
  { symbol: "9433.T", market: "JP", name: "KDDI", aliases: ["au"], sector: "communication-services" },
  { symbol: "9434.T", market: "JP", name: "ソフトバンク", aliases: ["SoftBank Corp"], sector: "communication-services" },
  { symbol: "4689.T", market: "JP", name: "LINEヤフー", aliases: ["LY", "Yahoo!", "ヤフー"], sector: "communication-services" },
  { symbol: "4751.T", market: "JP", name: "サイバーエージェント", aliases: ["CyberAgent", "サイバー"], sector: "communication-services" },
  { symbol: "2432.T", market: "JP", name: "ディー・エヌ・エー", aliases: ["DeNA"], sector: "communication-services" },
  { symbol: "9602.T", market: "JP", name: "東宝", aliases: ["Toho"], sector: "communication-services" },
  { symbol: "7974.T", market: "JP", name: "任天堂", aliases: ["Nintendo", "ニンテンドー"], sector: "communication-services" },
  { symbol: "9684.T", market: "JP", name: "スクウェア・エニックス・ホールディングス", aliases: ["Square Enix", "スクエニ"], sector: "communication-services" },
  { symbol: "7832.T", market: "JP", name: "バンダイナムコホールディングス", aliases: ["Bandai Namco", "バンダイ"], sector: "communication-services" },
  { symbol: "9697.T", market: "JP", name: "カプコン", aliases: ["Capcom"], sector: "communication-services" },
  { symbol: "9766.T", market: "JP", name: "コナミグループ", aliases: ["Konami", "コナミ"], sector: "communication-services" },

  // ===== Consumer Discretionary / 一般消費財 =====
  { symbol: "AMZN", market: "US", name: "Amazon", sector: "consumer-discretionary" },
  { symbol: "TSLA", market: "US", name: "Tesla", sector: "consumer-discretionary" },
  { symbol: "HD", market: "US", name: "Home Depot", sector: "consumer-discretionary" },
  { symbol: "MCD", market: "US", name: "McDonald's", sector: "consumer-discretionary" },
  { symbol: "NKE", market: "US", name: "Nike", sector: "consumer-discretionary" },
  { symbol: "LOW", market: "US", name: "Lowe's", sector: "consumer-discretionary" },
  { symbol: "SBUX", market: "US", name: "Starbucks", sector: "consumer-discretionary" },
  { symbol: "BKNG", market: "US", name: "Booking Holdings", sector: "consumer-discretionary" },
  { symbol: "TJX", market: "US", name: "TJX Companies", sector: "consumer-discretionary" },
  { symbol: "GM", market: "US", name: "General Motors", sector: "consumer-discretionary" },
  { symbol: "F", market: "US", name: "Ford Motor", sector: "consumer-discretionary" },
  { symbol: "MAR", market: "US", name: "Marriott International", sector: "consumer-discretionary" },
  { symbol: "ROST", market: "US", name: "Ross Stores", sector: "consumer-discretionary" },
  { symbol: "ABNB", market: "US", name: "Airbnb", sector: "consumer-discretionary" },
  { symbol: "DHI", market: "US", name: "D.R. Horton", sector: "consumer-discretionary" },
  { symbol: "LEN", market: "US", name: "Lennar", sector: "consumer-discretionary" },
  { symbol: "LULU", market: "US", name: "Lululemon Athletica", sector: "consumer-discretionary" },
  { symbol: "ORLY", market: "US", name: "O'Reilly Automotive", sector: "consumer-discretionary" },
  { symbol: "AZO", market: "US", name: "AutoZone", sector: "consumer-discretionary" },
  { symbol: "CMG", market: "US", name: "Chipotle Mexican Grill", sector: "consumer-discretionary" },
  { symbol: "YUM", market: "US", name: "Yum! Brands", sector: "consumer-discretionary" },
  { symbol: "RCL", market: "US", name: "Royal Caribbean Cruises", sector: "consumer-discretionary" },
  { symbol: "EBAY", market: "US", name: "eBay", sector: "consumer-discretionary" },
  { symbol: "DPZ", market: "US", name: "Domino's Pizza", sector: "consumer-discretionary" },

  { symbol: "7203.T", market: "JP", name: "トヨタ自動車", aliases: ["Toyota", "トヨタ"], sector: "consumer-discretionary" },
  { symbol: "7267.T", market: "JP", name: "本田技研工業", aliases: ["Honda", "ホンダ"], sector: "consumer-discretionary" },
  { symbol: "7201.T", market: "JP", name: "日産自動車", aliases: ["Nissan", "ニッサン"], sector: "consumer-discretionary" },
  { symbol: "7269.T", market: "JP", name: "スズキ", aliases: ["Suzuki"], sector: "consumer-discretionary" },
  { symbol: "7270.T", market: "JP", name: "SUBARU", aliases: ["スバル", "Subaru"], sector: "consumer-discretionary" },
  { symbol: "7261.T", market: "JP", name: "マツダ", aliases: ["Mazda"], sector: "consumer-discretionary" },
  { symbol: "9983.T", market: "JP", name: "ファーストリテイリング", aliases: ["Fast Retailing", "ユニクロ", "Uniqlo"], sector: "consumer-discretionary" },
  { symbol: "3092.T", market: "JP", name: "ZOZO", aliases: ["ゾゾ"], sector: "consumer-discretionary" },
  { symbol: "4661.T", market: "JP", name: "オリエンタルランド", aliases: ["Oriental Land", "ディズニーランド"], sector: "consumer-discretionary" },
  { symbol: "9831.T", market: "JP", name: "ヤマダホールディングス", aliases: ["Yamada"], sector: "consumer-discretionary" },
  { symbol: "8175.T", market: "JP", name: "ベスト電器", sector: "consumer-discretionary" },
  { symbol: "5108.T", market: "JP", name: "ブリヂストン", aliases: ["Bridgestone"], sector: "consumer-discretionary" },
  { symbol: "1928.T", market: "JP", name: "積水ハウス", aliases: ["Sekisui House"], sector: "consumer-discretionary" },
  { symbol: "1925.T", market: "JP", name: "大和ハウス工業", aliases: ["Daiwa House", "大和ハウス"], sector: "consumer-discretionary" },
  { symbol: "8278.T", market: "JP", name: "フジ", sector: "consumer-staples" },
  { symbol: "3086.T", market: "JP", name: "J.フロント リテイリング", aliases: ["J Front"], sector: "consumer-discretionary" },
  { symbol: "8233.T", market: "JP", name: "高島屋", aliases: ["Takashimaya"], sector: "consumer-discretionary" },
  { symbol: "8252.T", market: "JP", name: "丸井グループ", aliases: ["Marui"], sector: "consumer-discretionary" },
  { symbol: "3099.T", market: "JP", name: "三越伊勢丹ホールディングス", aliases: ["Mitsukoshi Isetan"], sector: "consumer-discretionary" },

  // ===== Consumer Staples / 生活必需品 =====
  { symbol: "PG", market: "US", name: "Procter & Gamble", sector: "consumer-staples" },
  { symbol: "KO", market: "US", name: "Coca-Cola", sector: "consumer-staples" },
  { symbol: "PEP", market: "US", name: "PepsiCo", sector: "consumer-staples" },
  { symbol: "WMT", market: "US", name: "Walmart", sector: "consumer-staples" },
  { symbol: "COST", market: "US", name: "Costco Wholesale", sector: "consumer-staples" },
  { symbol: "PM", market: "US", name: "Philip Morris International", sector: "consumer-staples" },
  { symbol: "MO", market: "US", name: "Altria Group", sector: "consumer-staples" },
  { symbol: "MDLZ", market: "US", name: "Mondelez International", sector: "consumer-staples" },
  { symbol: "CL", market: "US", name: "Colgate-Palmolive", sector: "consumer-staples" },
  { symbol: "KMB", market: "US", name: "Kimberly-Clark", sector: "consumer-staples" },
  { symbol: "GIS", market: "US", name: "General Mills", sector: "consumer-staples" },
  { symbol: "KHC", market: "US", name: "Kraft Heinz", sector: "consumer-staples" },
  { symbol: "STZ", market: "US", name: "Constellation Brands", sector: "consumer-staples" },
  { symbol: "KR", market: "US", name: "Kroger", sector: "consumer-staples" },
  { symbol: "ADM", market: "US", name: "Archer-Daniels-Midland", sector: "consumer-staples" },
  { symbol: "TGT", market: "US", name: "Target", sector: "consumer-staples" },
  { symbol: "EL", market: "US", name: "Estée Lauder", sector: "consumer-staples" },
  { symbol: "SYY", market: "US", name: "Sysco", sector: "consumer-staples" },
  { symbol: "HSY", market: "US", name: "Hershey", sector: "consumer-staples" },
  { symbol: "CHD", market: "US", name: "Church & Dwight", sector: "consumer-staples" },

  { symbol: "2914.T", market: "JP", name: "日本たばこ産業", aliases: ["JT", "Japan Tobacco"], sector: "consumer-staples" },
  { symbol: "2502.T", market: "JP", name: "アサヒグループホールディングス", aliases: ["Asahi", "アサヒビール"], sector: "consumer-staples" },
  { symbol: "2503.T", market: "JP", name: "キリンホールディングス", aliases: ["Kirin", "キリン"], sector: "consumer-staples" },
  { symbol: "2802.T", market: "JP", name: "味の素", aliases: ["Ajinomoto"], sector: "consumer-staples" },
  { symbol: "2269.T", market: "JP", name: "明治ホールディングス", aliases: ["Meiji", "明治"], sector: "consumer-staples" },
  { symbol: "2587.T", market: "JP", name: "サントリー食品インターナショナル", aliases: ["Suntory", "サントリー"], sector: "consumer-staples" },
  { symbol: "2897.T", market: "JP", name: "日清食品ホールディングス", aliases: ["Nissin Foods", "日清"], sector: "consumer-staples" },
  { symbol: "2801.T", market: "JP", name: "キッコーマン", aliases: ["Kikkoman"], sector: "consumer-staples" },
  { symbol: "4452.T", market: "JP", name: "花王", aliases: ["Kao"], sector: "consumer-staples" },
  { symbol: "4911.T", market: "JP", name: "資生堂", aliases: ["Shiseido"], sector: "consumer-staples" },
  { symbol: "8113.T", market: "JP", name: "ユニ・チャーム", aliases: ["Unicharm", "ユニチャーム"], sector: "consumer-staples" },
  { symbol: "3088.T", market: "JP", name: "マツキヨココカラ&カンパニー", aliases: ["Matsukiyo"], sector: "consumer-staples" },
  { symbol: "8267.T", market: "JP", name: "イオン", aliases: ["Aeon"], sector: "consumer-staples" },
  { symbol: "3382.T", market: "JP", name: "セブン&アイ・ホールディングス", aliases: ["Seven & i", "セブン", "7-Eleven"], sector: "consumer-staples" },
  { symbol: "8028.T", market: "JP", name: "ファミリーマート", aliases: ["FamilyMart"], sector: "consumer-staples" },
  { symbol: "2670.T", market: "JP", name: "エービーシー・マート", aliases: ["ABC Mart"], sector: "consumer-discretionary" },
  { symbol: "2811.T", market: "JP", name: "カゴメ", aliases: ["Kagome"], sector: "consumer-staples" },

  // ===== Health Care / ヘルスケア =====
  { symbol: "JNJ", market: "US", name: "Johnson & Johnson", sector: "health-care" },
  { symbol: "LLY", market: "US", name: "Eli Lilly", sector: "health-care" },
  { symbol: "UNH", market: "US", name: "UnitedHealth Group", sector: "health-care" },
  { symbol: "PFE", market: "US", name: "Pfizer", sector: "health-care" },
  { symbol: "MRK", market: "US", name: "Merck", sector: "health-care" },
  { symbol: "ABBV", market: "US", name: "AbbVie", sector: "health-care" },
  { symbol: "TMO", market: "US", name: "Thermo Fisher Scientific", sector: "health-care" },
  { symbol: "ABT", market: "US", name: "Abbott Laboratories", sector: "health-care" },
  { symbol: "DHR", market: "US", name: "Danaher", sector: "health-care" },
  { symbol: "BMY", market: "US", name: "Bristol-Myers Squibb", sector: "health-care" },
  { symbol: "AMGN", market: "US", name: "Amgen", sector: "health-care" },
  { symbol: "GILD", market: "US", name: "Gilead Sciences", sector: "health-care" },
  { symbol: "MDT", market: "US", name: "Medtronic", sector: "health-care" },
  { symbol: "ISRG", market: "US", name: "Intuitive Surgical", sector: "health-care" },
  { symbol: "CVS", market: "US", name: "CVS Health", sector: "health-care" },
  { symbol: "ELV", market: "US", name: "Elevance Health", sector: "health-care" },
  { symbol: "REGN", market: "US", name: "Regeneron Pharmaceuticals", sector: "health-care" },
  { symbol: "VRTX", market: "US", name: "Vertex Pharmaceuticals", sector: "health-care" },
  { symbol: "ZTS", market: "US", name: "Zoetis", sector: "health-care" },
  { symbol: "BIIB", market: "US", name: "Biogen", sector: "health-care" },
  { symbol: "MRNA", market: "US", name: "Moderna", sector: "health-care" },
  { symbol: "BSX", market: "US", name: "Boston Scientific", sector: "health-care" },

  { symbol: "4519.T", market: "JP", name: "中外製薬", aliases: ["Chugai"], sector: "health-care" },
  { symbol: "4502.T", market: "JP", name: "武田薬品工業", aliases: ["Takeda", "武田薬品"], sector: "health-care" },
  { symbol: "4543.T", market: "JP", name: "テルモ", aliases: ["Terumo"], sector: "health-care" },
  { symbol: "4523.T", market: "JP", name: "エーザイ", aliases: ["Eisai"], sector: "health-care" },
  { symbol: "4568.T", market: "JP", name: "第一三共", aliases: ["Daiichi Sankyo"], sector: "health-care" },
  { symbol: "4503.T", market: "JP", name: "アステラス製薬", aliases: ["Astellas", "アステラス"], sector: "health-care" },
  { symbol: "4578.T", market: "JP", name: "大塚ホールディングス", aliases: ["Otsuka", "大塚"], sector: "health-care" },
  { symbol: "7741.T", market: "JP", name: "HOYA", sector: "health-care" },
  { symbol: "6869.T", market: "JP", name: "シスメックス", aliases: ["Sysmex"], sector: "health-care" },
  { symbol: "7733.T", market: "JP", name: "オリンパス", aliases: ["Olympus"], sector: "health-care" },
  { symbol: "4151.T", market: "JP", name: "協和キリン", aliases: ["Kyowa Kirin"], sector: "health-care" },
  { symbol: "4507.T", market: "JP", name: "塩野義製薬", aliases: ["Shionogi"], sector: "health-care" },

  // ===== Financials / 金融 =====
  { symbol: "JPM", market: "US", name: "JPMorgan Chase", sector: "financials" },
  { symbol: "BAC", market: "US", name: "Bank of America", sector: "financials" },
  { symbol: "WFC", market: "US", name: "Wells Fargo", sector: "financials" },
  { symbol: "GS", market: "US", name: "Goldman Sachs", sector: "financials" },
  { symbol: "MS", market: "US", name: "Morgan Stanley", sector: "financials" },
  { symbol: "C", market: "US", name: "Citigroup", sector: "financials" },
  { symbol: "BLK", market: "US", name: "BlackRock", sector: "financials" },
  { symbol: "AXP", market: "US", name: "American Express", sector: "financials" },
  { symbol: "BX", market: "US", name: "Blackstone", sector: "financials" },
  { symbol: "SCHW", market: "US", name: "Charles Schwab", sector: "financials" },
  { symbol: "V", market: "US", name: "Visa", sector: "financials" },
  { symbol: "MA", market: "US", name: "Mastercard", sector: "financials" },
  { symbol: "USB", market: "US", name: "U.S. Bancorp", sector: "financials" },
  { symbol: "PNC", market: "US", name: "PNC Financial Services", sector: "financials" },
  { symbol: "PGR", market: "US", name: "Progressive", sector: "financials" },
  { symbol: "MMC", market: "US", name: "Marsh & McLennan", sector: "financials" },
  { symbol: "CB", market: "US", name: "Chubb", sector: "financials" },
  { symbol: "AON", market: "US", name: "Aon", sector: "financials" },
  { symbol: "ICE", market: "US", name: "Intercontinental Exchange", sector: "financials" },
  { symbol: "CME", market: "US", name: "CME Group", sector: "financials" },
  { symbol: "COIN", market: "US", name: "Coinbase Global", sector: "financials" },
  { symbol: "PYPL", market: "US", name: "PayPal Holdings", sector: "financials" },

  { symbol: "8306.T", market: "JP", name: "三菱UFJフィナンシャル・グループ", aliases: ["三菱UFJ", "MUFG", "Mitsubishi UFJ"], sector: "financials" },
  { symbol: "8316.T", market: "JP", name: "三井住友フィナンシャルグループ", aliases: ["三井住友", "SMFG", "Sumitomo Mitsui"], sector: "financials" },
  { symbol: "8411.T", market: "JP", name: "みずほフィナンシャルグループ", aliases: ["みずほ", "Mizuho"], sector: "financials" },
  { symbol: "8766.T", market: "JP", name: "東京海上ホールディングス", aliases: ["東京海上", "Tokio Marine"], sector: "financials" },
  { symbol: "8725.T", market: "JP", name: "MS&ADインシュアランスグループホールディングス", aliases: ["MS&AD"], sector: "financials" },
  { symbol: "8630.T", market: "JP", name: "SOMPOホールディングス", aliases: ["Sompo", "ソンポ"], sector: "financials" },
  { symbol: "8591.T", market: "JP", name: "オリックス", aliases: ["Orix"], sector: "financials" },
  { symbol: "8604.T", market: "JP", name: "野村ホールディングス", aliases: ["Nomura", "野村"], sector: "financials" },
  { symbol: "8601.T", market: "JP", name: "大和証券グループ本社", aliases: ["Daiwa", "大和証券"], sector: "financials" },
  { symbol: "8331.T", market: "JP", name: "千葉銀行", aliases: ["Chiba Bank"], sector: "financials" },
  { symbol: "8473.T", market: "JP", name: "SBIホールディングス", aliases: ["SBI"], sector: "financials" },
  { symbol: "8697.T", market: "JP", name: "日本取引所グループ", aliases: ["JPX"], sector: "financials" },
  { symbol: "8354.T", market: "JP", name: "ふくおかフィナンシャルグループ", aliases: ["Fukuoka"], sector: "financials" },

  // ===== Industrials / 資本財・サービス =====
  { symbol: "BA", market: "US", name: "Boeing", sector: "industrials" },
  { symbol: "CAT", market: "US", name: "Caterpillar", sector: "industrials" },
  { symbol: "HON", market: "US", name: "Honeywell International", sector: "industrials" },
  { symbol: "UPS", market: "US", name: "United Parcel Service", sector: "industrials" },
  { symbol: "GE", market: "US", name: "General Electric", sector: "industrials" },
  { symbol: "RTX", market: "US", name: "RTX (Raytheon)", sector: "industrials" },
  { symbol: "LMT", market: "US", name: "Lockheed Martin", sector: "industrials" },
  { symbol: "UNP", market: "US", name: "Union Pacific", sector: "industrials" },
  { symbol: "DE", market: "US", name: "Deere & Company", sector: "industrials" },
  { symbol: "MMM", market: "US", name: "3M", sector: "industrials" },
  { symbol: "ETN", market: "US", name: "Eaton", sector: "industrials" },
  { symbol: "ITW", market: "US", name: "Illinois Tool Works", sector: "industrials" },
  { symbol: "EMR", market: "US", name: "Emerson Electric", sector: "industrials" },
  { symbol: "NSC", market: "US", name: "Norfolk Southern", sector: "industrials" },
  { symbol: "CSX", market: "US", name: "CSX", sector: "industrials" },
  { symbol: "GD", market: "US", name: "General Dynamics", sector: "industrials" },
  { symbol: "FDX", market: "US", name: "FedEx", sector: "industrials" },
  { symbol: "NOC", market: "US", name: "Northrop Grumman", sector: "industrials" },
  { symbol: "WM", market: "US", name: "Waste Management", sector: "industrials" },
  { symbol: "ADP", market: "US", name: "Automatic Data Processing", sector: "industrials" },
  { symbol: "PH", market: "US", name: "Parker-Hannifin", sector: "industrials" },
  { symbol: "TT", market: "US", name: "Trane Technologies", sector: "industrials" },
  { symbol: "UBER", market: "US", name: "Uber Technologies", sector: "industrials" },

  { symbol: "6301.T", market: "JP", name: "小松製作所", aliases: ["Komatsu", "コマツ"], sector: "industrials" },
  { symbol: "6954.T", market: "JP", name: "ファナック", aliases: ["Fanuc"], sector: "industrials" },
  { symbol: "7011.T", market: "JP", name: "三菱重工業", aliases: ["三菱重工", "MHI"], sector: "industrials" },
  { symbol: "9020.T", market: "JP", name: "東日本旅客鉄道", aliases: ["JR東日本", "JR East"], sector: "industrials" },
  { symbol: "9022.T", market: "JP", name: "東海旅客鉄道", aliases: ["JR東海", "JR Central"], sector: "industrials" },
  { symbol: "9021.T", market: "JP", name: "西日本旅客鉄道", aliases: ["JR西日本", "JR West"], sector: "industrials" },
  { symbol: "9202.T", market: "JP", name: "ANAホールディングス", aliases: ["ANA", "全日空"], sector: "industrials" },
  { symbol: "9201.T", market: "JP", name: "日本航空", aliases: ["JAL"], sector: "industrials" },
  { symbol: "9101.T", market: "JP", name: "日本郵船", aliases: ["NYK", "郵船"], sector: "industrials" },
  { symbol: "9104.T", market: "JP", name: "商船三井", aliases: ["MOL"], sector: "industrials" },
  { symbol: "9107.T", market: "JP", name: "川崎汽船", aliases: ["K Line"], sector: "industrials" },
  { symbol: "6367.T", market: "JP", name: "ダイキン工業", aliases: ["Daikin", "ダイキン"], sector: "industrials" },
  { symbol: "6273.T", market: "JP", name: "SMC", sector: "industrials" },
  { symbol: "6326.T", market: "JP", name: "クボタ", aliases: ["Kubota"], sector: "industrials" },
  { symbol: "6471.T", market: "JP", name: "日本精工", aliases: ["NSK"], sector: "industrials" },
  { symbol: "6503.T", market: "JP", name: "三菱電機", aliases: ["三菱電", "Mitsubishi Electric"], sector: "industrials" },
  { symbol: "6501.T", market: "JP", name: "日立製作所", aliases: ["Hitachi", "日立"], sector: "industrials" },
  { symbol: "6502.T", market: "JP", name: "東芝", aliases: ["Toshiba"], sector: "industrials" },
  { symbol: "7012.T", market: "JP", name: "川崎重工業", aliases: ["川崎重工", "Kawasaki Heavy"], sector: "industrials" },
  { symbol: "7013.T", market: "JP", name: "IHI", sector: "industrials" },
  { symbol: "8001.T", market: "JP", name: "伊藤忠商事", aliases: ["Itochu"], sector: "industrials" },
  { symbol: "8002.T", market: "JP", name: "丸紅", aliases: ["Marubeni"], sector: "industrials" },
  { symbol: "8031.T", market: "JP", name: "三井物産", aliases: ["Mitsui & Co"], sector: "industrials" },
  { symbol: "8053.T", market: "JP", name: "住友商事", aliases: ["Sumitomo Corporation"], sector: "industrials" },
  { symbol: "8058.T", market: "JP", name: "三菱商事", aliases: ["Mitsubishi Corporation"], sector: "industrials" },
  { symbol: "6594.T", market: "JP", name: "ニデック", aliases: ["Nidec", "日本電産"], sector: "industrials" },

  // ===== Materials / 素材 =====
  { symbol: "LIN", market: "US", name: "Linde", sector: "materials" },
  { symbol: "SHW", market: "US", name: "Sherwin-Williams", sector: "materials" },
  { symbol: "ECL", market: "US", name: "Ecolab", sector: "materials" },
  { symbol: "APD", market: "US", name: "Air Products and Chemicals", sector: "materials" },
  { symbol: "FCX", market: "US", name: "Freeport-McMoRan", sector: "materials" },
  { symbol: "NEM", market: "US", name: "Newmont", sector: "materials" },
  { symbol: "DD", market: "US", name: "DuPont de Nemours", sector: "materials" },
  { symbol: "NUE", market: "US", name: "Nucor", sector: "materials" },
  { symbol: "IFF", market: "US", name: "International Flavors & Fragrances", sector: "materials" },
  { symbol: "DOW", market: "US", name: "Dow", sector: "materials" },
  { symbol: "PPG", market: "US", name: "PPG Industries", sector: "materials" },
  { symbol: "MLM", market: "US", name: "Martin Marietta Materials", sector: "materials" },
  { symbol: "VMC", market: "US", name: "Vulcan Materials", sector: "materials" },

  { symbol: "4063.T", market: "JP", name: "信越化学工業", aliases: ["信越化学", "Shin-Etsu Chemical"], sector: "materials" },
  { symbol: "5401.T", market: "JP", name: "日本製鉄", aliases: ["Nippon Steel", "新日鉄"], sector: "materials" },
  { symbol: "3402.T", market: "JP", name: "東レ", aliases: ["Toray"], sector: "materials" },
  { symbol: "4188.T", market: "JP", name: "三菱ケミカルグループ", aliases: ["Mitsubishi Chemical", "三菱ケミカル"], sector: "materials" },
  { symbol: "4005.T", market: "JP", name: "住友化学", aliases: ["Sumitomo Chemical"], sector: "materials" },
  { symbol: "5713.T", market: "JP", name: "住友金属鉱山", aliases: ["Sumitomo Metal Mining"], sector: "materials" },
  { symbol: "3407.T", market: "JP", name: "旭化成", aliases: ["Asahi Kasei"], sector: "materials" },
  { symbol: "4901.T", market: "JP", name: "富士フイルムホールディングス", aliases: ["Fujifilm", "富士フイルム"], sector: "materials" },
  { symbol: "5201.T", market: "JP", name: "AGC", aliases: ["旭硝子"], sector: "materials" },
  { symbol: "5411.T", market: "JP", name: "JFEホールディングス", aliases: ["JFE"], sector: "materials" },
  { symbol: "5802.T", market: "JP", name: "住友電気工業", aliases: ["Sumitomo Electric"], sector: "industrials" },

  // ===== Energy / エネルギー =====
  { symbol: "XOM", market: "US", name: "ExxonMobil", sector: "energy" },
  { symbol: "CVX", market: "US", name: "Chevron", sector: "energy" },
  { symbol: "COP", market: "US", name: "ConocoPhillips", sector: "energy" },
  { symbol: "EOG", market: "US", name: "EOG Resources", sector: "energy" },
  { symbol: "SLB", market: "US", name: "Schlumberger", sector: "energy" },
  { symbol: "MPC", market: "US", name: "Marathon Petroleum", sector: "energy" },
  { symbol: "PSX", market: "US", name: "Phillips 66", sector: "energy" },
  { symbol: "OXY", market: "US", name: "Occidental Petroleum", sector: "energy" },
  { symbol: "VLO", market: "US", name: "Valero Energy", sector: "energy" },
  { symbol: "HAL", market: "US", name: "Halliburton", sector: "energy" },
  { symbol: "KMI", market: "US", name: "Kinder Morgan", sector: "energy" },
  { symbol: "WMB", market: "US", name: "Williams Companies", sector: "energy" },
  { symbol: "BKR", market: "US", name: "Baker Hughes", sector: "energy" },

  { symbol: "5020.T", market: "JP", name: "ENEOSホールディングス", aliases: ["ENEOS", "エネオス"], sector: "energy" },
  { symbol: "1605.T", market: "JP", name: "INPEX", aliases: ["国際石油開発"], sector: "energy" },
  { symbol: "5019.T", market: "JP", name: "出光興産", aliases: ["Idemitsu", "出光"], sector: "energy" },
  { symbol: "1662.T", market: "JP", name: "石油資源開発", aliases: ["JAPEX"], sector: "energy" },

  // ===== Utilities / 公益事業 =====
  { symbol: "NEE", market: "US", name: "NextEra Energy", sector: "utilities" },
  { symbol: "DUK", market: "US", name: "Duke Energy", sector: "utilities" },
  { symbol: "SO", market: "US", name: "Southern Company", sector: "utilities" },
  { symbol: "AEP", market: "US", name: "American Electric Power", sector: "utilities" },
  { symbol: "EXC", market: "US", name: "Exelon", sector: "utilities" },
  { symbol: "D", market: "US", name: "Dominion Energy", sector: "utilities" },
  { symbol: "XEL", market: "US", name: "Xcel Energy", sector: "utilities" },
  { symbol: "SRE", market: "US", name: "Sempra", sector: "utilities" },
  { symbol: "PEG", market: "US", name: "Public Service Enterprise Group", sector: "utilities" },
  { symbol: "ED", market: "US", name: "Consolidated Edison", sector: "utilities" },
  { symbol: "WEC", market: "US", name: "WEC Energy Group", sector: "utilities" },
  { symbol: "ES", market: "US", name: "Eversource Energy", sector: "utilities" },
  { symbol: "PCG", market: "US", name: "PG&E", sector: "utilities" },

  { symbol: "9501.T", market: "JP", name: "東京電力ホールディングス", aliases: ["東電", "TEPCO"], sector: "utilities" },
  { symbol: "9503.T", market: "JP", name: "関西電力", aliases: ["Kanden", "関電"], sector: "utilities" },
  { symbol: "9502.T", market: "JP", name: "中部電力", aliases: ["Chuden"], sector: "utilities" },
  { symbol: "9531.T", market: "JP", name: "東京瓦斯", aliases: ["東京ガス", "Tokyo Gas"], sector: "utilities" },
  { symbol: "9532.T", market: "JP", name: "大阪瓦斯", aliases: ["大阪ガス", "Osaka Gas"], sector: "utilities" },
  { symbol: "9508.T", market: "JP", name: "九州電力", aliases: ["Kyushu Electric"], sector: "utilities" },
  { symbol: "9504.T", market: "JP", name: "中国電力", aliases: ["Chugoku Electric"], sector: "utilities" },

  // ===== Real Estate / 不動産 =====
  { symbol: "PLD", market: "US", name: "Prologis", sector: "real-estate" },
  { symbol: "AMT", market: "US", name: "American Tower", sector: "real-estate" },
  { symbol: "EQIX", market: "US", name: "Equinix", sector: "real-estate" },
  { symbol: "SPG", market: "US", name: "Simon Property Group", sector: "real-estate" },
  { symbol: "O", market: "US", name: "Realty Income", sector: "real-estate" },
  { symbol: "CCI", market: "US", name: "Crown Castle", sector: "real-estate" },
  { symbol: "DLR", market: "US", name: "Digital Realty Trust", sector: "real-estate" },
  { symbol: "PSA", market: "US", name: "Public Storage", sector: "real-estate" },
  { symbol: "AVB", market: "US", name: "AvalonBay Communities", sector: "real-estate" },
  { symbol: "EQR", market: "US", name: "Equity Residential", sector: "real-estate" },
  { symbol: "WELL", market: "US", name: "Welltower", sector: "real-estate" },
  { symbol: "ARE", market: "US", name: "Alexandria Real Estate Equities", sector: "real-estate" },
  { symbol: "EXR", market: "US", name: "Extra Space Storage", sector: "real-estate" },
  { symbol: "VICI", market: "US", name: "VICI Properties", sector: "real-estate" },

  { symbol: "8801.T", market: "JP", name: "三井不動産", aliases: ["Mitsui Fudosan"], sector: "real-estate" },
  { symbol: "8802.T", market: "JP", name: "三菱地所", aliases: ["Mitsubishi Estate"], sector: "real-estate" },
  { symbol: "8830.T", market: "JP", name: "住友不動産", aliases: ["Sumitomo Realty"], sector: "real-estate" },
  { symbol: "3289.T", market: "JP", name: "東急不動産ホールディングス", aliases: ["Tokyu Fudosan"], sector: "real-estate" },
  { symbol: "8804.T", market: "JP", name: "東京建物", aliases: ["Tokyo Tatemono"], sector: "real-estate" },
  { symbol: "3231.T", market: "JP", name: "野村不動産ホールディングス", aliases: ["Nomura Real Estate"], sector: "real-estate" },

  // ===== ETFs / 投資信託 (上場投信) =====
  // --- Broad market (米国/グローバル指数連動) ---
  { symbol: "SPY", market: "US", name: "SPDR S&P 500 ETF", aliases: ["S&P500"], sector: "information-technology", type: "etf", etfCategory: "broad" },
  { symbol: "VOO", market: "US", name: "バンガード S&P 500 ETF", aliases: ["Vanguard S&P500"], sector: "information-technology", type: "etf", etfCategory: "broad" },
  { symbol: "IVV", market: "US", name: "iShares Core S&P 500 ETF", sector: "information-technology", type: "etf", etfCategory: "broad" },
  { symbol: "VTI", market: "US", name: "バンガード トータル・ストック・マーケット ETF", aliases: ["Vanguard Total Stock"], sector: "information-technology", type: "etf", etfCategory: "broad" },
  { symbol: "QQQ", market: "US", name: "インベスコ QQQ (NASDAQ-100)", aliases: ["NASDAQ100", "QQQ"], sector: "information-technology", type: "etf", etfCategory: "broad" },
  { symbol: "DIA", market: "US", name: "SPDR ダウ平均 ETF", aliases: ["Dow ETF"], sector: "industrials", type: "etf", etfCategory: "broad" },
  { symbol: "IWM", market: "US", name: "iShares ラッセル2000 ETF", aliases: ["Russell 2000"], sector: "industrials", type: "etf", etfCategory: "broad" },
  { symbol: "VT", market: "US", name: "バンガード トータル・ワールド・ストック ETF", sector: "information-technology", type: "etf", etfCategory: "broad" },
  { symbol: "VXUS", market: "US", name: "バンガード トータル・インターナショナル・ストック ETF", sector: "information-technology", type: "etf", etfCategory: "international" },
  { symbol: "VEA", market: "US", name: "バンガード FTSE 先進国市場 ETF", sector: "information-technology", type: "etf", etfCategory: "international" },
  { symbol: "VWO", market: "US", name: "バンガード FTSE エマージング・マーケッツ ETF", sector: "information-technology", type: "etf", etfCategory: "international" },
  { symbol: "EFA", market: "US", name: "iShares MSCI EAFE ETF", sector: "information-technology", type: "etf", etfCategory: "international" },
  { symbol: "EEM", market: "US", name: "iShares MSCI エマージング・マーケッツ ETF", sector: "information-technology", type: "etf", etfCategory: "international" },

  // --- Sector ETFs (SPDR) ---
  { symbol: "XLK", market: "US", name: "テクノロジー・セレクト・セクター SPDR", sector: "information-technology", type: "etf", etfCategory: "sector" },
  { symbol: "XLF", market: "US", name: "金融セレクト・セクター SPDR", sector: "financials", type: "etf", etfCategory: "sector" },
  { symbol: "XLE", market: "US", name: "エネルギー・セレクト・セクター SPDR", sector: "energy", type: "etf", etfCategory: "sector" },
  { symbol: "XLV", market: "US", name: "ヘルスケア・セレクト・セクター SPDR", sector: "health-care", type: "etf", etfCategory: "sector" },
  { symbol: "XLY", market: "US", name: "一般消費財セレクト・セクター SPDR", sector: "consumer-discretionary", type: "etf", etfCategory: "sector" },
  { symbol: "XLP", market: "US", name: "生活必需品セレクト・セクター SPDR", sector: "consumer-staples", type: "etf", etfCategory: "sector" },
  { symbol: "XLI", market: "US", name: "資本財セレクト・セクター SPDR", sector: "industrials", type: "etf", etfCategory: "sector" },
  { symbol: "XLU", market: "US", name: "公益事業セレクト・セクター SPDR", sector: "utilities", type: "etf", etfCategory: "sector" },
  { symbol: "XLB", market: "US", name: "素材セレクト・セクター SPDR", sector: "materials", type: "etf", etfCategory: "sector" },
  { symbol: "XLRE", market: "US", name: "不動産セレクト・セクター SPDR", sector: "real-estate", type: "etf", etfCategory: "sector" },
  { symbol: "XLC", market: "US", name: "コミュニケーションサービス・セレクト・セクター SPDR", sector: "communication-services", type: "etf", etfCategory: "sector" },
  { symbol: "SMH", market: "US", name: "VanEck 半導体株 ETF", sector: "information-technology", type: "etf", etfCategory: "sector" },
  { symbol: "SOXX", market: "US", name: "iShares 半導体株 ETF", sector: "information-technology", type: "etf", etfCategory: "sector" },

  // --- Thematic / Growth ---
  { symbol: "ARKK", market: "US", name: "ARK イノベーション ETF", aliases: ["ARK Innovation"], sector: "information-technology", type: "etf", etfCategory: "thematic" },
  { symbol: "ICLN", market: "US", name: "iShares グローバル・クリーンエネルギー ETF", sector: "utilities", type: "etf", etfCategory: "thematic" },
  { symbol: "TAN", market: "US", name: "インベスコ ソーラー ETF", sector: "energy", type: "etf", etfCategory: "thematic" },
  { symbol: "LIT", market: "US", name: "グローバル X リチウム & 電池技術 ETF", sector: "materials", type: "etf", etfCategory: "thematic" },
  { symbol: "BOTZ", market: "US", name: "グローバル X ロボティクス & AI ETF", sector: "information-technology", type: "etf", etfCategory: "thematic" },

  // --- Dividend / Income ---
  { symbol: "VYM", market: "US", name: "バンガード 高配当株 ETF", sector: "financials", type: "etf", etfCategory: "dividend" },
  { symbol: "SCHD", market: "US", name: "シュワブ 米国配当株 ETF", sector: "financials", type: "etf", etfCategory: "dividend" },
  { symbol: "VIG", market: "US", name: "バンガード 配当成長株 ETF", sector: "financials", type: "etf", etfCategory: "dividend" },
  { symbol: "HDV", market: "US", name: "iShares コア 米国高配当株 ETF", sector: "financials", type: "etf", etfCategory: "dividend" },

  // --- Bond ---
  { symbol: "AGG", market: "US", name: "iShares コア 米国総合債券 ETF", sector: "financials", type: "etf", etfCategory: "bond" },
  { symbol: "BND", market: "US", name: "バンガード 米国総合債券 ETF", sector: "financials", type: "etf", etfCategory: "bond" },
  { symbol: "TLT", market: "US", name: "iShares 米国20年超 国債 ETF", sector: "financials", type: "etf", etfCategory: "bond" },
  { symbol: "LQD", market: "US", name: "iShares iBoxx 米国投資適格社債 ETF", sector: "financials", type: "etf", etfCategory: "bond" },
  { symbol: "HYG", market: "US", name: "iShares iBoxx 米国ハイイールド社債 ETF", sector: "financials", type: "etf", etfCategory: "bond" },

  // --- Commodity ---
  { symbol: "GLD", market: "US", name: "SPDR ゴールド・トラスト", aliases: ["Gold ETF"], sector: "materials", type: "etf", etfCategory: "commodity" },
  { symbol: "IAU", market: "US", name: "iShares ゴールド・トラスト", sector: "materials", type: "etf", etfCategory: "commodity" },
  { symbol: "SLV", market: "US", name: "iShares シルバー・トラスト", sector: "materials", type: "etf", etfCategory: "commodity" },
  { symbol: "USO", market: "US", name: "米国オイル・ファンド", sector: "energy", type: "etf", etfCategory: "commodity" },

  // --- Leveraged ---
  { symbol: "TQQQ", market: "US", name: "ProShares ウルトラプロ QQQ (3倍)", sector: "information-technology", type: "etf", etfCategory: "leveraged" },
  { symbol: "SOXL", market: "US", name: "Direxion 半導体株 3倍ブル", sector: "information-technology", type: "etf", etfCategory: "leveraged" },
  { symbol: "SQQQ", market: "US", name: "ProShares ウルトラプロ ショート QQQ (3倍)", sector: "information-technology", type: "etf", etfCategory: "leveraged" },

  // --- 日本ETF ---
  { symbol: "1306.T", market: "JP", name: "NEXT FUNDS TOPIX 連動型上場投信", aliases: ["TOPIX ETF"], sector: "information-technology", type: "etf", etfCategory: "broad" },
  { symbol: "1321.T", market: "JP", name: "NEXT FUNDS 日経225連動型上場投信", aliases: ["日経225 ETF", "Nikkei225"], sector: "information-technology", type: "etf", etfCategory: "broad" },
  { symbol: "1320.T", market: "JP", name: "ダイワ上場投信-日経225", sector: "information-technology", type: "etf", etfCategory: "broad" },
  { symbol: "1330.T", market: "JP", name: "上場インデックスファンド 225", sector: "information-technology", type: "etf", etfCategory: "broad" },
  { symbol: "2558.T", market: "JP", name: "MAXIS 米国株式 (S&P500) 上場投信", aliases: ["MAXIS米国"], sector: "information-technology", type: "etf", etfCategory: "international" },
  { symbol: "2559.T", market: "JP", name: "MAXIS 全世界株式 (オール・カントリー) 上場投信", aliases: ["オルカン"], sector: "information-technology", type: "etf", etfCategory: "international" },
  { symbol: "1655.T", market: "JP", name: "iシェアーズ S&P 500 米国株 ETF (東証)", sector: "information-technology", type: "etf", etfCategory: "international" },
  { symbol: "2563.T", market: "JP", name: "iシェアーズ S&P 500 米国株 ETF (為替ヘッジあり)", sector: "information-technology", type: "etf", etfCategory: "international" },
  { symbol: "1545.T", market: "JP", name: "NEXT FUNDS NASDAQ-100 連動型上場投信", aliases: ["NASDAQ100 (JP)"], sector: "information-technology", type: "etf", etfCategory: "international" },
  { symbol: "1489.T", market: "JP", name: "NEXT FUNDS 日経平均高配当株50指数 連動型上場投信", aliases: ["日経高配当50"], sector: "financials", type: "etf", etfCategory: "dividend" },
  { symbol: "1577.T", market: "JP", name: "NEXT FUNDS 野村日本株高配当70 連動型上場投信", sector: "financials", type: "etf", etfCategory: "dividend" },
  { symbol: "1326.T", market: "JP", name: "SPDR ゴールド・シェア (東証)", sector: "materials", type: "etf", etfCategory: "commodity" },
];

const SYMBOL_INDEX = new Map(STOCKS_CATALOG.map((s) => [s.symbol, s]));

export function findStockBySymbol(symbol: string): CatalogStock | undefined {
  return SYMBOL_INDEX.get(symbol);
}

export function getStocksBySector(
  sector: GicsSectorId,
  includeEtf = false,
): CatalogStock[] {
  return STOCKS_CATALOG.filter(
    (s) => s.sector === sector && (includeEtf || s.type !== "etf"),
  );
}

export function getEtfs(): CatalogStock[] {
  return STOCKS_CATALOG.filter((s) => s.type === "etf");
}

export function getAllStocks(includeEtf = false): CatalogStock[] {
  return includeEtf
    ? STOCKS_CATALOG
    : STOCKS_CATALOG.filter((s) => s.type !== "etf");
}

export function getJpStocks(): CatalogStock[] {
  return STOCKS_CATALOG.filter((s) => s.market === "JP");
}
