import type { GicsSectorId } from "./gics";
import { US_STOCKS_SUPPLEMENT } from "./us-stocks-list";
import { US_SECTOR_MAP } from "./us-sector-supplement";
import { TSE_NAMES } from "./tse-names";
import { JP_SECTOR_MAP } from "./jp-sector-supplement";

export type CatalogStock = {
  symbol: string;
  market: "JP" | "US";
  name: string;
  aliases?: string[];
  sector: GicsSectorId;
  /** "stock" by default. ETFs/funds are tagged "etf" and shown on /etfs. */
  type?: "stock" | "etf";
  /** For ETFs only — themed category for grouping on /etfs page. */
  etfCategory?:
    | "broad"
    | "sector"
    | "international"
    | "bond"
    | "commodity"
    | "thematic"
    | "dividend"
    | "leveraged";
};

export const STOCKS_CATALOG: CatalogStock[] = [
  // ===== Information Technology / 情報技術 =====
  { symbol: "AAPL", market: "US", name: "Apple", sector: "information-technology" },
  { symbol: "MSFT", market: "US", name: "Microsoft", sector: "information-technology" },
  { symbol: "NVDA", market: "US", name: "NVIDIA", sector: "information-technology" },
  { symbol: "AVGO", market: "US", name: "Broadcom", sector: "information-technology" },
  { symbol: "ORCL", market: "US", name: "Oracle", sector: "information-technology" },
  { symbol: "CRM", market: "US", name: "Salesforce", sector: "information-technology" },
  { symbol: "ADBE", market: "US", name: "Adobe", sector: "information-technology" },
  { symbol: "AMD", market: "US", name: "Advanced Micro Devices", sector: "information-technology" },
  { symbol: "CSCO", market: "US", name: "Cisco Systems", sector: "information-technology" },
  { symbol: "INTC", market: "US", name: "Intel", sector: "information-technology" },
  { symbol: "IBM", market: "US", name: "IBM", sector: "information-technology" },
  { symbol: "NOW", market: "US", name: "ServiceNow", sector: "information-technology" },
  { symbol: "INTU", market: "US", name: "Intuit", sector: "information-technology" },
  { symbol: "QCOM", market: "US", name: "Qualcomm", sector: "information-technology" },
  { symbol: "TXN", market: "US", name: "Texas Instruments", sector: "information-technology" },
  { symbol: "AMAT", market: "US", name: "Applied Materials", sector: "information-technology" },
  { symbol: "MU", market: "US", name: "Micron Technology", sector: "information-technology" },
  { symbol: "PANW", market: "US", name: "Palo Alto Networks", sector: "information-technology" },
  { symbol: "KLAC", market: "US", name: "KLA Corporation", sector: "information-technology" },
  { symbol: "LRCX", market: "US", name: "Lam Research", sector: "information-technology" },
  { symbol: "ADI", market: "US", name: "Analog Devices", sector: "information-technology" },
  { symbol: "SNPS", market: "US", name: "Synopsys", sector: "information-technology" },
  { symbol: "CDNS", market: "US", name: "Cadence Design Systems", sector: "information-technology" },
  { symbol: "ANET", market: "US", name: "Arista Networks", sector: "information-technology" },
  { symbol: "FTNT", market: "US", name: "Fortinet", sector: "information-technology" },
  { symbol: "ACN", market: "US", name: "Accenture", sector: "information-technology" },
  { symbol: "HPE", market: "US", name: "Hewlett Packard Enterprise", sector: "information-technology" },
  { symbol: "HPQ", market: "US", name: "HP Inc.", sector: "information-technology" },
  { symbol: "DELL", market: "US", name: "Dell Technologies", sector: "information-technology" },
  { symbol: "PLTR", market: "US", name: "Palantir Technologies", sector: "information-technology" },
  { symbol: "SMCI", market: "US", name: "Super Micro Computer", sector: "information-technology" },
  { symbol: "WDAY", market: "US", name: "Workday", sector: "information-technology" },
  { symbol: "CRWD", market: "US", name: "CrowdStrike", sector: "information-technology" },
  { symbol: "SNOW", market: "US", name: "Snowflake", sector: "information-technology" },
  { symbol: "NET", market: "US", name: "Cloudflare", sector: "information-technology" },
  { symbol: "DDOG", market: "US", name: "Datadog", sector: "information-technology" },
  { symbol: "ZS", market: "US", name: "Zscaler", sector: "information-technology" },
  { symbol: "OKTA", market: "US", name: "Okta", sector: "information-technology" },
  { symbol: "MDB", market: "US", name: "MongoDB", sector: "information-technology" },
  { symbol: "ARM", market: "US", name: "ARM Holdings", sector: "information-technology" },
  { symbol: "MRVL", market: "US", name: "Marvell Technology", sector: "information-technology" },
  { symbol: "MPWR", market: "US", name: "Monolithic Power Systems", sector: "information-technology" },
  { symbol: "MCHP", market: "US", name: "Microchip Technology", sector: "information-technology" },
  { symbol: "WDC", market: "US", name: "Western Digital", sector: "information-technology" },
  { symbol: "STX", market: "US", name: "Seagate Technology", sector: "information-technology" },
  { symbol: "CTSH", market: "US", name: "Cognizant Technology Solutions", sector: "information-technology" },
  { symbol: "TEAM", market: "US", name: "Atlassian", sector: "information-technology" },
  { symbol: "VEEV", market: "US", name: "Veeva Systems", sector: "information-technology" },
  { symbol: "HUBS", market: "US", name: "HubSpot", sector: "information-technology" },
  { symbol: "VRT", market: "US", name: "Vertiv Holdings", sector: "information-technology" },
  { symbol: "CHKP", market: "US", name: "Check Point Software", sector: "information-technology" },
  { symbol: "APP", market: "US", name: "AppLovin", sector: "information-technology" },
  { symbol: "GTLB", market: "US", name: "GitLab", sector: "information-technology" },
  { symbol: "MSTR", market: "US", name: "MicroStrategy", sector: "information-technology" },

  { symbol: "6758.T", market: "JP", name: "ソニーグループ", aliases: ["Sony", "ソニー"], sector: "information-technology" },
  { symbol: "6861.T", market: "JP", name: "キーエンス", aliases: ["Keyence"], sector: "information-technology" },
  { symbol: "8035.T", market: "JP", name: "東京エレクトロン", aliases: ["Tokyo Electron", "TEL"], sector: "information-technology" },
  { symbol: "6098.T", market: "JP", name: "リクルートホールディングス", aliases: ["Recruit", "リクルート"], sector: "information-technology" },
  { symbol: "6920.T", market: "JP", name: "レーザーテック", aliases: ["Lasertec"], sector: "information-technology" },
  { symbol: "6857.T", market: "JP", name: "アドバンテスト", aliases: ["Advantest"], sector: "information-technology" },
  { symbol: "6971.T", market: "JP", name: "京セラ", aliases: ["Kyocera"], sector: "information-technology" },
  { symbol: "6981.T", market: "JP", name: "村田製作所", aliases: ["Murata"], sector: "information-technology" },
  { symbol: "6701.T", market: "JP", name: "NEC", aliases: ["日本電気"], sector: "information-technology" },
  { symbol: "6702.T", market: "JP", name: "富士通", aliases: ["Fujitsu"], sector: "information-technology" },
  { symbol: "6724.T", market: "JP", name: "セイコーエプソン", aliases: ["Epson", "エプソン"], sector: "information-technology" },
  { symbol: "7751.T", market: "JP", name: "キヤノン", aliases: ["Canon", "キャノン"], sector: "information-technology" },
  { symbol: "4307.T", market: "JP", name: "野村総合研究所", aliases: ["NRI", "野村総研"], sector: "information-technology" },
  { symbol: "9613.T", market: "JP", name: "NTTデータ", aliases: ["NTT Data"], sector: "information-technology" },
  { symbol: "4768.T", market: "JP", name: "大塚商会", aliases: ["Otsuka Shokai"], sector: "information-technology" },
  { symbol: "6770.T", market: "JP", name: "アルプスアルパイン", aliases: ["Alps Alpine"], sector: "information-technology" },
  { symbol: "6963.T", market: "JP", name: "ローム", aliases: ["ROHM"], sector: "information-technology" },
  { symbol: "285A.T", market: "JP", name: "キオクシアホールディングス", aliases: ["Kioxia", "キオクシア", "KIOXIA", "6600"], sector: "information-technology" },
  { symbol: "6532.T", market: "JP", name: "ベイカレント・コンサルティング", aliases: ["Baycurrent"], sector: "information-technology" },
  { symbol: "6762.T", market: "JP", name: "TDK", aliases: ["TDK Corporation"], sector: "information-technology" },
  { symbol: "4062.T", market: "JP", name: "イビデン", aliases: ["Ibiden"], sector: "information-technology" },
  { symbol: "4385.T", market: "JP", name: "メルカリ", aliases: ["Mercari"], sector: "information-technology" },
  { symbol: "3064.T", market: "JP", name: "MonotaRO", aliases: ["モノタロウ"], sector: "information-technology" },
  { symbol: "3769.T", market: "JP", name: "GMOペイメントゲートウェイ", aliases: ["GMO PG", "GMO Payment"], sector: "information-technology" },
  { symbol: "3915.T", market: "JP", name: "テラスカイ", aliases: ["TerraSky", "Terrasky", "クラウド", "Salesforce"], sector: "information-technology" },
  // 量子コンピュータ
  { symbol: "IONQ", market: "US", name: "IonQ", aliases: ["イオンキュー", "量子コンピュータ"], sector: "information-technology" },
  { symbol: "RGTI", market: "US", name: "Rigetti Computing", aliases: ["リジェッティ", "量子コンピュータ"], sector: "information-technology" },
  { symbol: "QBTS", market: "US", name: "D-Wave Quantum", aliases: ["Dウェーブ", "量子コンピュータ"], sector: "information-technology" },
  { symbol: "QUBT", market: "US", name: "Quantum Computing Inc", aliases: ["量子コンピュータ"], sector: "information-technology" },
  { symbol: "ARQQ", market: "US", name: "Arqit Quantum", aliases: ["量子暗号"], sector: "information-technology" },

  { symbol: "3659.T", market: "JP", name: "ネクソン", aliases: ["Nexon"], sector: "communication-services" },

  // ===== Communication Services / コミュニケーション =====
  { symbol: "GOOGL", market: "US", name: "Alphabet (Google)", aliases: ["Google"], sector: "communication-services" },
  { symbol: "META", market: "US", name: "Meta Platforms", aliases: ["Facebook"], sector: "communication-services" },
  { symbol: "NFLX", market: "US", name: "Netflix", sector: "communication-services" },
  { symbol: "DIS", market: "US", name: "Walt Disney", sector: "communication-services" },
  { symbol: "VZ", market: "US", name: "Verizon Communications", sector: "communication-services" },
  { symbol: "T", market: "US", name: "AT&T", sector: "communication-services" },
  { symbol: "CMCSA", market: "US", name: "Comcast", sector: "communication-services" },
  { symbol: "TMUS", market: "US", name: "T-Mobile US", sector: "communication-services" },
  { symbol: "EA", market: "US", name: "Electronic Arts", sector: "communication-services" },
  { symbol: "TTWO", market: "US", name: "Take-Two Interactive", sector: "communication-services" },
  { symbol: "WBD", market: "US", name: "Warner Bros. Discovery", sector: "communication-services" },
  { symbol: "PARA", market: "US", name: "Paramount Global", sector: "communication-services" },
  { symbol: "CHTR", market: "US", name: "Charter Communications", sector: "communication-services" },
  { symbol: "ROKU", market: "US", name: "Roku", sector: "communication-services" },
  { symbol: "SPOT", market: "US", name: "Spotify", sector: "communication-services" },
  { symbol: "PINS", market: "US", name: "Pinterest", sector: "communication-services" },
  { symbol: "SNAP", market: "US", name: "Snap", aliases: ["Snapchat"], sector: "communication-services" },
  { symbol: "RDDT", market: "US", name: "Reddit", sector: "communication-services" },
  { symbol: "LYV", market: "US", name: "Live Nation Entertainment", sector: "communication-services" },
  { symbol: "MTCH", market: "US", name: "Match Group", aliases: ["Tinder"], sector: "communication-services" },
  { symbol: "RBLX", market: "US", name: "Roblox", sector: "communication-services" },
  { symbol: "WMG", market: "US", name: "Warner Music Group", sector: "communication-services" },
  { symbol: "ZM", market: "US", name: "Zoom Video Communications", aliases: ["Zoom", "ズーム"], sector: "communication-services" },
  { symbol: "TWLO", market: "US", name: "Twilio", sector: "communication-services" },

  { symbol: "9984.T", market: "JP", name: "ソフトバンクグループ", aliases: ["ソフトバンク", "SoftBank"], sector: "communication-services" },
  { symbol: "9432.T", market: "JP", name: "日本電信電話", aliases: ["NTT"], sector: "communication-services" },
  { symbol: "9433.T", market: "JP", name: "KDDI", aliases: ["au"], sector: "communication-services" },
  { symbol: "9434.T", market: "JP", name: "ソフトバンク", aliases: ["SoftBank Corp"], sector: "communication-services" },
  { symbol: "4689.T", market: "JP", name: "LINEヤフー", aliases: ["LY", "Yahoo!", "ヤフー"], sector: "communication-services" },
  { symbol: "4751.T", market: "JP", name: "サイバーエージェント", aliases: ["CyberAgent", "サイバー"], sector: "communication-services" },
  { symbol: "2432.T", market: "JP", name: "ディー・エヌ・エー", aliases: ["DeNA"], sector: "communication-services" },
  { symbol: "9602.T", market: "JP", name: "東宝", aliases: ["Toho"], sector: "communication-services" },
  { symbol: "7974.T", market: "JP", name: "任天堂", aliases: ["Nintendo", "ニンテンドー"], sector: "communication-services" },
  { symbol: "9684.T", market: "JP", name: "スクウェア・エニックス・ホールディングス", aliases: ["Square Enix", "スクエニ"], sector: "communication-services" },
  { symbol: "7832.T", market: "JP", name: "バンダイナムコホールディングス", aliases: ["Bandai Namco", "バンダイ"], sector: "communication-services" },
  { symbol: "9697.T", market: "JP", name: "カプコン", aliases: ["Capcom"], sector: "communication-services" },
  { symbol: "9766.T", market: "JP", name: "コナミグループ", aliases: ["Konami", "コナミ"], sector: "communication-services" },
  { symbol: "4324.T", market: "JP", name: "電通グループ", aliases: ["Dentsu", "電通"], sector: "communication-services" },
  { symbol: "3765.T", market: "JP", name: "ガンホー・オンライン・エンターテイメント", aliases: ["GungHo", "ガンホー"], sector: "communication-services" },
  { symbol: "2121.T", market: "JP", name: "ミクシィ", aliases: ["Mixi"], sector: "communication-services" },

  // ===== Consumer Discretionary / 一般消費財 =====
  { symbol: "AMZN", market: "US", name: "Amazon", sector: "consumer-discretionary" },
  { symbol: "TSLA", market: "US", name: "Tesla", sector: "consumer-discretionary" },
  { symbol: "HD", market: "US", name: "Home Depot", sector: "consumer-discretionary" },
  { symbol: "MCD", market: "US", name: "McDonald's", sector: "consumer-discretionary" },
  { symbol: "NKE", market: "US", name: "Nike", sector: "consumer-discretionary" },
  { symbol: "LOW", market: "US", name: "Lowe's", sector: "consumer-discretionary" },
  { symbol: "SBUX", market: "US", name: "Starbucks", sector: "consumer-discretionary" },
  { symbol: "BKNG", market: "US", name: "Booking Holdings", sector: "consumer-discretionary" },
  { symbol: "TJX", market: "US", name: "TJX Companies", sector: "consumer-discretionary" },
  { symbol: "GM", market: "US", name: "General Motors", sector: "consumer-discretionary" },
  { symbol: "F", market: "US", name: "Ford Motor", sector: "consumer-discretionary" },
  { symbol: "MAR", market: "US", name: "Marriott International", sector: "consumer-discretionary" },
  { symbol: "ROST", market: "US", name: "Ross Stores", sector: "consumer-discretionary" },
  { symbol: "ABNB", market: "US", name: "Airbnb", sector: "consumer-discretionary" },
  { symbol: "DHI", market: "US", name: "D.R. Horton", sector: "consumer-discretionary" },
  { symbol: "LEN", market: "US", name: "Lennar", sector: "consumer-discretionary" },
  { symbol: "LULU", market: "US", name: "Lululemon Athletica", sector: "consumer-discretionary" },
  { symbol: "ORLY", market: "US", name: "O'Reilly Automotive", sector: "consumer-discretionary" },
  { symbol: "AZO", market: "US", name: "AutoZone", sector: "consumer-discretionary" },
  { symbol: "CMG", market: "US", name: "Chipotle Mexican Grill", sector: "consumer-discretionary" },
  { symbol: "YUM", market: "US", name: "Yum! Brands", sector: "consumer-discretionary" },
  { symbol: "RCL", market: "US", name: "Royal Caribbean Cruises", sector: "consumer-discretionary" },
  { symbol: "EBAY", market: "US", name: "eBay", sector: "consumer-discretionary" },
  { symbol: "DPZ", market: "US", name: "Domino's Pizza", sector: "consumer-discretionary" },
  { symbol: "SHOP", market: "US", name: "Shopify", sector: "consumer-discretionary" },
  { symbol: "RIVN", market: "US", name: "Rivian Automotive", sector: "consumer-discretionary" },
  { symbol: "DASH", market: "US", name: "DoorDash", sector: "consumer-discretionary" },
  { symbol: "PHM", market: "US", name: "PulteGroup", sector: "consumer-discretionary" },
  { symbol: "TOL", market: "US", name: "Toll Brothers", sector: "consumer-discretionary" },
  { symbol: "WING", market: "US", name: "Wingstop", sector: "consumer-discretionary" },
  { symbol: "HAS", market: "US", name: "Hasbro", sector: "consumer-discretionary" },
  { symbol: "MAT", market: "US", name: "Mattel", sector: "consumer-discretionary" },
  { symbol: "CVNA", market: "US", name: "Carvana", sector: "consumer-discretionary" },
  { symbol: "LYFT", market: "US", name: "Lyft", sector: "consumer-discretionary" },
  { symbol: "LCID", market: "US", name: "Lucid Group", aliases: ["ルーシッド", "Lucid Motors"], sector: "consumer-discretionary" },

  { symbol: "7203.T", market: "JP", name: "トヨタ自動車", aliases: ["Toyota", "トヨタ"], sector: "consumer-discretionary" },
  { symbol: "7267.T", market: "JP", name: "本田技研工業", aliases: ["Honda", "ホンダ"], sector: "consumer-discretionary" },
  { symbol: "7201.T", market: "JP", name: "日産自動車", aliases: ["Nissan", "ニッサン"], sector: "consumer-discretionary" },
  { symbol: "7269.T", market: "JP", name: "スズキ", aliases: ["Suzuki"], sector: "consumer-discretionary" },
  { symbol: "7270.T", market: "JP", name: "SUBARU", aliases: ["スバル", "Subaru"], sector: "consumer-discretionary" },
  { symbol: "7261.T", market: "JP", name: "マツダ", aliases: ["Mazda"], sector: "consumer-discretionary" },
  { symbol: "9983.T", market: "JP", name: "ファーストリテイリング", aliases: ["Fast Retailing", "ユニクロ", "Uniqlo"], sector: "consumer-discretionary" },
  { symbol: "3092.T", market: "JP", name: "ZOZO", aliases: ["ゾゾ"], sector: "consumer-discretionary" },
  { symbol: "4661.T", market: "JP", name: "オリエンタルランド", aliases: ["Oriental Land", "ディズニーランド"], sector: "consumer-discretionary" },
  { symbol: "9831.T", market: "JP", name: "ヤマダホールディングス", aliases: ["Yamada"], sector: "consumer-discretionary" },
  { symbol: "8175.T", market: "JP", name: "ベスト電器", sector: "consumer-discretionary" },
  { symbol: "5108.T", market: "JP", name: "ブリヂストン", aliases: ["Bridgestone"], sector: "consumer-discretionary" },
  { symbol: "1928.T", market: "JP", name: "積水ハウス", aliases: ["Sekisui House"], sector: "consumer-discretionary" },
  { symbol: "1925.T", market: "JP", name: "大和ハウス工業", aliases: ["Daiwa House", "大和ハウス"], sector: "consumer-discretionary" },
  { symbol: "8278.T", market: "JP", name: "フジ", sector: "consumer-staples" },
  { symbol: "3086.T", market: "JP", name: "J.フロント リテイリング", aliases: ["J Front"], sector: "consumer-discretionary" },
  { symbol: "8233.T", market: "JP", name: "高島屋", aliases: ["Takashimaya"], sector: "consumer-discretionary" },
  { symbol: "8252.T", market: "JP", name: "丸井グループ", aliases: ["Marui"], sector: "consumer-discretionary" },
  { symbol: "3099.T", market: "JP", name: "三越伊勢丹ホールディングス", aliases: ["Mitsukoshi Isetan"], sector: "consumer-discretionary" },
  { symbol: "9843.T", market: "JP", name: "ニトリホールディングス", aliases: ["Nitori", "ニトリ"], sector: "consumer-discretionary" },
  { symbol: "7453.T", market: "JP", name: "良品計画", aliases: ["Muji", "MUJI", "無印良品"], sector: "consumer-discretionary" },
  { symbol: "3197.T", market: "JP", name: "すかいらーくホールディングス", aliases: ["Skylark", "ガスト", "Gusto"], sector: "consumer-discretionary" },
  { symbol: "2702.T", market: "JP", name: "日本マクドナルドホールディングス", aliases: ["McDonald's Japan", "マクドナルド"], sector: "consumer-discretionary" },
  { symbol: "3543.T", market: "JP", name: "コメダホールディングス", aliases: ["Komeda", "コメダ珈琲"], sector: "consumer-discretionary" },
  { symbol: "7564.T", market: "JP", name: "ワークマン", aliases: ["Workman"], sector: "consumer-discretionary" },
  { symbol: "9861.T", market: "JP", name: "吉野家ホールディングス", aliases: ["Yoshinoya", "吉野家"], sector: "consumer-discretionary" },
  { symbol: "4666.T", market: "JP", name: "パーク24", aliases: ["Park24"], sector: "consumer-discretionary" },

  // ===== Consumer Staples / 生活必需品 =====
  { symbol: "PG", market: "US", name: "Procter & Gamble", sector: "consumer-staples" },
  { symbol: "KO", market: "US", name: "Coca-Cola", sector: "consumer-staples" },
  { symbol: "PEP", market: "US", name: "PepsiCo", sector: "consumer-staples" },
  { symbol: "WMT", market: "US", name: "Walmart", sector: "consumer-staples" },
  { symbol: "COST", market: "US", name: "Costco Wholesale", sector: "consumer-staples" },
  { symbol: "PM", market: "US", name: "Philip Morris International", sector: "consumer-staples" },
  { symbol: "MO", market: "US", name: "Altria Group", sector: "consumer-staples" },
  { symbol: "MDLZ", market: "US", name: "Mondelez International", sector: "consumer-staples" },
  { symbol: "CL", market: "US", name: "Colgate-Palmolive", sector: "consumer-staples" },
  { symbol: "KMB", market: "US", name: "Kimberly-Clark", sector: "consumer-staples" },
  { symbol: "GIS", market: "US", name: "General Mills", sector: "consumer-staples" },
  { symbol: "KHC", market: "US", name: "Kraft Heinz", sector: "consumer-staples" },
  { symbol: "STZ", market: "US", name: "Constellation Brands", sector: "consumer-staples" },
  { symbol: "KR", market: "US", name: "Kroger", sector: "consumer-staples" },
  { symbol: "ADM", market: "US", name: "Archer-Daniels-Midland", sector: "consumer-staples" },
  { symbol: "TGT", market: "US", name: "Target", sector: "consumer-staples" },
  { symbol: "EL", market: "US", name: "Estée Lauder", sector: "consumer-staples" },
  { symbol: "SYY", market: "US", name: "Sysco", sector: "consumer-staples" },
  { symbol: "HSY", market: "US", name: "Hershey", sector: "consumer-staples" },
  { symbol: "CHD", market: "US", name: "Church & Dwight", sector: "consumer-staples" },
  { symbol: "KDP", market: "US", name: "Keurig Dr Pepper", sector: "consumer-staples" },
  { symbol: "MKC", market: "US", name: "McCormick & Company", sector: "consumer-staples" },
  { symbol: "HRL", market: "US", name: "Hormel Foods", sector: "consumer-staples" },
  { symbol: "SJM", market: "US", name: "J.M. Smucker", sector: "consumer-staples" },
  { symbol: "CELH", market: "US", name: "Celsius Holdings", sector: "consumer-staples" },
  { symbol: "BJ", market: "US", name: "BJ's Wholesale Club", sector: "consumer-staples" },

  { symbol: "2914.T", market: "JP", name: "日本たばこ産業", aliases: ["JT", "Japan Tobacco"], sector: "consumer-staples" },
  { symbol: "2502.T", market: "JP", name: "アサヒグループホールディングス", aliases: ["Asahi", "アサヒビール"], sector: "consumer-staples" },
  { symbol: "2503.T", market: "JP", name: "キリンホールディングス", aliases: ["Kirin", "キリン"], sector: "consumer-staples" },
  { symbol: "2802.T", market: "JP", name: "味の素", aliases: ["Ajinomoto"], sector: "consumer-staples" },
  { symbol: "2269.T", market: "JP", name: "明治ホールディングス", aliases: ["Meiji", "明治"], sector: "consumer-staples" },
  { symbol: "2587.T", market: "JP", name: "サントリー食品インターナショナル", aliases: ["Suntory", "サントリー"], sector: "consumer-staples" },
  { symbol: "2897.T", market: "JP", name: "日清食品ホールディングス", aliases: ["Nissin Foods", "日清"], sector: "consumer-staples" },
  { symbol: "2801.T", market: "JP", name: "キッコーマン", aliases: ["Kikkoman"], sector: "consumer-staples" },
  { symbol: "4452.T", market: "JP", name: "花王", aliases: ["Kao"], sector: "consumer-staples" },
  { symbol: "4911.T", market: "JP", name: "資生堂", aliases: ["Shiseido"], sector: "consumer-staples" },
  { symbol: "8113.T", market: "JP", name: "ユニ・チャーム", aliases: ["Unicharm", "ユニチャーム"], sector: "consumer-staples" },
  { symbol: "3088.T", market: "JP", name: "マツキヨココカラ&カンパニー", aliases: ["Matsukiyo"], sector: "consumer-staples" },
  { symbol: "8267.T", market: "JP", name: "イオン", aliases: ["Aeon"], sector: "consumer-staples" },
  { symbol: "3382.T", market: "JP", name: "セブン&アイ・ホールディングス", aliases: ["Seven & i", "セブン", "7-Eleven"], sector: "consumer-staples" },
  { symbol: "8028.T", market: "JP", name: "ファミリーマート", aliases: ["FamilyMart"], sector: "consumer-staples" },
  { symbol: "2670.T", market: "JP", name: "エービーシー・マート", aliases: ["ABC Mart"], sector: "consumer-discretionary" },
  { symbol: "2811.T", market: "JP", name: "カゴメ", aliases: ["Kagome"], sector: "consumer-staples" },
  { symbol: "3349.T", market: "JP", name: "コスモス薬品", aliases: ["Cosmos Drug"], sector: "consumer-staples" },
  { symbol: "7649.T", market: "JP", name: "スギホールディングス", aliases: ["Sugi", "スギ薬局"], sector: "consumer-staples" },
  { symbol: "4927.T", market: "JP", name: "ポーラ・オルビスホールディングス", aliases: ["POLA ORBIS", "ポーラ"], sector: "consumer-staples" },
  { symbol: "2875.T", market: "JP", name: "東洋水産", aliases: ["Toyo Suisan", "マルちゃん"], sector: "consumer-staples" },
  { symbol: "2264.T", market: "JP", name: "森永乳業", aliases: ["Morinaga Milk", "森永"], sector: "consumer-staples" },
  { symbol: "4922.T", market: "JP", name: "コーセー", aliases: ["Kose"], sector: "consumer-staples" },
  { symbol: "2212.T", market: "JP", name: "山崎製パン", aliases: ["Yamazaki Baking", "ヤマザキ"], sector: "consumer-staples" },

  // ===== Health Care / ヘルスケア =====
  { symbol: "JNJ", market: "US", name: "Johnson & Johnson", sector: "health-care" },
  { symbol: "LLY", market: "US", name: "Eli Lilly", sector: "health-care" },
  { symbol: "UNH", market: "US", name: "UnitedHealth Group", sector: "health-care" },
  { symbol: "PFE", market: "US", name: "Pfizer", sector: "health-care" },
  { symbol: "MRK", market: "US", name: "Merck", sector: "health-care" },
  { symbol: "ABBV", market: "US", name: "AbbVie", sector: "health-care" },
  { symbol: "TMO", market: "US", name: "Thermo Fisher Scientific", sector: "health-care" },
  { symbol: "ABT", market: "US", name: "Abbott Laboratories", sector: "health-care" },
  { symbol: "DHR", market: "US", name: "Danaher", sector: "health-care" },
  { symbol: "BMY", market: "US", name: "Bristol-Myers Squibb", sector: "health-care" },
  { symbol: "AMGN", market: "US", name: "Amgen", sector: "health-care" },
  { symbol: "GILD", market: "US", name: "Gilead Sciences", sector: "health-care" },
  { symbol: "MDT", market: "US", name: "Medtronic", sector: "health-care" },
  { symbol: "ISRG", market: "US", name: "Intuitive Surgical", sector: "health-care" },
  { symbol: "CVS", market: "US", name: "CVS Health", sector: "health-care" },
  { symbol: "ELV", market: "US", name: "Elevance Health", sector: "health-care" },
  { symbol: "REGN", market: "US", name: "Regeneron Pharmaceuticals", sector: "health-care" },
  { symbol: "VRTX", market: "US", name: "Vertex Pharmaceuticals", sector: "health-care" },
  { symbol: "ZTS", market: "US", name: "Zoetis", sector: "health-care" },
  { symbol: "BIIB", market: "US", name: "Biogen", sector: "health-care" },
  { symbol: "MRNA", market: "US", name: "Moderna", sector: "health-care" },
  { symbol: "BSX", market: "US", name: "Boston Scientific", sector: "health-care" },
  { symbol: "HIMS", market: "US", name: "Hims & Hers Health", sector: "health-care" },
  { symbol: "DXCM", market: "US", name: "DexCom", sector: "health-care" },
  { symbol: "EW", market: "US", name: "Edwards Lifesciences", sector: "health-care" },
  { symbol: "BDX", market: "US", name: "Becton Dickinson", sector: "health-care" },
  { symbol: "CI", market: "US", name: "Cigna Group", sector: "health-care" },
  { symbol: "HUM", market: "US", name: "Humana", sector: "health-care" },
  { symbol: "ALGN", market: "US", name: "Align Technology", sector: "health-care" },
  { symbol: "PODD", market: "US", name: "Insulet", sector: "health-care" },
  { symbol: "EXAS", market: "US", name: "Exact Sciences", sector: "health-care" },
  { symbol: "MOH", market: "US", name: "Molina Healthcare", sector: "health-care" },

  { symbol: "4519.T", market: "JP", name: "中外製薬", aliases: ["Chugai"], sector: "health-care" },
  { symbol: "4502.T", market: "JP", name: "武田薬品工業", aliases: ["Takeda", "武田薬品"], sector: "health-care" },
  { symbol: "4543.T", market: "JP", name: "テルモ", aliases: ["Terumo"], sector: "health-care" },
  { symbol: "4523.T", market: "JP", name: "エーザイ", aliases: ["Eisai"], sector: "health-care" },
  { symbol: "4568.T", market: "JP", name: "第一三共", aliases: ["Daiichi Sankyo"], sector: "health-care" },
  { symbol: "4503.T", market: "JP", name: "アステラス製薬", aliases: ["Astellas", "アステラス"], sector: "health-care" },
  { symbol: "4578.T", market: "JP", name: "大塚ホールディングス", aliases: ["Otsuka", "大塚"], sector: "health-care" },
  { symbol: "7741.T", market: "JP", name: "HOYA", sector: "health-care" },
  { symbol: "6869.T", market: "JP", name: "シスメックス", aliases: ["Sysmex"], sector: "health-care" },
  { symbol: "7733.T", market: "JP", name: "オリンパス", aliases: ["Olympus"], sector: "health-care" },
  { symbol: "4151.T", market: "JP", name: "協和キリン", aliases: ["Kyowa Kirin"], sector: "health-care" },
  { symbol: "4507.T", market: "JP", name: "塩野義製薬", aliases: ["Shionogi"], sector: "health-care" },
  { symbol: "4506.T", market: "JP", name: "住友ファーマ", aliases: ["Sumitomo Pharma", "大日本住友製薬"], sector: "health-care" },
  { symbol: "4527.T", market: "JP", name: "ロート製薬", aliases: ["Rohto", "ロート"], sector: "health-care" },
  { symbol: "4536.T", market: "JP", name: "参天製薬", aliases: ["Santen Pharmaceutical", "参天"], sector: "health-care" },
  { symbol: "4528.T", market: "JP", name: "小野薬品工業", aliases: ["Ono Pharmaceutical", "小野薬品"], sector: "health-care" },
  { symbol: "4530.T", market: "JP", name: "久光製薬", aliases: ["Hisamitsu Pharmaceutical", "久光"], sector: "health-care" },
  { symbol: "4704.T", market: "JP", name: "トレンドマイクロ", aliases: ["Trend Micro"], sector: "information-technology" },

  // ===== Financials / 金融 =====
  { symbol: "JPM", market: "US", name: "JPMorgan Chase", sector: "financials" },
  { symbol: "BAC", market: "US", name: "Bank of America", sector: "financials" },
  { symbol: "WFC", market: "US", name: "Wells Fargo", sector: "financials" },
  { symbol: "GS", market: "US", name: "Goldman Sachs", sector: "financials" },
  { symbol: "MS", market: "US", name: "Morgan Stanley", sector: "financials" },
  { symbol: "C", market: "US", name: "Citigroup", sector: "financials" },
  { symbol: "BLK", market: "US", name: "BlackRock", sector: "financials" },
  { symbol: "AXP", market: "US", name: "American Express", sector: "financials" },
  { symbol: "BX", market: "US", name: "Blackstone", sector: "financials" },
  { symbol: "SCHW", market: "US", name: "Charles Schwab", sector: "financials" },
  { symbol: "V", market: "US", name: "Visa", sector: "financials" },
  { symbol: "MA", market: "US", name: "Mastercard", sector: "financials" },
  { symbol: "USB", market: "US", name: "U.S. Bancorp", sector: "financials" },
  { symbol: "PNC", market: "US", name: "PNC Financial Services", sector: "financials" },
  { symbol: "PGR", market: "US", name: "Progressive", sector: "financials" },
  { symbol: "MMC", market: "US", name: "Marsh & McLennan", sector: "financials" },
  { symbol: "CB", market: "US", name: "Chubb", sector: "financials" },
  { symbol: "AON", market: "US", name: "Aon", sector: "financials" },
  { symbol: "ICE", market: "US", name: "Intercontinental Exchange", sector: "financials" },
  { symbol: "CME", market: "US", name: "CME Group", sector: "financials" },
  { symbol: "COIN", market: "US", name: "Coinbase Global", sector: "financials" },
  { symbol: "PYPL", market: "US", name: "PayPal Holdings", sector: "financials" },
  { symbol: "SQ", market: "US", name: "Block", aliases: ["Square"], sector: "financials" },
  { symbol: "HOOD", market: "US", name: "Robinhood Markets", sector: "financials" },
  { symbol: "SOFI", market: "US", name: "SoFi Technologies", sector: "financials" },
  { symbol: "NU", market: "US", name: "Nu Holdings", sector: "financials" },
  { symbol: "IBKR", market: "US", name: "Interactive Brokers", sector: "financials" },
  { symbol: "COF", market: "US", name: "Capital One Financial", sector: "financials" },
  { symbol: "STT", market: "US", name: "State Street", sector: "financials" },
  { symbol: "AFL", market: "US", name: "Aflac", sector: "financials" },
  { symbol: "AIG", market: "US", name: "American International Group", sector: "financials" },
  { symbol: "HIG", market: "US", name: "Hartford Financial Services", sector: "financials" },
  { symbol: "TROW", market: "US", name: "T. Rowe Price", sector: "financials" },

  { symbol: "8306.T", market: "JP", name: "三菱UFJフィナンシャル・グループ", aliases: ["三菱UFJ", "MUFG", "Mitsubishi UFJ"], sector: "financials" },
  { symbol: "8316.T", market: "JP", name: "三井住友フィナンシャルグループ", aliases: ["三井住友", "SMFG", "Sumitomo Mitsui"], sector: "financials" },
  { symbol: "8411.T", market: "JP", name: "みずほフィナンシャルグループ", aliases: ["みずほ", "Mizuho"], sector: "financials" },
  { symbol: "8766.T", market: "JP", name: "東京海上ホールディングス", aliases: ["東京海上", "Tokio Marine"], sector: "financials" },
  { symbol: "8725.T", market: "JP", name: "MS&ADインシュアランスグループホールディングス", aliases: ["MS&AD"], sector: "financials" },
  { symbol: "8630.T", market: "JP", name: "SOMPOホールディングス", aliases: ["Sompo", "ソンポ"], sector: "financials" },
  { symbol: "8591.T", market: "JP", name: "オリックス", aliases: ["Orix"], sector: "financials" },
  { symbol: "8604.T", market: "JP", name: "野村ホールディングス", aliases: ["Nomura", "野村"], sector: "financials" },
  { symbol: "8601.T", market: "JP", name: "大和証券グループ本社", aliases: ["Daiwa", "大和証券"], sector: "financials" },
  { symbol: "8331.T", market: "JP", name: "千葉銀行", aliases: ["Chiba Bank"], sector: "financials" },
  { symbol: "8473.T", market: "JP", name: "SBIホールディングス", aliases: ["SBI"], sector: "financials" },
  { symbol: "8697.T", market: "JP", name: "日本取引所グループ", aliases: ["JPX"], sector: "financials" },
  { symbol: "8354.T", market: "JP", name: "ふくおかフィナンシャルグループ", aliases: ["Fukuoka"], sector: "financials" },
  { symbol: "8308.T", market: "JP", name: "りそなホールディングス", aliases: ["Resona", "りそな銀行"], sector: "financials" },
  { symbol: "8309.T", market: "JP", name: "三井住友トラスト・ホールディングス", aliases: ["Sumitomo Mitsui Trust", "SMTH"], sector: "financials" },
  { symbol: "8332.T", market: "JP", name: "横浜銀行", aliases: ["Bank of Yokohama", "横浜"], sector: "financials" },
  { symbol: "7186.T", market: "JP", name: "コンコルディア・フィナンシャルグループ", aliases: ["Concordia FG"], sector: "financials" },

  // ===== Industrials / 資本財・サービス =====
  { symbol: "BA", market: "US", name: "Boeing", sector: "industrials" },
  { symbol: "CAT", market: "US", name: "Caterpillar", sector: "industrials" },
  { symbol: "HON", market: "US", name: "Honeywell International", sector: "industrials" },
  { symbol: "UPS", market: "US", name: "United Parcel Service", sector: "industrials" },
  { symbol: "GE", market: "US", name: "General Electric", sector: "industrials" },
  { symbol: "RTX", market: "US", name: "RTX (Raytheon)", sector: "industrials" },
  { symbol: "LMT", market: "US", name: "Lockheed Martin", sector: "industrials" },
  { symbol: "UNP", market: "US", name: "Union Pacific", sector: "industrials" },
  { symbol: "DE", market: "US", name: "Deere & Company", sector: "industrials" },
  { symbol: "MMM", market: "US", name: "3M", sector: "industrials" },
  { symbol: "ETN", market: "US", name: "Eaton", sector: "industrials" },
  { symbol: "ITW", market: "US", name: "Illinois Tool Works", sector: "industrials" },
  { symbol: "EMR", market: "US", name: "Emerson Electric", sector: "industrials" },
  { symbol: "NSC", market: "US", name: "Norfolk Southern", sector: "industrials" },
  { symbol: "CSX", market: "US", name: "CSX", sector: "industrials" },
  { symbol: "GD", market: "US", name: "General Dynamics", sector: "industrials" },
  { symbol: "FDX", market: "US", name: "FedEx", sector: "industrials" },
  { symbol: "NOC", market: "US", name: "Northrop Grumman", sector: "industrials" },
  { symbol: "WM", market: "US", name: "Waste Management", sector: "industrials" },
  { symbol: "ADP", market: "US", name: "Automatic Data Processing", sector: "industrials" },
  { symbol: "PH", market: "US", name: "Parker-Hannifin", sector: "industrials" },
  { symbol: "TT", market: "US", name: "Trane Technologies", sector: "industrials" },
  { symbol: "UBER", market: "US", name: "Uber Technologies", sector: "industrials" },
  { symbol: "GEV", market: "US", name: "GE Vernova", sector: "industrials" },
  { symbol: "PWR", market: "US", name: "Quanta Services", sector: "industrials" },
  { symbol: "TDG", market: "US", name: "TransDigm Group", sector: "industrials" },
  { symbol: "LDOS", market: "US", name: "Leidos Holdings", sector: "industrials" },
  { symbol: "BAH", market: "US", name: "Booz Allen Hamilton", sector: "industrials" },
  { symbol: "ROP", market: "US", name: "Roper Technologies", sector: "industrials" },
  { symbol: "HEI", market: "US", name: "Heico", sector: "industrials" },
  { symbol: "BLDR", market: "US", name: "Builders FirstSource", sector: "industrials" },
  { symbol: "SAIC", market: "US", name: "Science Applications International", sector: "industrials" },
  { symbol: "XYL", market: "US", name: "Xylem", sector: "industrials" },

  { symbol: "6301.T", market: "JP", name: "小松製作所", aliases: ["Komatsu", "コマツ"], sector: "industrials" },
  { symbol: "6954.T", market: "JP", name: "ファナック", aliases: ["Fanuc"], sector: "industrials" },
  { symbol: "7011.T", market: "JP", name: "三菱重工業", aliases: ["三菱重工", "MHI"], sector: "industrials" },
  { symbol: "9020.T", market: "JP", name: "東日本旅客鉄道", aliases: ["JR東日本", "JR East"], sector: "industrials" },
  { symbol: "9022.T", market: "JP", name: "東海旅客鉄道", aliases: ["JR東海", "JR Central"], sector: "industrials" },
  { symbol: "9021.T", market: "JP", name: "西日本旅客鉄道", aliases: ["JR西日本", "JR West"], sector: "industrials" },
  { symbol: "9202.T", market: "JP", name: "ANAホールディングス", aliases: ["ANA", "全日空"], sector: "industrials" },
  { symbol: "9201.T", market: "JP", name: "日本航空", aliases: ["JAL"], sector: "industrials" },
  { symbol: "9101.T", market: "JP", name: "日本郵船", aliases: ["NYK", "郵船"], sector: "industrials" },
  { symbol: "9104.T", market: "JP", name: "商船三井", aliases: ["MOL"], sector: "industrials" },
  { symbol: "9107.T", market: "JP", name: "川崎汽船", aliases: ["K Line"], sector: "industrials" },
  { symbol: "6367.T", market: "JP", name: "ダイキン工業", aliases: ["Daikin", "ダイキン"], sector: "industrials" },
  { symbol: "6273.T", market: "JP", name: "SMC", sector: "industrials" },
  { symbol: "6326.T", market: "JP", name: "クボタ", aliases: ["Kubota"], sector: "industrials" },
  { symbol: "6471.T", market: "JP", name: "日本精工", aliases: ["NSK"], sector: "industrials" },
  { symbol: "6503.T", market: "JP", name: "三菱電機", aliases: ["三菱電", "Mitsubishi Electric"], sector: "industrials" },
  { symbol: "6501.T", market: "JP", name: "日立製作所", aliases: ["Hitachi", "日立"], sector: "industrials" },
  { symbol: "6502.T", market: "JP", name: "東芝", aliases: ["Toshiba"], sector: "industrials" },
  { symbol: "7012.T", market: "JP", name: "川崎重工業", aliases: ["川崎重工", "Kawasaki Heavy"], sector: "industrials" },
  { symbol: "7013.T", market: "JP", name: "IHI", sector: "industrials" },
  { symbol: "8001.T", market: "JP", name: "伊藤忠商事", aliases: ["Itochu"], sector: "industrials" },
  { symbol: "8002.T", market: "JP", name: "丸紅", aliases: ["Marubeni"], sector: "industrials" },
  { symbol: "8031.T", market: "JP", name: "三井物産", aliases: ["Mitsui & Co"], sector: "industrials" },
  { symbol: "8053.T", market: "JP", name: "住友商事", aliases: ["Sumitomo Corporation"], sector: "industrials" },
  { symbol: "8058.T", market: "JP", name: "三菱商事", aliases: ["Mitsubishi Corporation"], sector: "industrials" },
  { symbol: "6594.T", market: "JP", name: "ニデック", aliases: ["Nidec", "日本電産"], sector: "industrials" },
  { symbol: "6506.T", market: "JP", name: "安川電機", aliases: ["Yaskawa Electric", "安川"], sector: "industrials" },
  { symbol: "6841.T", market: "JP", name: "横河電機", aliases: ["Yokogawa Electric", "横河"], sector: "industrials" },
  { symbol: "7731.T", market: "JP", name: "ニコン", aliases: ["Nikon"], sector: "industrials" },
  { symbol: "6305.T", market: "JP", name: "日立建機", aliases: ["Hitachi Construction Machinery", "日立建機"], sector: "industrials" },
  { symbol: "7004.T", market: "JP", name: "日立造船", aliases: ["Hitachi Zosen"], sector: "industrials" },
  { symbol: "6472.T", market: "JP", name: "NTN", sector: "industrials" },
  { symbol: "9064.T", market: "JP", name: "ヤマトホールディングス", aliases: ["Yamato Holdings", "クロネコヤマト"], sector: "industrials" },
  { symbol: "9062.T", market: "JP", name: "日本通運", aliases: ["Nippon Express", "日通"], sector: "industrials" },

  // ===== Materials / 素材 =====
  { symbol: "LIN", market: "US", name: "Linde", sector: "materials" },
  { symbol: "SHW", market: "US", name: "Sherwin-Williams", sector: "materials" },
  { symbol: "ECL", market: "US", name: "Ecolab", sector: "materials" },
  { symbol: "APD", market: "US", name: "Air Products and Chemicals", sector: "materials" },
  { symbol: "FCX", market: "US", name: "Freeport-McMoRan", sector: "materials" },
  { symbol: "NEM", market: "US", name: "Newmont", sector: "materials" },
  { symbol: "DD", market: "US", name: "DuPont de Nemours", sector: "materials" },
  { symbol: "NUE", market: "US", name: "Nucor", sector: "materials" },
  { symbol: "IFF", market: "US", name: "International Flavors & Fragrances", sector: "materials" },
  { symbol: "DOW", market: "US", name: "Dow", sector: "materials" },
  { symbol: "PPG", market: "US", name: "PPG Industries", sector: "materials" },
  { symbol: "MLM", market: "US", name: "Martin Marietta Materials", sector: "materials" },
  { symbol: "VMC", market: "US", name: "Vulcan Materials", sector: "materials" },
  { symbol: "AA", market: "US", name: "Alcoa", sector: "materials" },
  { symbol: "STLD", market: "US", name: "Steel Dynamics", sector: "materials" },
  { symbol: "RS", market: "US", name: "Reliance Steel & Aluminum", sector: "materials" },
  { symbol: "CE", market: "US", name: "Celanese", sector: "materials" },
  { symbol: "EMN", market: "US", name: "Eastman Chemical", sector: "materials" },
  { symbol: "RPM", market: "US", name: "RPM International", sector: "materials" },
  { symbol: "SW", market: "US", name: "Smurfit WestRock", aliases: ["スマーフィット・ウエストロック"], sector: "materials" },

  { symbol: "4063.T", market: "JP", name: "信越化学工業", aliases: ["信越化学", "Shin-Etsu Chemical"], sector: "materials" },
  { symbol: "5401.T", market: "JP", name: "日本製鉄", aliases: ["Nippon Steel", "新日鉄"], sector: "materials" },
  { symbol: "3402.T", market: "JP", name: "東レ", aliases: ["Toray"], sector: "materials" },
  { symbol: "4188.T", market: "JP", name: "三菱ケミカルグループ", aliases: ["Mitsubishi Chemical", "三菱ケミカル"], sector: "materials" },
  { symbol: "4005.T", market: "JP", name: "住友化学", aliases: ["Sumitomo Chemical"], sector: "materials" },
  { symbol: "5713.T", market: "JP", name: "住友金属鉱山", aliases: ["Sumitomo Metal Mining"], sector: "materials" },
  { symbol: "3407.T", market: "JP", name: "旭化成", aliases: ["Asahi Kasei"], sector: "materials" },
  { symbol: "4901.T", market: "JP", name: "富士フイルムホールディングス", aliases: ["Fujifilm", "富士フイルム"], sector: "materials" },
  { symbol: "5201.T", market: "JP", name: "AGC", aliases: ["旭硝子"], sector: "materials" },
  { symbol: "5411.T", market: "JP", name: "JFEホールディングス", aliases: ["JFE"], sector: "materials" },
  { symbol: "5802.T", market: "JP", name: "住友電気工業", aliases: ["Sumitomo Electric"], sector: "industrials" },
  { symbol: "4204.T", market: "JP", name: "積水化学工業", aliases: ["Sekisui Chemical", "積水化学"], sector: "materials" },
  { symbol: "4042.T", market: "JP", name: "東ソー", aliases: ["Tosoh"], sector: "materials" },
  { symbol: "5333.T", market: "JP", name: "日本ガイシ", aliases: ["NGK Insulators", "NGK"], sector: "materials" },
  { symbol: "4021.T", market: "JP", name: "日産化学", aliases: ["Nissan Chemical"], sector: "materials" },
  { symbol: "5631.T", market: "JP", name: "日本製鋼所", aliases: ["Japan Steel Works", "JSW"], sector: "materials" },
  { symbol: "4183.T", market: "JP", name: "三井化学", aliases: ["Mitsui Chemicals"], sector: "materials" },

  // ===== Energy / エネルギー =====
  { symbol: "XOM", market: "US", name: "ExxonMobil", sector: "energy" },
  { symbol: "CVX", market: "US", name: "Chevron", sector: "energy" },
  { symbol: "COP", market: "US", name: "ConocoPhillips", sector: "energy" },
  { symbol: "EOG", market: "US", name: "EOG Resources", sector: "energy" },
  { symbol: "SLB", market: "US", name: "Schlumberger", sector: "energy" },
  { symbol: "MPC", market: "US", name: "Marathon Petroleum", sector: "energy" },
  { symbol: "PSX", market: "US", name: "Phillips 66", sector: "energy" },
  { symbol: "OXY", market: "US", name: "Occidental Petroleum", sector: "energy" },
  { symbol: "VLO", market: "US", name: "Valero Energy", sector: "energy" },
  { symbol: "HAL", market: "US", name: "Halliburton", sector: "energy" },
  { symbol: "KMI", market: "US", name: "Kinder Morgan", sector: "energy" },
  { symbol: "WMB", market: "US", name: "Williams Companies", sector: "energy" },
  { symbol: "BKR", market: "US", name: "Baker Hughes", sector: "energy" },
  { symbol: "DVN", market: "US", name: "Devon Energy", sector: "energy" },
  { symbol: "FANG", market: "US", name: "Diamondback Energy", sector: "energy" },
  { symbol: "APA", market: "US", name: "APA Corporation", sector: "energy" },
  { symbol: "OKE", market: "US", name: "ONEOK", sector: "energy" },
  { symbol: "TRGP", market: "US", name: "Targa Resources", sector: "energy" },
  { symbol: "BP", market: "US", name: "BP", sector: "energy" },
  { symbol: "SHEL", market: "US", name: "Shell", sector: "energy" },
  { symbol: "TTE", market: "US", name: "TotalEnergies", sector: "energy" },
  // ウラン・核燃料
  { symbol: "CCJ", market: "US", name: "Cameco", aliases: ["カメコ", "ウラン"], sector: "energy" },
  { symbol: "UEC", market: "US", name: "Uranium Energy Corp", aliases: ["ウラン", "UEC"], sector: "energy" },
  { symbol: "LEU", market: "US", name: "Centrus Energy", aliases: ["セントラス", "ウラン濃縮"], sector: "energy" },
  { symbol: "UUUU", market: "US", name: "Energy Fuels", aliases: ["エナジー・フュエルズ"], sector: "energy" },

  { symbol: "5020.T", market: "JP", name: "ENEOSホールディングス", aliases: ["ENEOS", "エネオス"], sector: "energy" },
  { symbol: "1605.T", market: "JP", name: "INPEX", aliases: ["国際石油開発"], sector: "energy" },
  { symbol: "5019.T", market: "JP", name: "出光興産", aliases: ["Idemitsu", "出光"], sector: "energy" },
  { symbol: "1662.T", market: "JP", name: "石油資源開発", aliases: ["JAPEX"], sector: "energy" },
  { symbol: "5021.T", market: "JP", name: "コスモエネルギーホールディングス", aliases: ["Cosmo Energy", "コスモ石油"], sector: "energy" },

  // ===== Utilities / 公益事業 =====
  { symbol: "NEE", market: "US", name: "NextEra Energy", sector: "utilities" },
  { symbol: "DUK", market: "US", name: "Duke Energy", sector: "utilities" },
  { symbol: "SO", market: "US", name: "Southern Company", sector: "utilities" },
  { symbol: "AEP", market: "US", name: "American Electric Power", sector: "utilities" },
  { symbol: "EXC", market: "US", name: "Exelon", sector: "utilities" },
  { symbol: "D", market: "US", name: "Dominion Energy", sector: "utilities" },
  { symbol: "XEL", market: "US", name: "Xcel Energy", sector: "utilities" },
  { symbol: "SRE", market: "US", name: "Sempra", sector: "utilities" },
  { symbol: "PEG", market: "US", name: "Public Service Enterprise Group", sector: "utilities" },
  { symbol: "ED", market: "US", name: "Consolidated Edison", sector: "utilities" },
  { symbol: "WEC", market: "US", name: "WEC Energy Group", sector: "utilities" },
  { symbol: "ES", market: "US", name: "Eversource Energy", sector: "utilities" },
  { symbol: "PCG", market: "US", name: "PG&E", sector: "utilities" },
  { symbol: "ETR", market: "US", name: "Entergy", sector: "utilities" },
  { symbol: "CNP", market: "US", name: "CenterPoint Energy", sector: "utilities" },
  { symbol: "AEE", market: "US", name: "Ameren", sector: "utilities" },
  { symbol: "EVRG", market: "US", name: "Evergy", sector: "utilities" },
  { symbol: "NI", market: "US", name: "NiSource", sector: "utilities" },
  { symbol: "LNT", market: "US", name: "Alliant Energy", sector: "utilities" },
  // 原子力・次世代エネルギー
  { symbol: "CEG", market: "US", name: "Constellation Energy", aliases: ["コンステレーション", "原子力"], sector: "utilities" },
  { symbol: "VST", market: "US", name: "Vistra Corp", aliases: ["ビストラ", "原子力"], sector: "utilities" },
  { symbol: "OKLO", market: "US", name: "Oklo", aliases: ["オクロ", "小型原子炉", "次世代原子力"], sector: "utilities" },
  { symbol: "NNE", market: "US", name: "Nano Nuclear Energy", aliases: ["ナノ・ニュークリア", "小型原子炉"], sector: "utilities" },
  // 小型モジュール炉・核融合
  { symbol: "SMR", market: "US", name: "NuScale Power", aliases: ["ニュースケール", "小型モジュール炉", "SMR"], sector: "utilities" },
  { symbol: "BWXT", market: "US", name: "BWX Technologies", aliases: ["BWX", "原子力部品"], sector: "industrials" },

  { symbol: "9501.T", market: "JP", name: "東京電力ホールディングス", aliases: ["東電", "TEPCO"], sector: "utilities" },
  { symbol: "9503.T", market: "JP", name: "関西電力", aliases: ["Kanden", "関電"], sector: "utilities" },
  { symbol: "9502.T", market: "JP", name: "中部電力", aliases: ["Chuden"], sector: "utilities" },
  { symbol: "9531.T", market: "JP", name: "東京瓦斯", aliases: ["東京ガス", "Tokyo Gas"], sector: "utilities" },
  { symbol: "9532.T", market: "JP", name: "大阪瓦斯", aliases: ["大阪ガス", "Osaka Gas"], sector: "utilities" },
  { symbol: "9508.T", market: "JP", name: "九州電力", aliases: ["Kyushu Electric"], sector: "utilities" },
  { symbol: "9504.T", market: "JP", name: "中国電力", aliases: ["Chugoku Electric"], sector: "utilities" },
  { symbol: "9505.T", market: "JP", name: "北海道電力", aliases: ["Hokkaido Electric"], sector: "utilities" },
  { symbol: "9506.T", market: "JP", name: "東北電力", aliases: ["Tohoku Electric"], sector: "utilities" },
  { symbol: "9507.T", market: "JP", name: "北陸電力", aliases: ["Hokuriku Electric"], sector: "utilities" },
  { symbol: "9511.T", market: "JP", name: "沖縄電力", aliases: ["Okinawa Electric"], sector: "utilities" },
  { symbol: "9533.T", market: "JP", name: "東邦ガス", aliases: ["Toho Gas"], sector: "utilities" },

  // ===== Real Estate / 不動産 =====
  { symbol: "PLD", market: "US", name: "Prologis", sector: "real-estate" },
  { symbol: "AMT", market: "US", name: "American Tower", sector: "real-estate" },
  { symbol: "EQIX", market: "US", name: "Equinix", sector: "real-estate" },
  { symbol: "SPG", market: "US", name: "Simon Property Group", sector: "real-estate" },
  { symbol: "O", market: "US", name: "Realty Income", sector: "real-estate" },
  { symbol: "CCI", market: "US", name: "Crown Castle", sector: "real-estate" },
  { symbol: "DLR", market: "US", name: "Digital Realty Trust", sector: "real-estate" },
  { symbol: "PSA", market: "US", name: "Public Storage", sector: "real-estate" },
  { symbol: "AVB", market: "US", name: "AvalonBay Communities", sector: "real-estate" },
  { symbol: "EQR", market: "US", name: "Equity Residential", sector: "real-estate" },
  { symbol: "WELL", market: "US", name: "Welltower", sector: "real-estate" },
  { symbol: "ARE", market: "US", name: "Alexandria Real Estate Equities", sector: "real-estate" },
  { symbol: "EXR", market: "US", name: "Extra Space Storage", sector: "real-estate" },
  { symbol: "VICI", market: "US", name: "VICI Properties", sector: "real-estate" },
  { symbol: "INVH", market: "US", name: "Invitation Homes", sector: "real-estate" },
  { symbol: "VTR", market: "US", name: "Ventas", sector: "real-estate" },
  { symbol: "MAA", market: "US", name: "Mid-America Apartment Communities", sector: "real-estate" },
  { symbol: "CBRE", market: "US", name: "CBRE Group", sector: "real-estate" },
  { symbol: "DOC", market: "US", name: "Healthpeak Properties", sector: "real-estate" },
  { symbol: "ADC", market: "US", name: "Agree Realty", sector: "real-estate" },
  { symbol: "JLL", market: "US", name: "Jones Lang LaSalle", sector: "real-estate" },

  { symbol: "8801.T", market: "JP", name: "三井不動産", aliases: ["Mitsui Fudosan"], sector: "real-estate" },
  { symbol: "8802.T", market: "JP", name: "三菱地所", aliases: ["Mitsubishi Estate"], sector: "real-estate" },
  { symbol: "8830.T", market: "JP", name: "住友不動産", aliases: ["Sumitomo Realty"], sector: "real-estate" },
  { symbol: "3289.T", market: "JP", name: "東急不動産ホールディングス", aliases: ["Tokyu Fudosan"], sector: "real-estate" },
  { symbol: "8804.T", market: "JP", name: "東京建物", aliases: ["Tokyo Tatemono"], sector: "real-estate" },
  { symbol: "3231.T", market: "JP", name: "野村不動産ホールディングス", aliases: ["Nomura Real Estate"], sector: "real-estate" },
  { symbol: "3003.T", market: "JP", name: "ヒューリック", aliases: ["Hulic"], sector: "real-estate" },
  { symbol: "1878.T", market: "JP", name: "大東建託", aliases: ["Daito Trust Construction"], sector: "real-estate" },
  { symbol: "3283.T", market: "JP", name: "日本プロロジスリート投資法人", aliases: ["Japan Prologis REIT"], sector: "real-estate" },
  { symbol: "8951.T", market: "JP", name: "日本ビルファンド投資法人", aliases: ["Nippon Building Fund"], sector: "real-estate" },
  { symbol: "8952.T", market: "JP", name: "ジャパンリアルエステイト投資法人", aliases: ["Japan Real Estate Investment"], sector: "real-estate" },
  { symbol: "3492.T", market: "JP", name: "タカラレーベン不動産投資法人", aliases: ["Takara Leben REIT"], sector: "real-estate" },

  // ===== ETFs / 投資信託 (上場投信) =====
  // --- Broad market (米国/グローバル指数連動) ---
  { symbol: "SPY", market: "US", name: "SPDR S&P 500 ETF", aliases: ["S&P500"], sector: "information-technology", type: "etf", etfCategory: "broad" },
  { symbol: "VOO", market: "US", name: "バンガード S&P 500 ETF", aliases: ["Vanguard S&P500"], sector: "information-technology", type: "etf", etfCategory: "broad" },
  { symbol: "IVV", market: "US", name: "iShares Core S&P 500 ETF", sector: "information-technology", type: "etf", etfCategory: "broad" },
  { symbol: "VTI", market: "US", name: "バンガード トータル・ストック・マーケット ETF", aliases: ["Vanguard Total Stock"], sector: "information-technology", type: "etf", etfCategory: "broad" },
  { symbol: "QQQ", market: "US", name: "インベスコ QQQ (NASDAQ-100)", aliases: ["NASDAQ100", "QQQ"], sector: "information-technology", type: "etf", etfCategory: "broad" },
  { symbol: "DIA", market: "US", name: "SPDR ダウ平均 ETF", aliases: ["Dow ETF"], sector: "industrials", type: "etf", etfCategory: "broad" },
  { symbol: "IWM", market: "US", name: "iShares ラッセル2000 ETF", aliases: ["Russell 2000"], sector: "industrials", type: "etf", etfCategory: "broad" },
  { symbol: "VT", market: "US", name: "バンガード トータル・ワールド・ストック ETF", sector: "information-technology", type: "etf", etfCategory: "broad" },
  { symbol: "VXUS", market: "US", name: "バンガード トータル・インターナショナル・ストック ETF", sector: "information-technology", type: "etf", etfCategory: "international" },
  { symbol: "VEA", market: "US", name: "バンガード FTSE 先進国市場 ETF", sector: "information-technology", type: "etf", etfCategory: "international" },
  { symbol: "VWO", market: "US", name: "バンガード FTSE エマージング・マーケッツ ETF", sector: "information-technology", type: "etf", etfCategory: "international" },
  { symbol: "EFA", market: "US", name: "iShares MSCI EAFE ETF", sector: "information-technology", type: "etf", etfCategory: "international" },
  { symbol: "EEM", market: "US", name: "iShares MSCI エマージング・マーケッツ ETF", sector: "information-technology", type: "etf", etfCategory: "international" },

  // --- Sector ETFs (SPDR) ---
  { symbol: "XLK", market: "US", name: "テクノロジー・セレクト・セクター SPDR", sector: "information-technology", type: "etf", etfCategory: "sector" },
  { symbol: "XLF", market: "US", name: "金融セレクト・セクター SPDR", sector: "financials", type: "etf", etfCategory: "sector" },
  { symbol: "XLE", market: "US", name: "エネルギー・セレクト・セクター SPDR", sector: "energy", type: "etf", etfCategory: "sector" },
  { symbol: "XLV", market: "US", name: "ヘルスケア・セレクト・セクター SPDR", sector: "health-care", type: "etf", etfCategory: "sector" },
  { symbol: "XLY", market: "US", name: "一般消費財セレクト・セクター SPDR", sector: "consumer-discretionary", type: "etf", etfCategory: "sector" },
  { symbol: "XLP", market: "US", name: "生活必需品セレクト・セクター SPDR", sector: "consumer-staples", type: "etf", etfCategory: "sector" },
  { symbol: "XLI", market: "US", name: "資本財セレクト・セクター SPDR", sector: "industrials", type: "etf", etfCategory: "sector" },
  { symbol: "XLU", market: "US", name: "公益事業セレクト・セクター SPDR", sector: "utilities", type: "etf", etfCategory: "sector" },
  { symbol: "XLB", market: "US", name: "素材セレクト・セクター SPDR", sector: "materials", type: "etf", etfCategory: "sector" },
  { symbol: "XLRE", market: "US", name: "不動産セレクト・セクター SPDR", sector: "real-estate", type: "etf", etfCategory: "sector" },
  { symbol: "XLC", market: "US", name: "コミュニケーションサービス・セレクト・セクター SPDR", sector: "communication-services", type: "etf", etfCategory: "sector" },
  { symbol: "SMH", market: "US", name: "VanEck 半導体株 ETF", sector: "information-technology", type: "etf", etfCategory: "sector" },
  { symbol: "SOXX", market: "US", name: "iShares 半導体株 ETF", sector: "information-technology", type: "etf", etfCategory: "sector" },

  // --- Thematic / Growth ---
  { symbol: "ARKK", market: "US", name: "ARK イノベーション ETF", aliases: ["ARK Innovation"], sector: "information-technology", type: "etf", etfCategory: "thematic" },
  { symbol: "ICLN", market: "US", name: "iShares グローバル・クリーンエネルギー ETF", sector: "utilities", type: "etf", etfCategory: "thematic" },
  { symbol: "TAN", market: "US", name: "インベスコ ソーラー ETF", sector: "energy", type: "etf", etfCategory: "thematic" },
  { symbol: "LIT", market: "US", name: "グローバル X リチウム & 電池技術 ETF", sector: "materials", type: "etf", etfCategory: "thematic" },
  { symbol: "BOTZ", market: "US", name: "グローバル X ロボティクス & AI ETF", sector: "information-technology", type: "etf", etfCategory: "thematic" },

  // --- Dividend / Income ---
  { symbol: "VYM", market: "US", name: "バンガード 高配当株 ETF", sector: "financials", type: "etf", etfCategory: "dividend" },
  { symbol: "SCHD", market: "US", name: "シュワブ 米国配当株 ETF", sector: "financials", type: "etf", etfCategory: "dividend" },
  { symbol: "VIG", market: "US", name: "バンガード 配当成長株 ETF", sector: "financials", type: "etf", etfCategory: "dividend" },
  { symbol: "HDV", market: "US", name: "iShares コア 米国高配当株 ETF", sector: "financials", type: "etf", etfCategory: "dividend" },

  // --- Bond ---
  { symbol: "AGG", market: "US", name: "iShares コア 米国総合債券 ETF", sector: "financials", type: "etf", etfCategory: "bond" },
  { symbol: "BND", market: "US", name: "バンガード 米国総合債券 ETF", sector: "financials", type: "etf", etfCategory: "bond" },
  { symbol: "TLT", market: "US", name: "iShares 米国20年超 国債 ETF", sector: "financials", type: "etf", etfCategory: "bond" },
  { symbol: "LQD", market: "US", name: "iShares iBoxx 米国投資適格社債 ETF", sector: "financials", type: "etf", etfCategory: "bond" },
  { symbol: "HYG", market: "US", name: "iShares iBoxx 米国ハイイールド社債 ETF", sector: "financials", type: "etf", etfCategory: "bond" },

  // --- Commodity ---
  { symbol: "GLD", market: "US", name: "SPDR ゴールド・トラスト", aliases: ["Gold ETF"], sector: "materials", type: "etf", etfCategory: "commodity" },
  { symbol: "IAU", market: "US", name: "iShares ゴールド・トラスト", sector: "materials", type: "etf", etfCategory: "commodity" },
  { symbol: "SLV", market: "US", name: "iShares シルバー・トラスト", sector: "materials", type: "etf", etfCategory: "commodity" },
  { symbol: "USO", market: "US", name: "米国オイル・ファンド", sector: "energy", type: "etf", etfCategory: "commodity" },

  // --- Leveraged ---
  { symbol: "TQQQ", market: "US", name: "ProShares ウルトラプロ QQQ (3倍)", sector: "information-technology", type: "etf", etfCategory: "leveraged" },
  { symbol: "SOXL", market: "US", name: "Direxion 半導体株 3倍ブル", sector: "information-technology", type: "etf", etfCategory: "leveraged" },
  { symbol: "SQQQ", market: "US", name: "ProShares ウルトラプロ ショート QQQ (3倍)", sector: "information-technology", type: "etf", etfCategory: "leveraged" },

  // --- 日本ETF ---
  { symbol: "1306.T", market: "JP", name: "NEXT FUNDS TOPIX 連動型上場投信", aliases: ["TOPIX ETF"], sector: "information-technology", type: "etf", etfCategory: "broad" },
  { symbol: "1321.T", market: "JP", name: "NEXT FUNDS 日経225連動型上場投信", aliases: ["日経225 ETF", "Nikkei225"], sector: "information-technology", type: "etf", etfCategory: "broad" },
  { symbol: "1320.T", market: "JP", name: "ダイワ上場投信-日経225", sector: "information-technology", type: "etf", etfCategory: "broad" },
  { symbol: "1330.T", market: "JP", name: "上場インデックスファンド 225", sector: "information-technology", type: "etf", etfCategory: "broad" },
  { symbol: "2558.T", market: "JP", name: "MAXIS 米国株式 (S&P500) 上場投信", aliases: ["MAXIS米国"], sector: "information-technology", type: "etf", etfCategory: "international" },
  { symbol: "2559.T", market: "JP", name: "MAXIS 全世界株式 (オール・カントリー) 上場投信", aliases: ["オルカン"], sector: "information-technology", type: "etf", etfCategory: "international" },
  { symbol: "1655.T", market: "JP", name: "iシェアーズ S&P 500 米国株 ETF (東証)", sector: "information-technology", type: "etf", etfCategory: "international" },
  { symbol: "2563.T", market: "JP", name: "iシェアーズ S&P 500 米国株 ETF (為替ヘッジあり)", sector: "information-technology", type: "etf", etfCategory: "international" },
  { symbol: "1545.T", market: "JP", name: "NEXT FUNDS NASDAQ-100 連動型上場投信", aliases: ["NASDAQ100 (JP)"], sector: "information-technology", type: "etf", etfCategory: "international" },
  { symbol: "1489.T", market: "JP", name: "NEXT FUNDS 日経平均高配当株50指数 連動型上場投信", aliases: ["日経高配当50"], sector: "financials", type: "etf", etfCategory: "dividend" },
  { symbol: "1577.T", market: "JP", name: "NEXT FUNDS 野村日本株高配当70 連動型上場投信", sector: "financials", type: "etf", etfCategory: "dividend" },
  { symbol: "1326.T", market: "JP", name: "SPDR ゴールド・シェア (東証)", sector: "materials", type: "etf", etfCategory: "commodity" },
];

const SYMBOL_INDEX = new Map(STOCKS_CATALOG.map((s) => [s.symbol, s]));

export function findStockBySymbol(symbol: string): CatalogStock | undefined {
  return SYMBOL_INDEX.get(symbol);
}

export function getStocksBySector(
  sector: GicsSectorId,
  includeEtf = false,
): CatalogStock[] {
  return STOCKS_CATALOG.filter(
    (s) => s.sector === sector && (includeEtf || s.type !== "etf"),
  );
}

export function getEtfs(): CatalogStock[] {
  return STOCKS_CATALOG.filter((s) => s.type === "etf");
}

export function getAllStocks(includeEtf = false): CatalogStock[] {
  return includeEtf
    ? STOCKS_CATALOG
    : STOCKS_CATALOG.filter((s) => s.type !== "etf");
}

export function getJpStocks(): CatalogStock[] {
  return STOCKS_CATALOG.filter((s) => s.market === "JP");
}

/**
 * Returns all stocks for a sector, including supplement stocks from
 * US_STOCKS_SUPPLEMENT that have sector data in US_SECTOR_MAP.
 * Deduplicates by symbol (curated catalog takes precedence).
 */
export function getStocksBySectorAll(
  sector: GicsSectorId,
): { symbol: string; name: string; market: "JP" | "US" }[] {
  // Start with curated catalog (non-ETF)
  const curated = STOCKS_CATALOG.filter(
    (s) => s.sector === sector && s.type !== "etf",
  ).map((s) => ({ symbol: s.symbol, name: s.name, market: s.market as "JP" | "US" }));

  const seen = new Set(curated.map((s) => s.symbol));

  // Add US supplement stocks that match this sector
  for (const [sym, name] of US_STOCKS_SUPPLEMENT) {
    if (seen.has(sym)) continue;
    if ((US_SECTOR_MAP[sym] as GicsSectorId) !== sector) continue;
    if (name.includes("廃止") || name.includes("delisted")) continue;
    seen.add(sym);
    curated.push({ symbol: sym, name, market: "US" });
  }

  // Add JP supplement stocks (TSE) that match this sector
  const jpSymSeen = new Set<string>();
  for (const [sym, name] of TSE_NAMES) {
    if (seen.has(sym)) continue; // already in curated catalog or added above
    if (name.includes("廃止") || name.includes("重複") || name === "?" || name.startsWith("?")) continue;
    if ((JP_SECTOR_MAP[sym] as GicsSectorId) !== sector) continue;
    if (jpSymSeen.has(sym)) continue; // dedup: first occurrence per symbol wins
    jpSymSeen.add(sym);
    seen.add(sym);
    curated.push({ symbol: sym, name, market: "JP" });
  }

  return curated;
}
