/**
 * Supplemental US stock list for the browse page.
 * Format: [symbol, company_name]
 * Covers S&P 500, major NASDAQ, and other well-known US-listed stocks.
 * Already-curated symbols (in STOCKS_CATALOG) are automatically deduped at runtime.
 */
export const US_STOCKS_SUPPLEMENT: [string, string][] = [

  // ── 宇宙・新規上場 ────────────────────────────────────────────────
  ["SPCX","Space Exploration Technologies (SpaceX)"],

  // ── S&P 500 / 大型株 ──────────────────────────────────────────────
  // Technology
  ["MSFT","Microsoft"],["AAPL","Apple"],["NVDA","NVIDIA"],["AVGO","Broadcom"],
  ["ORCL","Oracle"],["CRM","Salesforce"],["CSCO","Cisco Systems"],["ACN","Accenture"],
  ["IBM","IBM"],["TXN","Texas Instruments"],["QCOM","Qualcomm"],["AMAT","Applied Materials"],
  ["INTC","Intel"],["MU","Micron Technology"],["AMD","Advanced Micro Devices"],
  ["NOW","ServiceNow"],["ADBE","Adobe"],["INTU","Intuit"],["KLAC","KLA Corporation"],
  ["LRCX","Lam Research"],["SNPS","Synopsys"],["CDNS","Cadence Design Systems"],
  ["FTNT","Fortinet"],["PANW","Palo Alto Networks"],["ZS","Zscaler"],
  ["CRWD","CrowdStrike"],["DDOG","Datadog"],["NET","Cloudflare"],["TEAM","Atlassian"],
  ["MRVL","Marvell Technology"],["FICO","Fair Isaac"],["TEL","TE Connectivity"],
  ["TER","Teradyne"],["GLW","Corning"],["SWKS","Skyworks Solutions"],
  ["KEYS","Keysight Technologies"],["WDC","Western Digital"],["STX","Seagate Technology"],
  ["NTAP","NetApp"],["PSTG","Pure Storage"],["JNPR","Juniper Networks"],
  ["AKAM","Akamai Technologies"],["CDW","CDW Corporation"],["GDDY","GoDaddy"],
  ["EPAM","EPAM Systems"],["CTSH","Cognizant"],["WIT","Wipro"],["INFY","Infosys"],
  ["SHOP","Shopify"],["SQ","Block"],["PYPL","PayPal"],["ADYEN","Adyen"],
  ["NXPI","NXP Semiconductors"],["ON","ON Semiconductor"],["ENPH","Enphase Energy"],
  ["AEHR","Aehr Test Systems"],["MPWR","Monolithic Power Systems"],
  ["WOLF","Wolfspeed"],["CREE","Cree (Wolfspeed)"],
  ["QRVO","Qorvo"],["IPGP","IPG Photonics"],["COHR","Coherent"],
  ["II","Inphi (廃止)"],["MCHP","Microchip Technology"],["SLAB","Silicon Laboratories"],
  ["MTSI","MACOM Technology"],["ALGM","Allegro MicroSystems"],
  ["SITM","SiTime"],["FORM","FormFactor"],["AMBA","Ambarella"],
  ["POWI","Power Integrations"],["DIOD","Diodes"],["SMTC","Semtech"],

  // Software / Cloud
  ["CRM","Salesforce"],["WDAY","Workday"],["VEEV","Veeva Systems"],["ANGI","Angi"],
  ["ZI","ZoomInfo"],["MDB","MongoDB"],["DDOG","Datadog"],["ESTC","Elastic"],
  ["GTLB","GitLab"],["HUBS","HubSpot"],["DOCN","DigitalOcean"],["TWLO","Twilio"],
  ["U","Unity Software"],["RBLX","Roblox"],["APP","Applovin"],["TTEC","TTEC Holdings"],
  ["SPT","Sprout Social"],["ALRM","Alarm.com"],["PRFT","Perficient"],
  ["CWAN","Clearwater Analytics"],["PCOR","Procore Technologies"],
  ["S","SentinelOne"],["CYBR","CyberArk Software"],["VRNS","Varonis Systems"],
  ["TENB","Tenable Holdings"],["RPD","Rapid7"],["QLYS","Qualys"],
  ["SAIL","SailPoint (廃止)"],["OSPN","OneSpan"],["PING","Ping Identity (廃止)"],
  ["TOST","Toast"],["BIGC","BigCommerce"],["WIX","Wix.com"],
  ["MNDY","Monday.com"],["BILL","Bill.com"],["SMAR","Smartsheet"],
  ["ASAN","Asana"],["BASE","Base (廃止)"],["WORK","Slack (廃止)"],
  ["ZM","Zoom Video"],["RNG","RingCentral"],["AVLR","Avalara (廃止)"],
  ["PAYA","Paya Holdings (廃止)"],["FOUR","Shift4 Payments"],
  ["PAX","PAX Global (廃止)"],["EVTC","EveriTec"],
  ["COUP","Coupa Software (廃止)"],["COUPA","Coupa Software"],
  ["SPSC","SPS Commerce"],["NTNX","Nutanix"],["VMEM","廃止"],
  ["PEGA","Pegasystems"],["PRGS","Progress Software"],["MSCI","MSCI"],
  ["MCO","Moody's"],["SPGI","S&P Global"],["VRSK","Verisk Analytics"],
  ["BR","Broadridge Financial"],["FDS","FactSet Research"],
  ["TYL","Tyler Technologies"],["CSGP","CoStar Group"],
  ["ANSS","ANSYS"],["PTC","PTC"],["DLB","Dolby Laboratories"],
  ["TTGT","TechTarget"],["BAND","Bandwidth"],["EGHT","8x8"],
  ["OOMA","Ooma"],["LSPD","Lightspeed Commerce"],

  // Consumer Discretionary
  ["AMZN","Amazon"],["TSLA","Tesla"],["HD","Home Depot"],["MCD","McDonald's"],
  ["NKE","Nike"],["LOW","Lowe's"],["SBUX","Starbucks"],["TJX","TJX Companies"],
  ["BKNG","Booking Holdings"],["ABNB","Airbnb"],["ROST","Ross Stores"],
  ["CMG","Chipotle Mexican Grill"],["YUM","Yum! Brands"],["QSR","Restaurant Brands"],
  ["DPZ","Domino's Pizza"],["PZZA","Papa John's"],["JACK","Jack in the Box"],
  ["SHAK","Shake Shack"],["WING","Wingstop"],["BLMN","Bloomin' Brands"],["TXRH","Texas Roadhouse"],
  ["EAT","Brinker International"],["DRI","Darden Restaurants"],["CAKE","Cheesecake Factory"],
  ["RUTH","Ruth's Hospitality (廃止)"],["BJRI","BJ's Restaurants"],
  ["F","Ford Motor"],["GM","General Motors"],["STLA","Stellantis"],
  ["TM","Toyota Motor ADR"],["HMC","Honda Motor ADR"],["NSANY","Nissan ADR"],
  ["LI","Li Auto"],["NIO","NIO"],["XPEV","XPeng"],["RIVN","Rivian"],
  ["LCID","Lucid Group"],["FSR","Fisker"],["GOEV","Canoo"],
  ["AZO","AutoZone"],["ORLY","O'Reilly Automotive"],["AAP","Advance Auto Parts"],
  ["GPC","Genuine Parts"],["MNRO","Monro"],["SAH","Sonic Automotive"],
  ["AN","AutoNation"],["KMX","CarMax"],["CVNA","Carvana"],["VRM","Vroom"],
  ["PAG","Penske Automotive"],["GPI","Group 1 Automotive"],
  ["DHI","D.R. Horton"],["LEN","Lennar"],["PHM","PulteGroup"],
  ["NVR","NVR"],["TOL","Toll Brothers"],["MDC","MDC Holdings"],
  ["TMHC","Taylor Morrison"],["MHO","M/I Homes"],["SKY","Skyline Champion"],
  ["CVCO","Cavco Industries"],["SSD","Simpson Manufacturing"],
  ["MAR","Marriott International"],["HLT","Hilton Worldwide"],
  ["H","Hyatt Hotels"],["IHG","IHG Hotels & Resorts ADR"],
  ["WH","Wyndham Hotels"],["VCNX","Vaccinex"],
  ["MGM","MGM Resorts"],["WYNN","Wynn Resorts"],["LVS","Las Vegas Sands"],
  ["CZR","Caesars Entertainment"],["PENN","Penn Entertainment"],
  ["BYD","Boyd Gaming"],["RCL","Royal Caribbean"],["CCL","Carnival"],
  ["NCLH","Norwegian Cruise Line"],
  ["LUV","Southwest Airlines"],["DAL","Delta Air Lines"],
  ["UAL","United Airlines"],["AAL","American Airlines"],["ALK","Alaska Air Group"],
  ["SAVE","Spirit Airlines (廃止)"],["HA","Hawaiian Holdings"],
  ["JBLU","JetBlue Airways"],["SKYW","SkyWest"],
  ["ULTA","Ulta Beauty"],["ETSY","Etsy"],["EBAY","eBay"],
  ["W","Wayfair"],["REAL","RealReal"],["FTCH","Farfetch (廃止)"],
  ["PVH","PVH Corp"],["RL","Ralph Lauren"],["TPR","Tapestry"],
  ["HBI","Hanesbrands"],["UA","Under Armour"],["COLM","Columbia Sportswear"],
  ["BOOT","Boot Barn"],["SCVL","Shoe Carnival"],["FL","Foot Locker"],
  ["FINL","Finish Line (廃止)"],["DKS","DICK'S Sporting Goods"],
  ["HIBB","Hibbett Sports"],["ASO","Academy Sports"],
  ["TIF","Tiffany (廃止)"],["SIG","Signet Jewelers"],["ZETA","Zeta Global"],
  ["WISH","ContextLogic (廃止)"],["OLLI","Ollie's Bargain Outlet"],
  ["BIG","Big Lots"],["FIVE","Five Below"],["DLLR","Dollar Tree"],
  ["DG","Dollar General"],["DLTR","Dollar Tree"],["COST","Costco"],
  ["WMT","Walmart"],["TGT","Target"],["KR","Kroger"],["SWY","Safeway (廃止)"],
  ["ACI","Albertsons"],["SFM","Sprouts Farmers Market"],
  ["BURL","Burlington Stores"],["JOSB","Jos. A. Bank (廃止)"],
  ["BCOR","Blucora (廃止)"],["GME","GameStop"],["AMC","AMC Entertainment"],
  ["BBBY","Bed Bath & Beyond (廃止)"],["PIR","Pier 1 Imports (廃止)"],
  ["RH","RH (Restoration Hardware)"],["WSM","Williams-Sonoma"],
  ["BBB","Bed Bath (廃止)"],["CASY","Casey's General Stores"],

  // Consumer Staples
  ["WMT","Walmart"],["PG","Procter & Gamble"],["KO","Coca-Cola"],
  ["PEP","PepsiCo"],["COST","Costco"],["CL","Colgate-Palmolive"],
  ["GIS","General Mills"],["K","Kellogg's / WK Kellogg"],["KHC","Kraft Heinz"],
  ["MDLZ","Mondelez International"],["PM","Philip Morris International"],
  ["MO","Altria Group"],["HSY","Hershey"],["STZ","Constellation Brands"],
  ["CHD","Church & Dwight"],["SYY","Sysco"],["ADM","Archer-Daniels-Midland"],
  ["KMB","Kimberly-Clark"],["MKC","McCormick"],["SJM","J.M. Smucker"],
  ["CAG","Conagra Brands"],["HRL","Hormel Foods"],["TSN","Tyson Foods"],
  ["LW","Lamb Weston"],["INGR","Ingredion"],["JJSF","J&J Snack Foods"],
  ["SAFM","Sanderson Farms (廃止)"],["PF","Pinnacle Foods (廃止)"],
  ["BG","Bunge Global"],["CF","CF Industries"],["MOS","Mosaic"],
  ["FMC","FMC Corporation"],["CTVA","Corteva"],["NTR","Nutrien"],
  ["AVP","Avon Products (廃止)"],["EL","Estée Lauder"],
  ["COTY","Coty"],["SPB","Spectrum Brands"],["ENERGIZER","Energizer"],
  ["ENR","Energizer Holdings"],["CLX","Clorox"],["RB","Reckitt (廃止/英国)"],
  ["UN","Unilever ADR"],["UL","Unilever ADR"],["BTI","British American Tobacco ADR"],
  ["DEO","Diageo ADR"],["SAM","Boston Beer"],["TAP","Molson Coors"],
  ["BUD","Anheuser-Busch InBev ADR"],["FLO","Flowers Foods"],
  ["TWNK","Hostess Brands"],["LANC","Lancaster Colony"],["SNAK","廃止"],
  ["SMPL","Simply Good Foods"],["HAIN","Hain Celestial"],["BYND","Beyond Meat"],
  ["VITL","Vital Farms"],["IIPR","Innovative Industrial Properties"],

  // Health Care
  ["UNH","UnitedHealth Group"],["JNJ","Johnson & Johnson"],
  ["LLY","Eli Lilly"],["ABBV","AbbVie"],["MRK","Merck"],
  ["ABT","Abbott Laboratories"],["TMO","Thermo Fisher Scientific"],
  ["DHR","Danaher"],["AMGN","Amgen"],["ISRG","Intuitive Surgical"],
  ["CVS","CVS Health"],["CI","Cigna"],["HUM","Humana"],
  ["ELV","Elevance Health"],["BSX","Boston Scientific"],["SYK","Stryker"],
  ["VRTX","Vertex Pharmaceuticals"],["REGN","Regeneron Pharmaceuticals"],
  ["BIIB","Biogen"],["GILD","Gilead Sciences"],["ZBH","Zimmer Biomet"],
  ["BAX","Baxter International"],["RMD","ResMed"],
  ["A","Agilent Technologies"],["IQV","IQVIA Holdings"],
  ["DGX","Quest Diagnostics"],["LH","Labcorp"],
  ["MCK","McKesson"],["CAH","Cardinal Health"],["ABC","AmerisourceBergen"],
  ["HOLX","Hologic"],["MTD","Mettler-Toledo"],["COO","Cooper Companies"],
  ["HSIC","Henry Schein"],["WAT","Waters Corporation"],["TFX","Teleflex"],
  ["ALGN","Align Technology"],["DXCM","DexCom"],["PODD","Insulet"],
  ["TNDM","Tandem Diabetes Care"],["PRTA","Prothena"],
  ["INVA","Innoviva"],["ARWR","Arrowhead Pharmaceuticals"],
  ["ALNY","Alnylam Pharmaceuticals"],["BLUE","bluebird bio"],
  ["FATE","Fate Therapeutics"],["EDIT","Editas Medicine"],
  ["CRSP","CRISPR Therapeutics"],["NTLA","Intellia Therapeutics"],
  ["BEAM","Beam Therapeutics"],["VERV","Verve Therapeutics"],
  ["RXRX","Recursion Pharmaceuticals"],["SEER","Seer"],
  ["ILMN","Illumina"],["PACIFIC","Pacific Biosciences"],["PACB","PacBio"],
  ["FLDM","Fluidigm (廃止)"],["NVTA","Invitae"],
  ["EXAS","Exact Sciences"],["GH","Guardant Health"],
  ["BHVN","Biohaven (廃止)"],["PTGX","Protagonist Therapeutics"],
  ["PTCT","PTC Therapeutics"],["SRPT","Sarepta Therapeutics"],
  ["BMRN","BioMarin Pharmaceutical"],["RARE","Ultragenyx"],
  ["ACAD","ACADIA Pharmaceuticals"],["LGND","Ligand Pharmaceuticals"],
  ["CORT","Corcept Therapeutics"],["HRMY","Harmony Biosciences"],
  ["ITCI","Intra-Cellular Therapies"],["SAVA","Cassava Sciences"],
  ["ANIP","ANI Pharmaceuticals"],["HRTX","Heron Therapeutics"],
  ["LNTH","Lantheus Holdings"],["PRAX","Praxis Precision Medicine"],
  ["DAWN","Day One Biopharmaceuticals"],["RCUS","Arcus Biosciences"],
  ["AGIO","Agios Pharmaceuticals"],["XLRN","Acceleron (廃止)"],
  ["SGNY","Signify Health (廃止)"],["SDGR","Schrödinger"],
  ["MDRX","Allscripts (廃止)"],["HQY","HealthEquity"],
  ["HCAT","Health Catalyst"],["PHR","Phreesia"],["ACCD","Accolade"],
  ["TDOC","Teladoc Health"],["AMWL","American Well (Amwell)"],
  ["OPAL","Opal Fuels"],["CRL","Charles River Laboratories"],
  ["MEDP","Medpace Holdings"],["ICLR","ICON"],["PPD","PPD (廃止)"],
  ["DOCS","Doximity"],["HIMS","Hims & Hers Health"],["WELL","Welltower"],
  ["HR","Healthpeak Properties"],["VTR","Ventas"],["OHI","Omega Healthcare"],
  ["SBRA","Sabra Health Care REIT"],["NHI","National Health Investors"],
  ["UHS","Universal Health Services"],["THC","Tenet Healthcare"],["HCA","HCA Healthcare"],
  ["CYH","Community Health Systems"],["LPNT","LifePoint (廃止)"],
  ["ENSG","Ensign Group"],["AMED","Amedisys"],["LHC","LHC Group (廃止)"],
  ["EHAB","Enhabit"],["BKD","Brookdale Senior Living"],
  ["MOH","Molina Healthcare"],["CNC","Centene"],["WCG","WellCare (廃止)"],
  ["OSCR","Oscar Health"],["CLOV","Clover Health"],

  // Financials
  ["JPM","JPMorgan Chase"],["BAC","Bank of America"],["WFC","Wells Fargo"],
  ["GS","Goldman Sachs"],["MS","Morgan Stanley"],["AXP","American Express"],
  ["BLK","BlackRock"],["BX","Blackstone"],["SCHW","Charles Schwab"],
  ["CME","CME Group"],["ICE","Intercontinental Exchange"],
  ["C","Citigroup"],["USB","U.S. Bancorp"],["PNC","PNC Financial Services"],
  ["TFC","Truist Financial"],["COF","Capital One Financial"],
  ["AIG","American International Group"],["ALL","Allstate"],
  ["MET","MetLife"],["PRU","Prudential Financial"],["AFL","Aflac"],
  ["CINF","Cincinnati Financial"],["LNC","Lincoln National"],
  ["PFG","Principal Financial Group"],["GL","Globe Life"],
  ["RE","Everest Re Group"],["RNR","RenaissanceRe"],
  ["ACGL","Arch Capital Group"],["WRB","W.R. Berkley"],
  ["HIG","Hartford Financial Services"],["THG","Hanover Insurance"],
  ["BRK.A","Berkshire Hathaway A"],["BRK.B","Berkshire Hathaway B"],
  ["MKL","Markel Group"],["CB","Chubb"],["PGR","Progressive"],
  ["AON","Aon"],["MMC","Marsh & McLennan"],["WTW","Willis Towers Watson"],
  ["AJG","Arthur J. Gallagher"],["BRO","Brown & Brown"],
  ["ERIE","Erie Indemnity"],["KMPR","Kemper"],
  ["JRVR","James River Group"],["KNTK","Kiniksa Pharmaceuticals"],
  ["STT","State Street"],["BK","Bank of New York Mellon"],
  ["NTRS","Northern Trust"],["FHN","First Horizon"],
  ["KEY","KeyCorp"],["CFG","Citizens Financial Group"],
  ["FITB","Fifth Third Bancorp"],["HBAN","Huntington Bancshares"],
  ["RF","Regions Financial"],["MTB","M&T Bank"],["WBS","Webster Financial"],
  ["WAL","Western Alliance Bancorporation"],["BOKF","BOK Financial"],
  ["CBSH","Commerce Bancshares"],["WSFS","WSFS Financial"],
  ["FCNCA","First Citizens BancShares"],["FFIN","Frost Bankers"],
  ["TROW","T. Rowe Price"],["FNF","Fidelity National Financial"],
  ["FAF","First American Financial"],["STC","Stewart Information Services"],
  ["LPLA","LPL Financial Holdings"],["RJF","Raymond James Financial"],
  ["PIPR","Piper Sandler"],["VRTS","Virtus Investment Partners"],
  ["AMK","AssetMark Financial"],["MORN","Morningstar"],
  ["IEX","IDEX Corporation"],["HRB","H&R Block"],
  ["DFS","Discover Financial Services"],["SYF","Synchrony Financial"],
  ["ALLY","Ally Financial"],["NAVI","Navient"],["SLM","Sallie Mae"],
  ["OMF","OneMain Financial"],["EZE","廃止"],["TREE","LendingTree"],
  ["UPST","Upstart Holdings"],["AFRM","Affirm Holdings"],["SOFI","SoFi Technologies"],
  ["LC","LendingClub"],["OPFI","OppFi"],["PRAA","PRA Group"],
  ["WRLD","World Acceptance"],["ENVA","Enova International"],
  ["CACC","Credit Acceptance"],["SC","Santander Consumer USA (廃止)"],
  ["OMI","Owens & Minor"],["SPNS","Sapiens International"],

  // Energy
  ["XOM","Exxon Mobil"],["CVX","Chevron"],["COP","ConocoPhillips"],
  ["EOG","EOG Resources"],["SLB","SLB (Schlumberger)"],
  ["PSX","Phillips 66"],["VLO","Valero Energy"],["MPC","Marathon Petroleum"],
  ["HAL","Halliburton"],["HES","Hess"],["DVN","Devon Energy"],
  ["BKR","Baker Hughes"],["OXY","Occidental Petroleum"],
  ["CTRA","Coterra Energy"],["APA","APA Corporation"],
  ["FANG","Diamondback Energy"],["PXD","Pioneer Natural Resources (廃止)"],
  ["PR","Permian Resources"],["MTDR","Matador Resources"],
  ["VTLE","Vital Energy"],["ROCC","Ranger Oil (廃止)"],
  ["CPE","Callon Petroleum"],["SM","SM Energy"],["CNX","CNX Resources"],
  ["AR","Antero Resources"],["EQT","EQT Corporation"],["RRC","Range Resources"],
  ["SWN","Southwestern Energy"],["CHK","Chesapeake Energy"],
  ["KMI","Kinder Morgan"],["WMB","Williams Companies"],["OKE","ONEOK"],
  ["EPD","Enterprise Products Partners"],["ET","Energy Transfer"],
  ["LNG","Cheniere Energy"],["CQP","Cheniere Energy Partners"],
  ["TRGP","Targa Resources"],["DT","Dynatrace"],
  ["MMP","Magellan Midstream (廃止)"],["MPLX","MPLX"],
  ["PAA","Plains All American Pipeline"],["GEL","Genesis Energy"],
  ["CAPL","CrossAmerica Partners"],["CDEV","Centennial Resource (廃止)"],
  ["NOV","NOV"],["FTI","TechnipFMC"],["WTTR","Select Water Solutions"],
  ["CHX","ChampionX"],["SLB","SLB"],["BOOM","Dynamic Materials (廃止)"],
  ["NEX","NexTier Oilfield (廃止)"],["RES","RPC"],["PKD","Parker Drilling (廃止)"],
  ["NE","Noble Corporation"],["VAL","Valaris"],["DO","Diamond Offshore"],
  ["RIG","Transocean"],["HP","Helmerich & Payne"],["PMP","Portman Ridge Finance"],
  ["NEXT","NextDecade"],["TELL","Tellurian (廃止)"],["GLNG","Golar LNG"],
  ["FLNG","FLEX LNG"],["CLMT","Calumet Specialty Products"],
  ["DK","Delek US Holdings"],["PBF","PBF Energy"],["HFC","HollyFrontier (廃止)"],
  ["PARR","Par Pacific Holdings"],["CALUMET","Calumet"],
  ["REX","REX Energy (廃止)"],["AMPY","Amplify Energy"],
  ["IMPP","Imperial Petroleum"],["TNK","Teekay Tankers"],
  ["FRO","Frontline"],["HAFN","Hafnia"],["DHT","DHT Holdings"],
  ["INSW","International Seaways"],["STNG","Scorpio Tankers"],
  ["TRMD","TORM"],["ASC","Ardmore Shipping"],

  // Materials
  ["LIN","Linde"],["APD","Air Products and Chemicals"],
  ["ECL","Ecolab"],["SHW","Sherwin-Williams"],["FCX","Freeport-McMoRan"],
  ["NEM","Newmont"],["ALB","Albemarle"],["DD","DuPont de Nemours"],
  ["PPG","PPG Industries"],["IFF","International Flavors & Fragrances"],
  ["CF","CF Industries"],["MOS","Mosaic"],["NUE","Nucor"],
  ["MLM","Martin Marietta Materials"],["VMC","Vulcan Materials"],
  ["RPM","RPM International"],["EMN","Eastman Chemical"],["LTHM","Livent (廃止)"],
  ["SQM","SQM ADR"],["ALTM","Arcosa"],["CE","Celanese"],
  ["FMC","FMC Corporation"],["CTVA","Corteva"],["SON","Sonoco Products"],
  ["AVY","Avery Dennison"],["PKG","Packaging Corporation of America"],
  ["IP","International Paper"],["GPK","Graphic Packaging Holding"],
  ["SEE","Sealed Air"],["BALL","Ball Corporation"],["CCK","Crown Holdings"],
  ["ATR","AptarGroup"],["SLGN","Silgan Holdings"],["AMCR","Amcor"],
  ["BERY","Berry Global"],["GEF","Greif"],["OI","O-I Glass"],
  ["AIN","Albany International"],["DOOR","Masonite International"],
  ["FBHS","Fortune Brands Home (廃止)"],["MAS","Masco"],["SSD","Simpson Manufacturing"],
  ["TREX","Trex Company"],["PGTI","PGT Innovations (廃止)"],
  ["AZEK","AZEK Company"],["CSL","Carlisle Companies"],
  ["WOR","Worthington Enterprises"],["CMC","Commercial Metals"],
  ["KALU","Kaiser Aluminum"],["CRS","Carpenter Technology"],
  ["ARNC","Arconic"],["HWM","Howmet Aerospace"],["ESAB","ESAB Corporation"],
  ["RYI","Ryerson Towing"],["GATO","Gatos Silver (廃止)"],
  ["AG","First Majestic Silver"],["PAAS","Pan American Silver"],
  ["AEM","Agnico Eagle Mines"],["KGC","Kinross Gold"],
  ["AU","AngloGold Ashanti ADR"],["NGD","New Gold"],
  ["GFI","Gold Fields ADR"],["SBSW","Sibanye Stillwater ADR"],
  ["RGLD","Royal Gold"],["WPM","Wheaton Precious Metals"],
  ["FNV","Franco-Nevada"],["OR","Osisko Gold Royalties"],
  ["USAS","Americas Silver (廃止)"],
  ["TECK","Teck Resources ADR"],["RIO","Rio Tinto ADR"],
  ["VALE","Vale ADR"],["BHP","BHP Group ADR"],["AA","Alcoa"],
  ["CENX","Century Aluminum"],["SLCA","U.S. Silica (廃止)"],

  // Industrials
  ["RTX","RTX (Raytheon)"],["HON","Honeywell"],["UPS","UPS"],
  ["CAT","Caterpillar"],["DE","Deere & Company"],["LMT","Lockheed Martin"],
  ["GE","GE Aerospace"],["MMM","3M"],["EMR","Emerson Electric"],
  ["ETN","Eaton"],["PH","Parker-Hannifin"],["PCAR","PACCAR"],
  ["CMI","Cummins"],["ITW","Illinois Tool Works"],["NOC","Northrop Grumman"],
  ["GD","General Dynamics"],["CSX","CSX Corporation"],["NSC","Norfolk Southern"],
  ["UNP","Union Pacific"],["FDX","FedEx"],["XYL","Xylem"],
  ["IR","Ingersoll Rand"],["TT","Trane Technologies"],["DOV","Dover"],
  ["PNR","Pentair"],["ROK","Rockwell Automation"],["AME","AMETEK"],
  ["ROP","Roper Technologies"],["VRNS","Varonis Systems"],
  ["CTAS","Cintas"],["ADP","ADP"],["PAYX","Paychex"],
  ["MAN","ManpowerGroup"],["RHI","Robert Half International"],["KFRC","Kforce"],
  ["KELYA","Kelly Services"],["HCSG","Healthcare Services Group"],
  ["SPXC","SPX Technologies"],["SPX","SPX"],["HUBB","Hubbell"],
  ["AOS","A.O. Smith"],["GNRC","Generac Holdings"],["WSO","Watsco"],
  ["WMS","Advanced Drainage Systems"],["AAON","AAON"],
  ["JCI","Johnson Controls"],["CARR","Carrier Global"],["OTIS","Otis Worldwide"],
  ["TKR","Timken"],["NN","NN"],["AIMC","Altra Industrial Motion (廃止)"],
  ["CFX","Colfax (廃止)"],["ESLT","Elbit Systems ADR"],["HEI","HEICO"],
  ["TDG","TransDigm Group"],["AXON","Axon Enterprise"],["BWA","BorgWarner"],
  ["MHK","Mohawk Industries"],["AWI","Armstrong World Industries"],
  ["SNA","Snap-on"],["KN","Knowles"],["CW","Curtiss-Wright"],
  ["TGI","Triumph Group"],["MOG.A","Moog A"],["DRS","Leonardo DRS"],
  ["LDOS","Leidos Holdings"],["SAIC","Science Applications International"],
  ["BAH","Booz Allen Hamilton"],["CACI","CACI International"],
  ["VSE","VSE Corporation"],["KEYW","Keyw Holding (廃止)"],
  ["GVA","Granite Construction"],["AGX","Argan"],["STRL","Sterling Construction"],
  ["DY","Dycom Industries"],["ASTE","Astec Industries"],
  ["ROAD","Construction Partners"],["MYRG","MYR Group"],
  ["PRIM","Primoris Services"],["PWR","Quanta Services"],
  ["MYR","MYR Group"],["HEES","H&E Equipment Services"],
  ["WSC","WillScot Holdings"],["URI","United Rentals"],["AL","Air Lease"],
  ["AER","AerCap Holdings"],["ASGN","ASGN"],["EXPO","Exponent"],
  ["ICF","InterContinental Finance"],["TRN","Trinity Industries"],
  ["GBX","Greenbrier Companies"],["RAIL","FreightCar America"],
  ["WLFC","Willis Lease Finance"],["FTAI","FTAI Aviation"],
  ["JBHT","J.B. Hunt Transport"],["SAIA","Saia"],["ODFL","Old Dominion Freight Line"],
  ["LSTR","Landstar System"],["WERN","Werner Enterprises"],
  ["KNX","Knight-Swift Transportation"],["MRTN","Marten Transport"],
  ["HTLD","Heartland Express"],["ECHO","Echo Global Logistics"],
  ["CHRW","C.H. Robinson Worldwide"],["XPO","XPO"],["GXO","GXO Logistics"],
  ["DSKE","Daseke (廃止)"],["USX","U.S. Xpress (廃止)"],
  ["TRTN","Triton International (廃止)"],["CAI","CAI International (廃止)"],
  ["GATX","GATX Corporation"],["RXO","RXO"],["DPRO","廃止"],

  // Real Estate
  ["AMT","American Tower"],["PLD","Prologis"],["CCI","Crown Castle"],
  ["EQIX","Equinix"],["SPG","Simon Property Group"],["DLR","Digital Realty Trust"],
  ["O","Realty Income"],["WELL","Welltower"],["EQR","Equity Residential"],
  ["PSA","Public Storage"],["ARE","Alexandria Real Estate"],
  ["EXR","Extra Space Storage"],["VICI","VICI Properties"],["AVB","AvalonBay Communities"],
  ["ESS","Essex Property Trust"],["MAA","Mid-America Apartment Communities"],
  ["CPT","Camden Property Trust"],["UDR","UDR"],["NNN","NNN REIT"],
  ["STAG","STAG Industrial"],["REXR","Rexford Industrial Realty"],
  ["EGP","EastGroup Properties"],["FR","First Industrial Realty Trust"],
  ["COLD","Americold Realty Trust"],["LPT","Liberty Property (廃止)"],
  ["IIPR","Innovative Industrial Properties"],["HASI","Hannon Armstrong"],
  ["IRM","Iron Mountain"],["SBAC","SBA Communications"],
  ["WY","Weyerhaeuser"],["PW","Power REIT"],["PCH","PotlatchDeltic"],
  ["RYN","Rayonier"],["CTT","CatchMark Timber (廃止)"],
  ["CBRE","CBRE Group"],["JLL","Jones Lang LaSalle"],
  ["CSGP","CoStar Group"],["RLGY","Realogy (廃止)"],["RDFN","Redfin"],
  ["Z","Zillow Group C"],["ZG","Zillow Group A"],["OPEN","Opendoor Technologies"],
  ["OPAD","Offerpad Solutions"],["HOUS","Anywhere Real Estate"],
  ["VER","VEREIT (廃止)"],["STORE","STORE Capital (廃止)"],
  ["WPC","W.P. Carey"],["SRC","Spirit Realty Capital (廃止)"],
  ["ADC","Agree Realty"],["EPRT","Essential Properties Realty"],
  ["FCPT","Four Corners Property Trust"],["NTST","NETSTREIT"],
  ["GTY","Getty Realty"],["ITIC","Investors Title"],
  ["HIW","Highwoods Properties"],["BXP","Boston Properties"],
  ["SLG","SL Green Realty"],["VNO","Vornado Realty Trust"],
  ["CUZ","Cousins Properties"],["CLI","Mack-Cali (廃止)"],
  ["PKI","PerkinElmer (廃止→Revvity)"],["RVTY","Revvity"],
  ["PGRE","Paramount Group"],["MNR","Mack-Cali (廃止)"],
  ["EQC","Equity Commonwealth (廃止)"],["HPP","Hudson Pacific Properties"],
  ["PDM","Piedmont Office Realty"],["DEA","Easterly Government Properties"],
  ["OFC","Corporate Office Properties"],["CTRE","CareTrust REIT"],
  ["MPW","Medical Properties Trust"],["GMRE","Global Medical REIT"],
  ["LTC","LTC Properties"],["CHCT","Community Healthcare Trust"],
  ["BRT","BRT Realty Trust"],["KW","Kennedy-Wilson Holdings"],

  // Utilities
  ["NEE","NextEra Energy"],["SO","Southern Company"],["D","Dominion Energy"],
  ["DUK","Duke Energy"],["SRE","Sempra"],["AEP","American Electric Power"],
  ["XEL","Xcel Energy"],["EXC","Exelon"],["PEG","Public Service Enterprise Group"],
  ["ED","Consolidated Edison"],["WEC","WEC Energy Group"],["PCG","PG&E"],
  ["ETR","Entergy"],["EIX","Edison International"],["ES","Eversource Energy"],
  ["CNP","CenterPoint Energy"],["OGE","OGE Energy"],["EVRG","Evergy"],
  ["POR","Portland General Electric"],["AVA","Avista"],["NWE","NorthWestern"],
  ["MGEE","Madison Gas and Electric"],["OTTR","Otter Tail"],
  ["IDACORP","IDACORP"],["IDA","IDACORP"],["NI","NiSource"],["LNT","Alliant Energy"],
  ["AEE","Ameren"],["CMS","CMS Energy"],["AT","Atlantic Tele-Network"],
  ["UTL","Unitil"],["BKH","Black Hills"],["ARTNA","Artesian Resources"],
  ["MSEX","Middlesex Water"],["SJW","SJW Group"],["YORW","York Water"],
  ["AWR","American States Water"],["AWK","American Water Works"],
  ["WTRG","Essential Utilities"],["CWT","California Water Service"],
  ["CDWWS","廃止"],["ENIA","Enel Americas ADR"],["ELP","Copel ADR"],
  ["NEOEN","廃止"],["RNST","Renasant"],

  // Communication Services
  ["GOOGL","Alphabet C"],["GOOG","Alphabet A"],["META","Meta Platforms"],
  ["NFLX","Netflix"],["DIS","Walt Disney"],["CMCSA","Comcast"],
  ["T","AT&T"],["VZ","Verizon"],["TTWO","Take-Two Interactive"],
  ["EA","Electronic Arts"],["ATVI","Activision Blizzard (廃止→MSFT)"],
  ["WBD","Warner Bros. Discovery"],["PARA","Paramount Global"],
  ["CHTR","Charter Communications"],["TMUS","T-Mobile US"],
  ["SNAP","Snap"],["PINS","Pinterest"],["SPOT","Spotify ADR"],
  ["ROKU","Roku"],["TKO","TKO Group Holdings"],["WWE","WWE (廃止→TKO)"],
  ["IAC","IAC"],["MTCH","Match Group"],["BMBL","Bumble"],
  ["TWTR","Twitter (廃止→X)"],["RDDT","Reddit"],
  ["LNKD","LinkedIn (廃止→MSFT)"],["FB","Meta (旧名)"],
  ["NYT","New York Times"],["GCI","Gannett"],["MDP","Meredith (廃止)"],
  ["SCI","Service Corporation International"],
  ["NWSA","News Corp A"],["NWS","News Corp B"],["FGX","廃止"],
  ["IPG","Interpublic Group"],["OMC","Omnicom Group"],["PUBGY","Publicis ADR"],
  ["FWONA","Liberty Formula One A"],["FWONK","Liberty Formula One K"],
  ["LSXMK","Liberty SiriusXM K"],["SIRI","Sirius XM Holdings"],
  ["LBRDK","Liberty Broadband K"],["GLIBA","GCI Liberty (廃止)"],
  ["RCI","Rogers Communications ADR"],["BCE","BCE ADR"],["MBT","Mobile TeleSystems ADR"],
  ["LILAK","Liberty Latin America C"],["LILA","Liberty Latin America A"],
  ["CABO","Cable One (廃止)"],["ATUS","Altice USA (廃止)"],
  ["DISH","DISH Network (廃止)"],["SATS","EchoStar"],
  ["VSAT","ViaSat"],["GSAT","Globalstar"],["ORB","廃止"],
  ["MAXN","Maxeon Solar"],["SPCE","Virgin Galactic"],
  ["ASTR","Astra Space"],["RDW","Redwire"],["SFET","廃止"],
  ["MNKD","MannKind"],["CCCS","廃止"],
  ["AMX","América Móvil ADR"],["CHL","China Mobile ADR"],
  ["CHU","China Unicom ADR"],["CHA","China Telecom ADR"],

  // International / ADR
  ["TSM","Taiwan Semiconductor ADR"],["BABA","Alibaba Group ADR"],
  ["TCEHY","Tencent ADR"],["BIDU","Baidu ADR"],["JD","JD.com ADR"],
  ["PDD","PDD Holdings ADR"],["NTES","NetEase ADR"],["BILI","Bilibili ADR"],
  ["TME","Tencent Music ADR"],["HUYA","Huya ADR"],["IQ","iQIYI ADR"],
  ["DIDI","DiDi Global (廃止)"],["GRAB","Grab Holdings"],
  ["SEA","Sea Limited ADR"],["SHOP","Shopify ADR"],["MELI","MercadoLibre"],
  ["LATI","廃止"],["NU","Nu Holdings"],["StoneCo","StoneCo"],["STNE","StoneCo"],
  ["PAGS","PagSeguro ADR"],["XP","XP"],["OINK","廃止"],
  ["VALE","Vale ADR"],["ITUB","Itaú Unibanco ADR"],["BBD","Bradesco ADR"],
  ["ABEV","Ambev ADR"],["VNET","VNET Group ADR"],
  ["CANG","Cango ADR"],["LU","Lufax Holding ADR"],
  ["FUTU","Futu Holdings ADR"],["TIGR","UP Fintech ADR"],
  ["NOAH","Noah Holdings ADR"],["CNF","廃止"],
  ["SAP","SAP ADR"],["ASML","ASML ADR"],["SHEL","Shell ADR"],
  ["BP","BP ADR"],["TTE","TotalEnergies ADR"],["ENB","Enbridge ADR"],
  ["TRP","TC Energy ADR"],["CNQ","Canadian Natural Resources ADR"],
  ["SU","Suncor Energy ADR"],["CVE","Cenovus Energy ADR"],
  ["NVO","Novo Nordisk ADR"],["AZN","AstraZeneca ADR"],
  ["RHHBY","Roche ADR"],["NVS","Novartis ADR"],["SNY","Sanofi ADR"],
  ["GSK","GSK ADR"],["UCB","UCB ADR"],["BAYRY","Bayer ADR"],
  ["ALIZY","Allianz ADR"],["CS","Credit Suisse (廃止)"],
  ["UBS","UBS Group ADR"],["DB","Deutsche Bank ADR"],
  ["ING","ING Groep ADR"],["BCS","Barclays ADR"],["HSBC","HSBC ADR"],
  ["LYG","Lloyds Banking ADR"],["NWG","NatWest Group ADR"],
  ["SMFG","Sumitomo Mitsui Financial ADR"],
  ["MFG","Mizuho Financial ADR"],["MTU","Mitsubishi UFJ ADR"],
  ["SONY","Sony Group ADR"],["TM","Toyota Motor ADR"],
  ["HMC","Honda Motor ADR"],["MUFG","Mitsubishi UFJ ADR"],
  ["KB","KB Financial Group ADR"],["SHG","Shinhan Financial ADR"],
  ["WF","Woori Financial ADR"],["HDB","HDFC Bank ADR"],
  ["IBN","ICICI Bank ADR"],["INFY","Infosys ADR"],["WIT","Wipro ADR"],
  ["TCS","Tata Consultancy (LSE)"],
  ["BEKE","KE Holdings ADR"],["BOSS","Hugo Boss ADR"],["HEN3","Henkel ADR"],
  ["BNTX","BioNTech ADR"],["VKTX","Viking Therapeutics"],
  ["ARM","Arm Holdings ADR"],["MSTR","MicroStrategy"],
  ["COIN","Coinbase Global"],["HOOD","Robinhood Markets"],["OPEN","廃止"],

  // ETF / Index Funds (補足)
  ["SPY","SPDR S&P 500 ETF"],["QQQ","Invesco QQQ Trust"],["IVV","iShares S&P 500"],
  ["VOO","Vanguard S&P 500 ETF"],["VTI","Vanguard Total Stock Market"],
  ["VEA","Vanguard FTSE Developed Markets"],["VWO","Vanguard FTSE Emerging Markets"],
  ["EEM","iShares MSCI Emerging Markets"],["EFA","iShares MSCI EAFE"],
  ["GLD","SPDR Gold Shares"],["SLV","iShares Silver Trust"],["IAU","iShares Gold Trust"],
  ["USO","United States Oil Fund"],["BND","Vanguard Total Bond Market"],
  ["AGG","iShares Core US Aggregate Bond"],["TLT","iShares 20+ Year Treasury Bond"],
  ["LQD","iShares iBoxx $ Investment Grade Corp Bond"],
  ["HYG","iShares iBoxx $ High Yield Corp Bond"],
  ["VIG","Vanguard Dividend Appreciation"],["VYM","Vanguard High Dividend Yield"],
  ["SCHD","Schwab US Dividend Equity"],["HDV","iShares Core High Dividend"],
  ["DVY","iShares Select Dividend"],
  ["XLK","Technology Select Sector SPDR"],["XLV","Health Care Select Sector"],
  ["XLF","Financial Select Sector"],["XLE","Energy Select Sector"],
  ["XLI","Industrial Select Sector"],["XLP","Consumer Staples Select Sector"],
  ["XLY","Consumer Discretionary Select Sector"],["XLU","Utilities Select Sector"],
  ["XLRE","Real Estate Select Sector"],["XLB","Materials Select Sector"],
  ["XLC","Communication Services Select Sector"],
  ["IWM","iShares Russell 2000"],["MDY","SPDR S&P MidCap 400"],
  ["IJH","iShares Core S&P Mid-Cap"],["IJR","iShares Core S&P Small-Cap"],
  ["VB","Vanguard Small-Cap"],["VT","Vanguard Total World Stock"],
  ["DIA","SPDR Dow Jones Industrial Average"],
  ["TQQQ","ProShares UltraPro QQQ"],["SQQQ","ProShares UltraPro Short QQQ"],
  ["SOXL","Direxion Daily Semiconductor Bull 3X"],
  ["SOXX","iShares Semiconductor"],["SMH","VanEck Semiconductor"],
  ["ARKK","ARK Innovation"],["ARKG","ARK Genomic Revolution"],
  ["ARKW","ARK Next Generation Internet"],["ARKF","ARK Fintech Innovation"],
  ["BOTZ","Global X Robotics & AI"],["LIT","Global X Lithium & Battery Tech"],
  ["TAN","Invesco Solar"],["ICLN","iShares Global Clean Energy"],
  ["VNQ","Vanguard Real Estate"],["SCHH","Schwab US REIT"],["IYR","iShares US Real Estate"],
  ["VGT","Vanguard Information Technology"],["FTEC","Fidelity MSCI IT"],
  ["CIBR","First Trust NASDAQ Cybersecurity"],
  ["BUG","Global X Cybersecurity"],["HACK","ETFMG Prime Cyber Security"],
  ["SKYY","First Trust Cloud Computing"],["CLOU","Global X Cloud Computing"],
  ["WCLD","WisdomTree Cloud Computing"],
  ["FDN","First Trust Dow Jones Internet"],
  ["PAVE","Global X US Infrastructure Development"],
  ["KOMP","SPDR S&P Kensho New Economies"],
  ["ROBO","Robo Global Robotics & Automation"],
  ["AIQ","Global X Artificial Intelligence"],
  ["IRBO","iShares Robotics & AI Multisector"],
  ["FNG","AdvisorShares New Tech & Media"],
  ["VHT","Vanguard Health Care"],["XBI","SPDR S&P Biotech"],
  ["IBB","iShares Biotechnology"],["FBT","First Trust NYSE Arca Biotechnology"],
  ["ARCC","Ares Capital"],["FSK","FS KKR Capital"],
  ["PSEC","Prospect Capital"],["MAIN","Main Street Capital"],
  ["HTGC","Hercules Capital"],["GBDC","Golub Capital BDC"],
  ["SLRC","Solar Capital (廃止)"],["SUNS","Solar Senior Capital (廃止)"],
  ["TPVG","TriplePoint Venture Growth"],["CGBD","TCG BDC (廃止)"],

  // その他有名企業
  ["UBER","Uber Technologies"],["LYFT","Lyft"],["DASH","DoorDash"],
  ["ABNB","Airbnb"],["AIRBNB","廃止"],["VRBO","廃止"],
  ["EXPE","Expedia Group"],["TRIP","TripAdvisor"],["PCLN","廃止→BKNG"],
  ["HTHT","H World Group ADR"],["MAR","Marriott"],["HLT","Hilton"],
  ["WDAY","Workday"],["OKTA","Okta"],["MDB","MongoDB"],["ESTC","Elastic"],
  ["SNOW","Snowflake"],["PLTR","Palantir Technologies"],["RBLX","Roblox"],
  ["U","Unity Software"],["AI","C3.ai"],["BBAI","BigBear.ai"],
  ["SOUN","SoundHound AI"],["SMCI","Super Micro Computer"],
  ["DELL","Dell Technologies"],["HPQ","HP"],["HPE","HP Enterprise"],
  ["NTDOY","Nintendo ADR"],["CCOEY","Capcom ADR"],["SQNNY","Square Enix ADR"],
  ["SGAMY","SEGA Sammy ADR"],["BNTNY","BandaiNamco ADR"],
  ["ANET","Arista Networks"],["LITE","Lumentum Holdings"],
  ["VIAV","Viavi Solutions"],["CIEN","Ciena"],["CALX","Calix"],
  ["INFN","Infinera"],["ADTRAN","ADTRAN"],["ACIA","Acacia (廃止)"],
  ["TTEC","TTEC Holdings"],["SAIC","Science Applications International"],
  ["BAH","Booz Allen Hamilton"],["CACI","CACI International"],
  ["LDOS","Leidos"],["DRS","Leonardo DRS"],["KTOS","Kratos Defense"],
  ["HEI","HEICO"],["TDG","TransDigm"],["AXON","Axon Enterprise"],
  ["RHX","廃止"],["ARLO","Arlo Technologies"],["LOGI","Logitech ADR"],
  ["HEAR","Turtle Beach (廃止)"],["GPRO","GoPro"],["VUZI","Vuzix"],
  ["NCLH","Norwegian Cruise Line"],["RCL","Royal Caribbean Cruises"],
  ["CCL","Carnival"],["CUK","Carnival ADR"],
  ["MGM","MGM Resorts International"],["WYNN","Wynn Resorts"],
  ["LVS","Las Vegas Sands"],["CZR","Caesars Entertainment"],
  ["DKNG","DraftKings"],["RSI","Rush Street Interactive"],
  ["PENN","Penn Entertainment"],["EVRI","Everi Holdings"],
  ["AGS","PlayAGS (廃止)"],["BYD","Boyd Gaming"],
  ["GDEN","Golden Entertainment"],["FULL","廃止"],
  ["PTON","Peloton Interactive"],["LULU","Lululemon Athletica"],
  ["NKE","Nike"],["UAA","Under Armour A"],["SKX","Skechers"],
  ["COLM","Columbia Sportswear"],["VFC","VF Corporation"],
  ["RL","Ralph Lauren"],["PVH","PVH Corp"],["TPR","Tapestry"],
  ["HBI","Hanesbrands"],["GIII","G-III Apparel"],["OXM","Oxford Industries"],
  ["CATO","Cato"],["CHICO","Chico's FAS"],["TLYS","Tilly's"],
  ["ANF","Abercrombie & Fitch"],["AEO","American Eagle Outfitters"],
  ["URBN","Urban Outfitters"],["GPS","Gap"],["EXPR","Express (廃止)"],
  ["JWN","Nordstrom"],["M","Macy's"],["KSS","Kohl's"],["BBWI","Bath & Body Works"],
  ["LAZR","Luminar Technologies"],["LIDR","AEye (廃止)"],
  ["OUST","Ouster (廃止)"],["VLDR","Velodyne Lidar (廃止)"],
  ["PTRA","Proterra (廃止)"],["WKHS","Workhorse Group"],
  ["NKLA","Nikola"],["RIDE","Lordstown Motors (廃止)"],
  ["SOLO","Electrameccanica (廃止)"],["ZEV","Lightning eMotors (廃止)"],

  // ── ヘルスケア・製薬 Healthcare / Pharma ──────────────────────────
  ["JNJ","Johnson & Johnson"],["UNH","UnitedHealth Group"],
  ["LLY","Eli Lilly"],["ABBV","AbbVie"],["MRK","Merck"],
  ["TMO","Thermo Fisher Scientific"],["ABT","Abbott Laboratories"],
  ["DHR","Danaher"],["BMY","Bristol-Myers Squibb"],
  ["AMGN","Amgen"],["GILD","Gilead Sciences"],["VRTX","Vertex Pharmaceuticals"],
  ["REGN","Regeneron Pharmaceuticals"],["BIIB","Biogen"],
  ["MRNA","Moderna"],["BNTX","BioNTech ADR"],
  ["PFE","Pfizer"],["CVS","CVS Health"],["CI","Cigna Group"],
  ["ELV","Elevance Health"],["HUM","Humana"],["CNC","Centene"],
  ["MCK","McKesson"],["CAH","Cardinal Health"],["ABC","AmerisourceBergen"],
  ["SYK","Stryker"],["BSX","Boston Scientific"],["MDT","Medtronic"],
  ["BDX","Becton Dickinson"],["ZBH","Zimmer Biomet"],["EW","Edwards Lifesciences"],
  ["ISRG","Intuitive Surgical"],["RMD","ResMed"],["TFX","Teleflex"],
  ["MTD","Mettler-Toledo"],["WAT","Waters Corporation"],
  ["IDXX","IDEXX Laboratories"],["IQV","IQVIA Holdings"],
  ["A","Agilent Technologies"],["HOLX","Hologic"],
  ["DXCM","DexCom"],["ALGN","Align Technology"],["PODD","Insulet"],
  ["NVCR","NovoCure"],["ACAD","ACADIA Pharmaceuticals"],
  ["SGEN","Seagen (廃止→PFE)"],["ALKS","Alkermes"],
  ["INVA","Innoviva"],["PRGO","Perrigo"],["ENDO","Endo (廃止)"],
  ["JAZZ","Jazz Pharmaceuticals"],["EXEL","Exelixis"],["IOVA","Iovance Biotherapeutics"],
  ["ARWR","Arrowhead Pharmaceuticals"],["BLUE","bluebird bio"],
  ["FOLD","Amicus Therapeutics"],["RARE","Ultragenyx Pharmaceutical"],
  ["RVMD","Revolution Medicines"],["KYMR","Kymera Therapeutics"],
  ["RXRX","Recursion Pharmaceuticals"],["BEAM","Beam Therapeutics"],
  ["NTLA","Intellia Therapeutics"],["CRSP","CRISPR Therapeutics ADR"],
  ["EDIT","Editas Medicine"],["FATE","Fate Therapeutics"],
  ["HALO","Halozyme Therapeutics"],["IMVT","Immunovant"],
  ["PRAXIS","Praxis Precision Medicine"],
  ["NRIX","Nurix Therapeutics"],["KRTX","Karuna Therapeutics (廃止→BMY)"],
  ["PTGX","Protagonist Therapeutics"],["ACMR","ACM Research"],
  ["CLOV","Clover Health (廃止)"],["ONEM","1Life Healthcare (廃止→AMZN)"],
  ["WELL","Welltower"],["PEAK","Healthpeak Properties"],["HR","Healthcare Realty"],
  ["SBRA","Sabra Health Care REIT"],["NHI","National Health Investors"],
  ["LTC","LTC Properties"],["OHI","Omega Healthcare Investors"],
  ["CTRE","CareTrust REIT"],["GMRE","Global Medical REIT"],

  // ── 金融・保険 Financials ──────────────────────────────────────────
  ["JPM","JPMorgan Chase"],["BAC","Bank of America"],["WFC","Wells Fargo"],
  ["C","Citigroup"],["USB","US Bancorp"],["PNC","PNC Financial Services"],
  ["TFC","Truist Financial"],["KEY","KeyCorp"],["RF","Regions Financial"],
  ["CFG","Citizens Financial Group"],["HBAN","Huntington Bancshares"],
  ["FITB","Fifth Third Bancorp"],["MTB","M&T Bank"],["WAL","Western Alliance Bancorporation"],
  ["PACW","PacWest (廃止)"],["FRC","First Republic (廃止→JPM)"],
  ["SIVB","Silicon Valley Bank (廃止)"],["SBNY","Signature Bank (廃止)"],
  ["ZION","Zions Bancorporation"],["CMA","Comerica"],["FHN","First Horizon"],
  ["WBS","Webster Financial"],["SNV","Synovus Financial"],
  ["BOH","Bank of Hawaii"],["FFIN","First Financial Bankshares"],
  ["BOKF","BOK Financial"],["IBOC","International Bancshares"],
  ["GS","Goldman Sachs"],["MS","Morgan Stanley"],["BLK","BlackRock"],
  ["SCHW","Charles Schwab"],["AMP","Ameriprise Financial"],
  ["IVZ","Invesco"],["EV","Eaton Vance (廃止→MS)"],
  ["TROW","T. Rowe Price"],["BEN","Franklin Resources"],
  ["STT","State Street"],["BK","Bank of New York Mellon"],["NTRS","Northern Trust"],
  ["V","Visa"],["MA","Mastercard"],["AXP","American Express"],["DFS","Discover Financial"],
  ["COF","Capital One Financial"],["SYF","Synchrony Financial"],
  ["ALLY","Ally Financial"],["OMF","OneMain Financial"],["SLM","Sallie Mae"],
  ["NAVI","Navient"],["TREE","LendingTree"],["LC","LendingClub"],
  ["SOFI","SoFi Technologies"],["AFRM","Affirm Holdings"],["UPST","Upstart Holdings"],
  ["OPFI","OppFi"],["ESXB","廃止"],
  ["ICE","Intercontinental Exchange"],["CME","CME Group"],["CBOE","Cboe Global Markets"],
  ["NDAQ","Nasdaq"],["MKTX","MarketAxess Holdings"],
  ["IBKR","Interactive Brokers"],["RJF","Raymond James Financial"],
  ["JEF","Jefferies Financial Group"],["LAZ","Lazard (廃止→非公開)"],
  ["EVR","Evercore"],["PJT","PJT Partners"],["HLI","Houlihan Lokey"],
  ["WTW","Willis Towers Watson"],["MMC","Marsh & McLennan"],
  ["AON","Aon"],["BRO","Brown & Brown"],["AJG","Arthur J. Gallagher"],
  ["RLI","RLI Corp"],["RYAN","Ryan Specialty"],["ACGL","Arch Capital Group ADR"],
  ["MKL","Markel Group"],["HIG","Hartford Financial"],["TRV","Travelers Companies"],
  ["CB","Chubb"],["ALL","Allstate"],["PGR","Progressive"],["AFG","American Financial Group"],
  ["WRB","W.R. Berkley"],["KNSL","Kinsale Capital"],["HROW","Harrow"],
  ["RE","Everest Group"],["GL","Globe Life"],["RGA","Reinsurance Group of America"],
  ["MET","MetLife"],["PRU","Prudential Financial"],["LNC","Lincoln National"],
  ["UNM","Unum Group"],["PFG","Principal Financial Group"],
  ["VOYA","Voya Financial"],["CNO","CNO Financial Group"],
  ["BHF","Brighthouse Financial"],["PRI","Primerica"],
  ["SPGI","S&P Global"],["MCO","Moody's"],["MSCI","MSCI"],
  ["FDS","FactSet Research"],["BR","Broadridge Financial"],["SS","Soundhound (廃止)"],
  ["VRSK","Verisk Analytics"],["TRI","Thomson Reuters ADR"],
  ["DNB","Dun & Bradstreet"],["CLGX","CoreLogic (廃止→非公開)"],
  ["FAF","First American Financial"],["FNF","Fidelity National Financial"],
  ["SFM","Sprouts Farmers Market"],

  // ── 消費財・小売 Consumer ──────────────────────────────────────────
  ["AMZN","Amazon"],["WMT","Walmart"],["COST","Costco Wholesale"],
  ["TGT","Target"],["HD","Home Depot"],["LOW","Lowe's Companies"],
  ["DG","Dollar General"],["DLTR","Dollar Tree"],["BJ","BJ's Wholesale Club"],
  ["KR","Kroger"],["SFM","Sprouts Farmers Market"],["CASY","Casey's General Stores"],
  ["FIVE","Five Below"],["OLLI","Ollie's Bargain Outlet"],
  ["TUES","Tuesday Morning (廃止)"],["BGFV","Big 5 Sporting Goods"],
  ["DKFS","廃止"],["HIBB","Hibbett Sports (廃止→非公開)"],
  ["TSCO","Tractor Supply"],["BOOT","Boot Barn Holdings"],["WSM","Williams-Sonoma"],
  ["RH","RH (Restoration Hardware)"],["PRTY","Party City (廃止)"],
  ["SIG","Signet Jewelers ADR"],["TIF","Tiffany (廃止→LVMH)"],
  ["MANU","Manchester United ADR"],
  ["MCD","McDonald's"],["SBUX","Starbucks"],["CMG","Chipotle Mexican Grill"],
  ["YUM","Yum! Brands"],["QSR","Restaurant Brands International ADR"],
  ["WEN","Wendy's"],["JACK","Jack in the Box"],["SHAK","Shake Shack"],
  ["DNUT","Krispy Kreme"],["BLMN","Bloomin' Brands"],["DENN","Denny's"],
  ["FAT","FAT Brands"],["FRSH","Fresh Del Monte (廃止)"],
  ["EL","Estée Lauder"],["COTY","Coty"],["REV","Revlon (廃止)"],
  ["KO","Coca-Cola"],["PEP","PepsiCo"],["MNST","Monster Beverage"],
  ["STZ","Constellation Brands"],["TAP","Molson Coors Beverage"],["SAM","Boston Beer"],
  ["BUD","Anheuser-Busch InBev ADR"],["FIZZ","National Beverage"],
  ["PM","Philip Morris International"],["MO","Altria Group"],["BTI","BAT ADR"],
  ["VGR","Vector Group"],["TPB","Turning Point Brands"],
  ["GIS","General Mills"],["K","Kellanova (旧Kellogg)"],["CPB","Campbell Soup"],
  ["HRL","Hormel Foods"],["CAG","Conagra Brands"],["SJM","J.M. Smucker"],
  ["MKC","McCormick"],["CLX","Clorox"],["CHD","Church & Dwight"],
  ["PG","Procter & Gamble"],["CL","Colgate-Palmolive"],["KMB","Kimberly-Clark"],
  ["ENR","Energizer Holdings"],["SPB","Spectrum Brands"],["EDGEWELL","廃止"],
  ["WHR","Whirlpool"],["SEB","Seaboard"],["LW","Lamb Weston Holdings"],
  ["INGR","Ingredion"],["ADM","Archer-Daniels-Midland"],["BG","Bunge Global ADR"],
  ["CTVA","Corteva"],["FMC","FMC Corporation"],["CF","CF Industries"],
  ["NTR","Nutrien ADR"],["MOS","Mosaic"],

  // ── 工業・防衛 Industrials / Defense ──────────────────────────────
  ["BA","Boeing"],["LMT","Lockheed Martin"],["RTX","RTX Corporation"],
  ["NOC","Northrop Grumman"],["GD","General Dynamics"],["LHX","L3Harris Technologies"],
  ["HII","Huntington Ingalls Industries"],["TDG","TransDigm Group"],
  ["HEICO","HEICO"],["CW","Curtiss-Wright"],["AIR","AAR Corp"],
  ["DRS","Leonardo DRS"],["KTOS","Kratos Defense"],["MRCY","Mercury Systems"],
  ["BWXT","BWX Technologies"],["CACI","CACI International"],["LDOS","Leidos"],
  ["BAH","Booz Allen Hamilton"],["SAIC","Science Applications International"],
  ["L3","L3 Technologies (廃止→LHX)"],
  ["GE","GE Aerospace"],["HON","Honeywell International"],["MMM","3M Company"],
  ["EMR","Emerson Electric"],["ROK","Rockwell Automation"],["ITW","Illinois Tool Works"],
  ["PH","Parker Hannifin"],["ETN","Eaton Corporation"],["AME","AMETEK"],
  ["XYL","Xylem"],["GNRC","Generac Holdings"],["ROP","Roper Technologies"],
  ["TT","Trane Technologies"],["JCI","Johnson Controls International"],
  ["CARR","Carrier Global"],["OTIS","Otis Worldwide"],["HVAC","廃止"],
  ["DOV","Dover Corporation"],["FAST","Fastenal"],["GWW","W.W. Grainger"],
  ["MSC","MSC Industrial Direct"],["SITE","SiteOne Landscape Supply"],
  ["MAS","Masco"],["BECN","Beacon Roofing Supply"],["TREX","Trex Company"],
  ["DOOR","Masonite International ADR"],["AWI","Armstrong World Industries"],
  ["LPX","Louisiana-Pacific"],["BLDR","Builders FirstSource"],
  ["SUM","Summit Materials"],["MLM","Martin Marietta Materials"],
  ["VMC","Vulcan Materials"],["EXP","Eagle Materials"],["USG","USG (廃止→KNAUF)"],
  ["FBIN","Fortune Brands Innovations"],
  ["UPS","United Parcel Service"],["FDX","FedEx"],["XPO","XPO"],
  ["ODFL","Old Dominion Freight Line"],["SAIA","Saia"],["JBHT","J.B. Hunt Transport"],
  ["CHRW","C.H. Robinson"],["EXPD","Expeditors International"],
  ["GXO","GXO Logistics"],["RXO","RXO"],["ECHO","Echo Global Logistics"],
  ["FWRD","Forward Air"],["ARCB","ArcBest"],["WERN","Werner Enterprises"],
  ["KNX","Knight-Swift Transportation"],["HTZ","Hertz Global Holdings"],
  ["CAR","Avis Budget Group"],["REVG","REV Group"],["PCAR","PACCAR"],
  ["CMI","Cummins"],["ALSN","Allison Transmission"],
  ["AGCO","AGCO Corporation"],["DE","Deere & Company"],["CNH","CNH Industrial ADR"],

  // ── エネルギー Energy ─────────────────────────────────────────────
  ["XOM","ExxonMobil"],["CVX","Chevron"],["COP","ConocoPhillips"],
  ["EOG","EOG Resources"],["PXD","Pioneer Natural Resources (廃止→XOM)"],
  ["DVN","Devon Energy"],["FANG","Diamondback Energy"],["MPC","Marathon Petroleum"],
  ["PSX","Phillips 66"],["VLO","Valero Energy"],
  ["SLB","SLB (Schlumberger)"],["HAL","Halliburton"],["BKR","Baker Hughes"],
  ["CIVI","Civitas Resources"],["SM","SM Energy"],["MTDR","Matador Resources"],
  ["PR","Permian Resources"],["CTRA","Coterra Energy"],["OXY","Occidental Petroleum"],
  ["MRO","Marathon Oil"],["HES","Hess Corporation (廃止→CVX)"],
  ["APA","APA Corporation"],["KMI","Kinder Morgan"],["WMB","Williams Companies"],
  ["OKE","ONEOK"],["TRP","TC Energy ADR"],["ET","Energy Transfer"],
  ["MPLX","MPLX"],["PAA","Plains All American Pipeline"],["TRGP","Targa Resources"],
  ["AM","Antero Midstream"],["DT","Dynatrace"],
  ["FTI","TechnipFMC ADR"],["NOV","NOV"],["MHO","M/I Homes"],
  ["NEE","NextEra Energy"],["SO","Southern Company"],["DUK","Duke Energy"],
  ["AEP","American Electric Power"],["D","Dominion Energy"],["PCG","PG&E"],
  ["EXC","Exelon"],["XEL","Xcel Energy"],["WEC","WEC Energy Group"],
  ["ES","Eversource Energy"],["AEE","Ameren"],["CNP","CenterPoint Energy"],
  ["NI","NiSource"],["LNT","Alliant Energy"],["ETRN","Equitrans Midstream (廃止→MWE)"],
  ["AWK","American Water Works"],["WTR","Aqua America (廃止→WTRG)"],
  ["WTRG","Essential Utilities"],["SJW","SJW Group"],

  // ── 素材・化学 Materials ──────────────────────────────────────────
  ["LIN","Linde ADR"],["APD","Air Products & Chemicals"],["SHWI","廃止"],
  ["SHW","Sherwin-Williams"],["PPG","PPG Industries"],["EMN","Eastman Chemical"],
  ["DD","DuPont de Nemours"],["DOW","Dow"],["LYB","LyondellBasell ADR"],
  ["BASFY","BASF ADR"],["ALB","Albemarle"],["LAC","Lithium Americas ADR"],
  ["LTHM","Livent (廃止→ALTM)"],["ALTM","Arcadium Lithium ADR (廃止→RIO)"],
  ["NEM","Newmont"],["GOLD","Barrick Gold ADR"],["AEM","Agnico Eagle Mines ADR"],
  ["WPM","Wheaton Precious Metals ADR"],["FNV","Franco-Nevada ADR"],
  ["RGLD","Royal Gold"],["KGC","Kinross Gold ADR"],["AGI","Alamos Gold ADR"],
  ["PAAS","Pan American Silver ADR"],["EQX","Equinox Gold ADR"],
  ["PKG","Packaging Corporation of America"],["SW","Smurfit WestRock"],
  ["IP","International Paper"],["CF","CF Industries"],["NUE","Nucor"],
  ["STLD","Steel Dynamics"],["RS","Reliance Steel & Aluminum"],
  ["X","United States Steel"],["CLF","Cleveland-Cliffs"],["MT","ArcelorMittal ADR"],
  ["RIO","Rio Tinto ADR"],["BHP","BHP Group ADR"],["VALE","Vale ADR"],
  ["FCX","Freeport-McMoRan"],["SCCO","Southern Copper ADR"],
  ["AA","Alcoa"],["CENX","Century Aluminum"],
  ["MERC","Mercer International ADR"],["GEF","Greif"],

  // ── 不動産 Real Estate ────────────────────────────────────────────
  ["AMT","American Tower"],["CCI","Crown Castle"],["SBAC","SBA Communications"],
  ["PLD","Prologis"],["EQR","Equity Residential"],["AVB","AvalonBay Communities"],
  ["ESS","Essex Property Trust"],["MAA","Mid-America Apartment"],["CPT","Camden Property Trust"],
  ["UDR","UDR"],["NNN","NNN REIT"],["O","Realty Income"],["STOR","STORE Capital (廃止)"],
  ["EPRT","Essential Properties Realty Trust"],["ADC","Agree Realty"],
  ["STAG","STAG Industrial"],["WPC","W. P. Carey"],["CUBE","CubeSmart"],
  ["PSA","Public Storage"],["EXR","Extra Space Storage"],["LSI","Life Storage (廃止→EXR)"],
  ["NSA","National Storage Affiliates"],["REXR","Rexford Industrial Realty"],
  ["EGP","EastGroup Properties"],["FR","First Industrial Realty Trust"],
  ["LTC","LTC Properties"],["HR","Healthcare Realty"],
  ["VICI","VICI Properties"],["GLPI","Gaming and Leisure Properties"],
  ["MPW","Medical Properties Trust"],["CHCT","Community Healthcare Trust"],
  ["SPG","Simon Property Group"],["MAC","Macerich"],["CBL","CBL & Associates (廃止)"],
  ["PEI","PREIT (廃止)"],["KIM","Kimco Realty"],["BRX","Brixmor Property Group"],
  ["RPT","RPT Realty (廃止→KIM)"],["WRI","Weingarten Realty (廃止→KIM)"],
  ["SLG","SL Green Realty"],["VNO","Vornado Realty Trust"],["BXP","BXP"],
  ["HIW","Highwoods Properties"],["DEI","Douglas Emmett"],["CUZ","Cousins Properties"],
  ["OFC","Corporate Office Properties Trust"],["PDM","Piedmont Office Realty"],
  ["EQC","Equity Commonwealth"],["CLI","Mack-Cali (廃止→Veris Residential)"],
  ["VRE","Veris Residential"],
  ["IRM","Iron Mountain"],["TRNO","Terreno Realty"],["CTRE","CareTrust REIT"],
  ["IIPR","Innovative Industrial Properties"],["COLD","Americold Realty Trust"],
  ["UNIT","Uniti Group"],["CSAL","廃止"],
  ["EQIX","Equinix"],["DLR","Digital Realty Trust"],["QTS","QTS Realty (廃止→非公開)"],

  // ── 通信サービス Communication Services ──────────────────────────
  ["GOOGL","Alphabet C"],["GOOG","Alphabet A"],["META","Meta Platforms"],
  ["NFLX","Netflix"],["DIS","Walt Disney"],["CMCSA","Comcast"],
  ["WBD","Warner Bros. Discovery"],["PARA","Paramount Global"],
  ["CHTR","Charter Communications"],["TMUS","T-Mobile US"],
  ["SNAP","Snap"],["PINS","Pinterest"],["SPOT","Spotify ADR"],
  ["RDDT","Reddit"],["MTCH","Match Group"],["BMBL","Bumble"],
  ["SIRI","Sirius XM Holdings"],["LSXMK","Liberty SiriusXM"],
  ["NYT","New York Times"],["IPG","Interpublic Group"],["OMC","Omnicom Group"],

  // ── AI・成長株 AI / Growth ────────────────────────────────────────
  ["NVDA","NVIDIA"],["TSM","Taiwan Semiconductor ADR"],
  ["PLTR","Palantir Technologies"],["AI","C3.ai"],["BBAI","BigBear.ai"],
  ["SOUN","SoundHound AI"],["AIXI","Xponential Fitness (廃止)"],
  ["PATH","UiPath"],["PEGA","Pegasystems"],["APPN","Appian"],
  ["AMSWA","American Software"],
  ["KVYO","Klaviyo"],["GTM","廃止"],["INTA","Intapp"],
  ["WEAVE","Weave Communications"],["TASK","TaskUs"],["EXL","EXL Service Holdings"],
  ["EPAM","EPAM Systems"],["GLOB","Globant ADR"],["GFI","Gold Fields ADR"],
  ["ARQQ","Arqit Quantum ADR"],["IONQ","IonQ"],["RGTI","Rigetti Computing"],
  ["QUBT","Quantum Computing"],["QMCO","廃止"],
  ["OPEN","Opendoor (廃止)"],["LMND","Lemonade"],["ROOT","Root Insurance"],
  ["HIG","Hartford Financial"],
  ["DBRG","DigitalBridge Group"],["FTIV","廃止"],
  ["DJT","Trump Media & Technology Group"],
  ["RKLB","Rocket Lab USA"],["ASTS","AST SpaceMobile"],
  ["LUNR","Intuitive Machines"],["RDW","Redwire"],["MNTS","Momentus (廃止)"],
  ["LPA","廃止"],["KPLT","Katapult Holdings (廃止)"],
  ["JOBY","Joby Aviation"],["ACHR","Archer Aviation"],["EVTOL","廃止"],
  ["BLDE","Blade Air Mobility"],["LILM","Lilium (廃止)"],["WISK","廃止"],

  // ── 中国ADR China ADR ─────────────────────────────────────────────
  ["BABA","Alibaba Group ADR"],["TCEHY","Tencent ADR"],["BIDU","Baidu ADR"],
  ["JD","JD.com ADR"],["PDD","PDD Holdings ADR"],["NTES","NetEase ADR"],
  ["BILI","Bilibili ADR"],["TME","Tencent Music ADR"],["LI","Li Auto ADR"],
  ["NIO","NIO ADR"],["XPEV","XPeng ADR"],["ZEEKR","ZEEKR ADR"],
  ["RLX","RLX Technology ADR"],["DIDIY","DiDi Global ADR"],
  ["VNET","VNET Group ADR"],["GDS","GDS Holdings ADR"],["CAN","Canaan ADR"],
  ["BTCM","BIT Mining ADR"],["CIFS","China Industrial Securities (廃止)"],
  ["IQ","iQIYI ADR"],["HUYA","Huya ADR"],["YY","JOYY ADR"],
  ["BEKE","KE Holdings ADR"],["RERE","ATRenew ADR"],["TIGR","UP Fintech ADR"],
  ["FUTU","Futu Holdings ADR"],["LKCO","Lushan Holdings ADR"],
  ["ZH","Zhihu ADR"],["EDTK","Skillful Craftsman (廃止)"],
  ["LAIX","廃止"],["GSX","Gaotu Techedu ADR"],["TAL","TAL Education ADR"],
  ["EDU","New Oriental Education ADR"],["WB","Weibo ADR"],
  ["MNSO","MINISO Group ADR"],["BEST","BEST ADR"],["ZTO","ZTO Express ADR"],
  ["YMM","Full Truck Alliance ADR"],["LX","LexinFintech ADR"],
  ["FINV","FinVolution ADR"],["QFIN","360 DigiTech ADR"],
  ["NOAH","Noah Holdings ADR"],["JFIN","Jiayin Group ADR"],
  ["XD","XINGDONG ADR (廃止)"],["RENN","Renren ADR (廃止)"],
  ["SFUN","SouFun Holdings ADR (廃止)"],

  // ── 韓国・インド・その他 Asia ADR ─────────────────────────────────
  ["KB","KB Financial Group ADR"],["SHG","Shinhan Financial ADR"],
  ["WF","Woori Financial ADR"],["HDB","HDFC Bank ADR"],
  ["IBN","ICICI Bank ADR"],["INFY","Infosys ADR"],["WIT","Wipro ADR"],
  ["HDB","HDFC Bank ADR"],["AXISBANK","廃止"],
  ["LTI","廃止"],["TECHM","Tech Mahindra (廃止OTC)"],
  ["MFG","Mizuho Financial ADR"],["MTU","Mitsubishi UFJ ADR"],
  ["SMFG","Sumitomo Mitsui Financial ADR"],["NTDOY","Nintendo ADR"],
  ["SONY","Sony Group ADR"],["TM","Toyota Motor ADR"],["HMC","Honda Motor ADR"],
  ["CCOEY","Capcom ADR"],["BNTNY","Bandai Namco ADR"],

  // ── ヨーロッパADR European ADR ────────────────────────────────────
  ["SAP","SAP ADR"],["ASML","ASML Holding ADR"],["SHEL","Shell ADR"],
  ["BP","BP ADR"],["TTE","TotalEnergies ADR"],["ENB","Enbridge ADR"],
  ["TRP","TC Energy ADR"],["CNQ","Canadian Natural Resources ADR"],
  ["NVO","Novo Nordisk ADR"],["AZN","AstraZeneca ADR"],
  ["RHHBY","Roche ADR"],["NVS","Novartis ADR"],["SNY","Sanofi ADR"],
  ["GSK","GSK ADR"],["BAYRY","Bayer ADR"],["ALIZY","Allianz ADR"],
  ["UBS","UBS Group ADR"],["DB","Deutsche Bank ADR"],
  ["ING","ING Groep ADR"],["BCS","Barclays ADR"],["HSBC","HSBC ADR"],
  ["LYG","Lloyds Banking ADR"],["NWG","NatWest Group ADR"],
  ["LRLCY","L'Oréal ADR"],["LVMUY","LVMH ADR"],["CFR","Richemont ADR"],
  ["EL","Estée Lauder"],["KER","Kering ADR"],
  ["SIEGY","Siemens ADR"],["ABBN","ABB ADR"],["PHIA","Philips ADR"],
  ["IDEXY","Industria de Diseño Textil (Inditex) ADR"],
  ["ESLOY","Essilorluxottica ADR"],["ADESY","Adidas ADR"],["PUMA","Puma ADR"],
  ["AMGN","Amgen"],["FERG","Ferguson Enterprises ADR"],
  ["FLNC","Fluence Energy"],["ORSTED","廃止"],
  ["EQNR","Equinor ADR"],["E","Eni ADR"],["REP","Repsol ADR"],
  ["AKZA","AkzoNobel ADR"],["SNN","Smith & Nephew ADR"],["SHL","Siemens Healthineers ADR"],
  ["STRAUMANN","廃止"],["GAPFF","廃止"],["RYCEY","Rolls-Royce ADR"],
  ["RR","廃止"],["BDEV","廃止"],["VOLVF","Volvo ADR"],
  ["VLVLY","Volvo Group ADR"],["SAND","Sandvik ADR"],["ATCOY","Atlas Copco ADR"],
  ["EPKKF","Epiroc ADR"],["ALFA","廃止"],["NZYMB","Novozymes ADR"],

  // ── ブロックチェーン・暗号資産関連 Crypto ──────────────────────────
  ["COIN","Coinbase Global"],["MSTR","MicroStrategy"],["MARA","Marathon Digital Holdings"],
  ["RIOT","Riot Platforms"],["BTBT","Bit Digital ADR"],
  ["HUT","Hut 8 Corp ADR"],["BITF","Bitfarms ADR"],
  ["CLSK","CleanSpark"],["CIFR","Cipher Mining"],["IREN","Iris Energy ADR"],
  ["CORZ","Core Scientific"],["WULF","TeraWulf"],["BTDR","Bitdeer Technologies ADR"],
  ["HOOD","Robinhood Markets"],["SMLR","Semler Scientific"],["HIMS","Hims & Hers Health"],
  ["GBTC","Grayscale Bitcoin Trust (廃止→ETF)"],
  ["BITO","ProShares Bitcoin ETF"],["BTCO","Invesco Galaxy Bitcoin ETF"],
  ["IBIT","iShares Bitcoin Trust ETF"],["FBTC","Fidelity Wise Origin Bitcoin Fund"],
  ["EZBC","Franklin Bitcoin ETF"],["HODL","VanEck Bitcoin ETF"],
  ["ETHA","iShares Ethereum Trust ETF"],["ETHX","廃止"],
  ["GETH","Grayscale Ethereum Mini Trust ETF"],

  // ── EV・クリーンテック EV / Cleantech ─────────────────────────────
  ["TSLA","Tesla"],["RIVN","Rivian Automotive"],["LCID","Lucid Group"],
  ["F","Ford Motor"],["GM","General Motors"],["STLA","Stellantis ADR"],
  ["MBGAF","Mercedes-Benz ADR"],["BAMXF","BMW ADR"],["VWAGY","Volkswagen ADR"],
  ["TM","Toyota Motor ADR"],["HMC","Honda Motor ADR"],
  ["BLNK","Blink Charging"],["EVGO","EVgo"],["CHPT","ChargePoint Holdings"],
  ["VLTA","Volta Charging (廃止)"],["NXPI","NXP Semiconductors"],
  ["ON","ON Semiconductor"],["MPWR","Monolithic Power Systems"],
  ["ENPH","Enphase Energy"],["SEDG","SolarEdge Technologies ADR"],
  ["RUN","Sunrun"],["NOVA","Sunnova Energy International"],
  ["SPWR","SunPower (廃止)"],["MAXN","Maxeon Solar"],["ARRY","Array Technologies"],
  ["FSLR","First Solar"],["CSIQ","Canadian Solar ADR"],["JKS","JinkoSolar ADR"],
  ["DQ","Daqo New Energy ADR"],["GCL","廃止"],["SOL","廃止"],
  ["VFS","VinFast Auto ADR"],["FSR","Fisker (廃止)"],["MULN","Mullen Automotive"],
  ["AYRO","AYRO"],["MVST","Microvast Holdings ADR"],
  ["FREYR","FREYR Battery ADR (廃止→TPVG)"],["LFG","廃止"],
  ["AMRC","Ameresco"],["BE","Bloom Energy"],["PLUG","Plug Power"],
  ["FCEL","FuelCell Energy"],["CWEN","Clearway Energy"],
  ["AZRE","Azure Power Global ADR (廃止)"],["SPWR","SunPower (廃止)"],
];
