/**
 * Sector data for US supplement stocks not in the curated STOCKS_CATALOG.
 * Maps symbol → GicsSectorId for use in sector ranking and sector pages.
 * 廃止・ETF は除外済み。
 */
import type { GicsSectorId } from "./gics";

export const US_SECTOR_MAP: Record<string, GicsSectorId> = {
  // ─── Information Technology ────────────────────────────────────────
  CSCO:"information-technology", IBM:"information-technology",
  TXN:"information-technology", QCOM:"information-technology",
  AMAT:"information-technology", MU:"information-technology",
  KLAC:"information-technology", LRCX:"information-technology",
  SNPS:"information-technology", CDNS:"information-technology",
  FTNT:"information-technology", PANW:"information-technology",
  ZS:"information-technology", CRWD:"information-technology",
  DDOG:"information-technology", NET:"information-technology",
  TEAM:"information-technology", MRVL:"information-technology",
  FICO:"information-technology", TEL:"information-technology",
  TER:"information-technology", GLW:"information-technology",
  SWKS:"information-technology", KEYS:"information-technology",
  WDC:"information-technology", STX:"information-technology",
  NTAP:"information-technology", PSTG:"information-technology",
  JNPR:"information-technology", AKAM:"information-technology",
  CDW:"information-technology", GDDY:"information-technology",
  EPAM:"information-technology", CTSH:"information-technology",
  WIT:"information-technology", INFY:"information-technology",
  SHOP:"information-technology", SQ:"information-technology",
  PYPL:"information-technology", NXPI:"information-technology",
  ON:"information-technology", MPWR:"information-technology",
  MCHP:"information-technology", SLAB:"information-technology",
  QRVO:"information-technology", IPGP:"information-technology",
  COHR:"information-technology", WOLF:"information-technology",
  // Software / Cloud
  OKTA:"information-technology", MDB:"information-technology",
  ESTC:"information-technology", RBLX:"information-technology",
  U:"information-technology", AI:"information-technology",
  SOUN:"information-technology", BBAI:"information-technology",
  WDAY:"information-technology", PLTR:"information-technology",
  SMCI:"information-technology", SNOW:"information-technology",
  DELL:"information-technology", HPQ:"information-technology",
  HPE:"information-technology", VRNS:"information-technology", MNDT:"information-technology",
  SAIL:"information-technology", CYBR:"information-technology",
  S:"information-technology", TENB:"information-technology",
  RPD:"information-technology", QLYS:"information-technology",
  CHKP:"information-technology", FFIV:"information-technology",
  VNET:"information-technology", CSGP:"information-technology",
  ZI:"information-technology", PCTY:"information-technology",
  PAYC:"information-technology", SMAR:"information-technology",
  HUBS:"information-technology", LPSN:"information-technology",
  DOCU:"information-technology", DOCN:"information-technology",
  MNDY:"information-technology", FROG:"information-technology",
  GTLB:"information-technology", PD:"information-technology",
  APPN:"information-technology", AZPN:"information-technology",
  ANSS:"information-technology", PTC:"information-technology",
  CDNA:"information-technology", VRT:"information-technology",
  AEHR:"information-technology", ENPH:"information-technology",
  ARM:"information-technology", TSM:"information-technology",
  ASML:"information-technology", SAP:"information-technology",
  // ADR tech
  NTDOY:"information-technology",

  // ─── Communication Services ────────────────────────────────────────
  GOOGL:"communication-services", GOOG:"communication-services",
  META:"communication-services", NFLX:"communication-services",
  DIS:"communication-services", CMCSA:"communication-services",
  T:"communication-services", VZ:"communication-services",
  TTWO:"communication-services", EA:"communication-services",
  WBD:"communication-services", PARA:"communication-services",
  CHTR:"communication-services", TMUS:"communication-services",
  SNAP:"communication-services", PINS:"communication-services",
  SPOT:"communication-services", ROKU:"communication-services",
  TKO:"communication-services", IAC:"communication-services",
  MTCH:"communication-services", BMBL:"communication-services",
  RDDT:"communication-services", NYT:"communication-services",
  GCI:"communication-services", IPG:"communication-services",
  OMC:"communication-services", NWSA:"communication-services",
  NWS:"communication-services", FWONA:"communication-services",
  FWONK:"communication-services", SIRI:"communication-services",
  LSXMK:"communication-services", LBRDK:"communication-services",
  RCI:"communication-services", BCE:"communication-services",
  AMX:"communication-services", SATS:"communication-services",
  VSAT:"communication-services", GSAT:"communication-services",
  // ADR communication
  BIDU:"communication-services", NTES:"communication-services",
  BILI:"communication-services", TME:"communication-services",
  HUYA:"communication-services", IQ:"communication-services",
  GRAB:"communication-services", SEA:"communication-services",
  TCEHY:"communication-services", JD:"communication-services",
  PDD:"communication-services", BABA:"communication-services",

  // ─── Consumer Discretionary ────────────────────────────────────────
  AMZN:"consumer-discretionary", TSLA:"consumer-discretionary",
  HD:"consumer-discretionary", MCD:"consumer-discretionary",
  NKE:"consumer-discretionary", LOW:"consumer-discretionary",
  SBUX:"consumer-discretionary", TJX:"consumer-discretionary",
  BKNG:"consumer-discretionary", ABNB:"consumer-discretionary",
  ROST:"consumer-discretionary", CMG:"consumer-discretionary",
  YUM:"consumer-discretionary", QSR:"consumer-discretionary",
  DPZ:"consumer-discretionary", SHAK:"consumer-discretionary",
  WING:"consumer-discretionary", TXRH:"consumer-discretionary",
  EAT:"consumer-discretionary", DRI:"consumer-discretionary",
  CAKE:"consumer-discretionary", BJRI:"consumer-discretionary",
  F:"consumer-discretionary", GM:"consumer-discretionary",
  STLA:"consumer-discretionary", LI:"consumer-discretionary",
  NIO:"consumer-discretionary", XPEV:"consumer-discretionary",
  RIVN:"consumer-discretionary", LCID:"consumer-discretionary",
  AZO:"consumer-discretionary", ORLY:"consumer-discretionary",
  KMX:"consumer-discretionary", CVNA:"consumer-discretionary",
  DHI:"consumer-discretionary", LEN:"consumer-discretionary",
  PHM:"consumer-discretionary", NVR:"consumer-discretionary",
  TOL:"consumer-discretionary", TMHC:"consumer-discretionary",
  MHO:"consumer-discretionary", SKY:"consumer-discretionary",
  MAR:"consumer-discretionary", HLT:"consumer-discretionary",
  H:"consumer-discretionary", WH:"consumer-discretionary",
  MGM:"consumer-discretionary", WYNN:"consumer-discretionary",
  LVS:"consumer-discretionary", CZR:"consumer-discretionary",
  PENN:"consumer-discretionary", BYD:"consumer-discretionary",
  RCL:"consumer-discretionary", CCL:"consumer-discretionary",
  NCLH:"consumer-discretionary", LUV:"consumer-discretionary",
  DAL:"consumer-discretionary", UAL:"consumer-discretionary",
  AAL:"consumer-discretionary", ALK:"consumer-discretionary",
  JBLU:"consumer-discretionary", ULTA:"consumer-discretionary",
  ETSY:"consumer-discretionary", EBAY:"consumer-discretionary",
  W:"consumer-discretionary", PVH:"consumer-discretionary",
  RL:"consumer-discretionary", TPR:"consumer-discretionary",
  BOOT:"consumer-discretionary", FL:"consumer-discretionary",
  DKS:"consumer-discretionary", ASO:"consumer-discretionary",
  SIG:"consumer-discretionary", OLLI:"consumer-discretionary",
  FIVE:"consumer-discretionary", GME:"consumer-discretionary",
  RH:"consumer-discretionary", WSM:"consumer-discretionary",
  CASY:"consumer-discretionary", PZZA:"consumer-discretionary",
  TM:"consumer-discretionary", HMC:"consumer-discretionary",
  SONY:"consumer-discretionary", AN:"consumer-discretionary",
  PAG:"consumer-discretionary", GPI:"consumer-discretionary",
  SAH:"consumer-discretionary",

  // ─── Consumer Staples ──────────────────────────────────────────────
  WMT:"consumer-staples", PG:"consumer-staples",
  KO:"consumer-staples", PEP:"consumer-staples",
  COST:"consumer-staples", CL:"consumer-staples",
  GIS:"consumer-staples", KHC:"consumer-staples",
  MDLZ:"consumer-staples", PM:"consumer-staples",
  MO:"consumer-staples", HSY:"consumer-staples",
  STZ:"consumer-staples", CHD:"consumer-staples",
  SYY:"consumer-staples", ADM:"consumer-staples",
  KMB:"consumer-staples", MKC:"consumer-staples",
  SJM:"consumer-staples", TGT:"consumer-staples",
  KR:"consumer-staples", ACI:"consumer-staples",
  SFM:"consumer-staples", BURL:"consumer-staples",
  DG:"consumer-staples", DLTR:"consumer-staples",
  DLLR:"consumer-staples", CAG:"consumer-staples",
  CPB:"consumer-staples", HRL:"consumer-staples",
  TSN:"consumer-staples", BG:"consumer-staples",
  INGR:"consumer-staples", FLO:"consumer-staples",
  LANC:"consumer-staples", SENEA:"consumer-staples",
  ABEV:"consumer-staples", BTI:"consumer-staples",

  // ─── Health Care ───────────────────────────────────────────────────
  UNH:"health-care", JNJ:"health-care",
  LLY:"health-care", ABBV:"health-care",
  MRK:"health-care", ABT:"health-care",
  TMO:"health-care", DHR:"health-care",
  AMGN:"health-care", ISRG:"health-care",
  CVS:"health-care", CI:"health-care",
  HUM:"health-care", ELV:"health-care",
  BSX:"health-care", SYK:"health-care",
  VRTX:"health-care", REGN:"health-care",
  BIIB:"health-care", GILD:"health-care",
  ZBH:"health-care", BAX:"health-care",
  RMD:"health-care", A:"health-care",
  IQV:"health-care", DGX:"health-care",
  LH:"health-care", MCK:"health-care",
  CAH:"health-care", ABC:"health-care",
  HOLX:"health-care", MTD:"health-care",
  ALGN:"health-care", DXCM:"health-care",
  PODD:"health-care", TNDM:"health-care",
  ALNY:"health-care", CRSP:"health-care",
  BEAM:"health-care", RXRX:"health-care",
  ILMN:"health-care", EXAS:"health-care",
  GH:"health-care", PTCT:"health-care",
  SRPT:"health-care", BMRN:"health-care",
  RARE:"health-care", ACAD:"health-care",
  LNTH:"health-care", TDOC:"health-care",
  DOCS:"health-care", HIMS:"health-care",
  UHS:"health-care", THC:"health-care",
  HCA:"health-care", ENSG:"health-care",
  MOH:"health-care", CNC:"health-care",
  OSCR:"health-care", MEDP:"health-care",
  ICLR:"health-care", CRL:"health-care",
  HQY:"health-care", PHR:"health-care",
  SDGR:"health-care", WELL:"health-care",
  HR:"health-care", VTR:"health-care",
  OHI:"health-care", SBRA:"health-care",
  NHI:"health-care",
  // ADR pharma
  NVO:"health-care", AZN:"health-care",
  RHHBY:"health-care", NVS:"health-care",
  SNY:"health-care", GSK:"health-care",
  BAYRY:"health-care", BNTX:"health-care",
  VKTX:"health-care",

  // ─── Financials ────────────────────────────────────────────────────
  JPM:"financials", BAC:"financials",
  WFC:"financials", GS:"financials",
  MS:"financials", AXP:"financials",
  BLK:"financials", BX:"financials",
  SCHW:"financials", CME:"financials",
  ICE:"financials", C:"financials",
  USB:"financials", PNC:"financials",
  TFC:"financials", COF:"financials",
  AIG:"financials", ALL:"financials",
  MET:"financials", PRU:"financials",
  AFL:"financials", CINF:"financials",
  PFG:"financials", GL:"financials",
  RE:"financials", RNR:"financials",
  ACGL:"financials", WRB:"financials",
  HIG:"financials", "BRK.A":"financials",
  "BRK.B":"financials", MKL:"financials",
  CB:"financials", PGR:"financials",
  AON:"financials", MMC:"financials",
  WTW:"financials", AJG:"financials",
  BRO:"financials", STT:"financials",
  BK:"financials", NTRS:"financials",
  KEY:"financials", CFG:"financials",
  FITB:"financials", HBAN:"financials",
  RF:"financials", MTB:"financials",
  WAL:"financials", FCNCA:"financials",
  TROW:"financials", FNF:"financials",
  LPLA:"financials", RJF:"financials",
  MORN:"financials", DFS:"financials",
  SYF:"financials", ALLY:"financials",
  SLM:"financials", UPST:"financials",
  AFRM:"financials", SOFI:"financials",
  LC:"financials", COIN:"financials",
  HOOD:"financials", MSTR:"financials",
  NU:"financials", FUTU:"financials",
  TIGR:"financials", ITUB:"financials",
  BBD:"financials", STNE:"financials",
  XP:"financials", PAGS:"financials",
  // ADR banks
  UBS:"financials", DB:"financials",
  ING:"financials", BCS:"financials",
  HSBC:"financials", LYG:"financials",
  SMFG:"financials", MFG:"financials",
  MTU:"financials", MUFG:"financials",
  KB:"financials", SHG:"financials",
  HDB:"financials", IBN:"financials",
  ALIZY:"financials",

  // ─── Energy ────────────────────────────────────────────────────────
  XOM:"energy", CVX:"energy",
  COP:"energy", EOG:"energy",
  SLB:"energy", PSX:"energy",
  VLO:"energy", MPC:"energy",
  HAL:"energy", HES:"energy",
  DVN:"energy", BKR:"energy",
  OXY:"energy", CTRA:"energy",
  APA:"energy", FANG:"energy",
  PR:"energy", MTDR:"energy",
  CPE:"energy", SM:"energy",
  CNX:"energy", AR:"energy",
  EQT:"energy", RRC:"energy",
  SWN:"energy", CHK:"energy",
  KMI:"energy", WMB:"energy",
  OKE:"energy", EPD:"energy",
  ET:"energy", LNG:"energy",
  CQP:"energy", TRGP:"energy",
  MPLX:"energy", PAA:"energy",
  NOV:"energy", FTI:"energy",
  NE:"energy", VAL:"energy",
  DO:"energy", RIG:"energy",
  HP:"energy", NEXT:"energy",
  GLNG:"energy", FLNG:"energy",
  DK:"energy", PBF:"energy",
  FRO:"energy", INSW:"energy",
  STNG:"energy", TNK:"energy",
  AMPY:"energy",
  // ADR energy
  SHEL:"energy", BP:"energy",
  TTE:"energy", ENB:"energy",
  TRP:"energy", CNQ:"energy",
  SU:"energy", CVE:"energy",

  // ─── Materials ─────────────────────────────────────────────────────
  LIN:"materials", APD:"materials",
  ECL:"materials", SHW:"materials",
  FCX:"materials", NEM:"materials",
  ALB:"materials", DD:"materials",
  PPG:"materials", IFF:"materials",
  CF:"materials", MOS:"materials",
  NUE:"materials", MLM:"materials",
  VMC:"materials", RPM:"materials",
  EMN:"materials", CE:"materials",
  FMC:"materials", CTVA:"materials",
  SON:"materials", AVY:"materials",
  PKG:"materials", IP:"materials",
  GPK:"materials", SEE:"materials",
  BALL:"materials", CCK:"materials",
  ATR:"materials", SLGN:"materials",
  AMCR:"materials", BERY:"materials",
  GEF:"materials", MAS:"materials",
  TREX:"materials", CSL:"materials",
  CMC:"materials", KALU:"materials",
  CRS:"materials", ARNC:"materials",
  HWM:"materials", ESAB:"materials",
  AG:"materials", PAAS:"materials",
  AEM:"materials", KGC:"materials",
  RGLD:"materials", WPM:"materials",
  FNV:"materials", TECK:"materials",
  RIO:"materials", BHP:"materials",
  AA:"materials", CENX:"materials",
  SQM:"materials",

  // ─── Industrials ───────────────────────────────────────────────────
  RTX:"industrials", HON:"industrials",
  UPS:"industrials", CAT:"industrials",
  DE:"industrials", LMT:"industrials",
  GE:"industrials", MMM:"industrials",
  EMR:"industrials", ETN:"industrials",
  PH:"industrials", PCAR:"industrials",
  CMI:"industrials", ITW:"industrials",
  NOC:"industrials", GD:"industrials",
  CSX:"industrials", NSC:"industrials",
  UNP:"industrials", FDX:"industrials",
  XYL:"industrials", IR:"industrials",
  TT:"industrials", DOV:"industrials",
  PNR:"industrials", ROK:"industrials",
  AME:"industrials", ROP:"industrials",
  CTAS:"industrials", ADP:"industrials",
  PAYX:"industrials", MAN:"industrials",
  RHI:"industrials", SPXC:"industrials",
  HUBB:"industrials", GNRC:"industrials",
  WSO:"industrials", JCI:"industrials",
  CARR:"industrials", OTIS:"industrials",
  TDG:"industrials", AXON:"industrials",
  SNA:"industrials", CW:"industrials",
  TGI:"industrials", LDOS:"industrials",
  SAIC:"industrials", BAH:"industrials",
  CACI:"industrials", GVA:"industrials",
  STRL:"industrials", DY:"industrials",
  ROAD:"industrials", MYRG:"industrials",
  PWR:"industrials", URI:"industrials",
  AL:"industrials", AER:"industrials",
  ASGN:"industrials", EXPO:"industrials",
  TRN:"industrials", JBHT:"industrials",
  SAIA:"industrials", ODFL:"industrials",
  LSTR:"industrials", WERN:"industrials",
  KNX:"industrials", CHRW:"industrials",
  XPO:"industrials", GXO:"industrials",
  GATX:"industrials", RXO:"industrials",
  HEI:"industrials", BWA:"industrials",
  MHK:"industrials", PRIM:"industrials",
  WSC:"industrials",

  // ─── Real Estate ───────────────────────────────────────────────────
  AMT:"real-estate", PLD:"real-estate",
  CCI:"real-estate", EQIX:"real-estate",
  SPG:"real-estate", DLR:"real-estate",
  O:"real-estate", EQR:"real-estate",
  PSA:"real-estate", ARE:"real-estate",
  EXR:"real-estate", VICI:"real-estate",
  AVB:"real-estate", ESS:"real-estate",
  MAA:"real-estate", CPT:"real-estate",
  UDR:"real-estate", NNN:"real-estate",
  STAG:"real-estate", REXR:"real-estate",
  EGP:"real-estate", FR:"real-estate",
  COLD:"real-estate", IIPR:"real-estate",
  HASI:"real-estate", IRM:"real-estate",
  SBAC:"real-estate", WY:"real-estate",
  PCH:"real-estate", RYN:"real-estate",
  CBRE:"real-estate", JLL:"real-estate",
  Z:"real-estate", ZG:"real-estate",
  WPC:"real-estate", ADC:"real-estate",
  EPRT:"real-estate", FCPT:"real-estate",
  GTY:"real-estate", HIW:"real-estate",
  BXP:"real-estate", SLG:"real-estate",
  VNO:"real-estate", CUZ:"real-estate",
  RVTY:"real-estate", HPP:"real-estate",
  PDM:"real-estate", DEA:"real-estate",
  OFC:"real-estate", CTRE:"real-estate",
  MPW:"real-estate", LTC:"real-estate",
  NTST:"real-estate", RDFN:"real-estate",

  // ─── Utilities ─────────────────────────────────────────────────────
  NEE:"utilities", SO:"utilities",
  D:"utilities", DUK:"utilities",
  SRE:"utilities", AEP:"utilities",
  XEL:"utilities", EXC:"utilities",
  PEG:"utilities", ED:"utilities",
  WEC:"utilities", PCG:"utilities",
  ETR:"utilities", EIX:"utilities",
  ES:"utilities", CNP:"utilities",
  OGE:"utilities", EVRG:"utilities",
  POR:"utilities", AVA:"utilities",
  NI:"utilities", LNT:"utilities",
  AEE:"utilities", CMS:"utilities",
  BKH:"utilities", AWK:"utilities",
  WTRG:"utilities", CWT:"utilities",
  IDACORP:"utilities", IDA:"utilities",
  AWR:"utilities", UTL:"utilities",
  MSEX:"utilities",

  // ─── Information Technology (additional) ──────────────────────────
  ADYEN:"information-technology", MTSI:"information-technology",
  ALGM:"information-technology", SITM:"information-technology",
  FORM:"information-technology", AMBA:"information-technology",
  POWI:"information-technology", DIOD:"information-technology",
  SMTC:"information-technology", VEEV:"information-technology",
  TWLO:"information-technology", APP:"information-technology",
  ALRM:"information-technology", CWAN:"information-technology",
  PCOR:"information-technology", TOST:"information-technology",
  BIGC:"information-technology", WIX:"information-technology",
  BILL:"information-technology", ASAN:"information-technology",
  ZM:"information-technology", RNG:"information-technology",
  FOUR:"information-technology", EVTC:"information-technology",
  SPSC:"information-technology", NTNX:"information-technology",
  PEGA:"information-technology", PRGS:"information-technology",
  TYL:"information-technology", DLB:"information-technology",
  LSPD:"information-technology", DT:"information-technology",
  SPNS:"information-technology", TTEC:"information-technology",
  SPT:"information-technology", PRFT:"information-technology",
  OSPN:"information-technology", BR:"information-technology",
  LITE:"information-technology", VIAV:"information-technology",
  CIEN:"information-technology", CALX:"information-technology",
  INFN:"information-technology", ADTRAN:"information-technology",
  ARLO:"information-technology", LOGI:"information-technology",
  LAZR:"information-technology", KN:"information-technology",
  MAXN:"information-technology",

  // ─── Communication Services (additional) ──────────────────────────
  BAND:"communication-services", EGHT:"communication-services",
  OOMA:"communication-services", ZETA:"communication-services",
  TRIP:"communication-services", AMC:"communication-services",
  AT:"communication-services", CCOEY:"communication-services",
  SQNNY:"communication-services", SGAMY:"communication-services",
  BNTNY:"communication-services", LILA:"communication-services",
  LILAK:"communication-services", CHL:"communication-services",
  CHU:"communication-services", CHA:"communication-services",

  // ─── Consumer Discretionary (additional) ──────────────────────────
  JACK:"consumer-discretionary", BLMN:"consumer-discretionary",
  NSANY:"consumer-discretionary", AAP:"consumer-discretionary",
  GPC:"consumer-discretionary", MNRO:"consumer-discretionary",
  VRM:"consumer-discretionary", MDC:"consumer-discretionary",
  CVCO:"consumer-discretionary", IHG:"consumer-discretionary",
  HBI:"consumer-discretionary", UA:"consumer-discretionary",
  COLM:"consumer-discretionary", SCVL:"consumer-discretionary",
  ANGI:"consumer-discretionary", UAA:"consumer-discretionary",
  SKX:"consumer-discretionary", VFC:"consumer-discretionary",
  GIII:"consumer-discretionary", OXM:"consumer-discretionary",
  CATO:"consumer-discretionary", TLYS:"consumer-discretionary",
  ANF:"consumer-discretionary", AEO:"consumer-discretionary",
  URBN:"consumer-discretionary", GPS:"consumer-discretionary",
  JWN:"consumer-discretionary", M:"consumer-discretionary",
  KSS:"consumer-discretionary", BBWI:"consumer-discretionary",
  GDEN:"consumer-discretionary", HTHT:"consumer-discretionary",
  CUK:"consumer-discretionary", DKNG:"consumer-discretionary",
  RSI:"consumer-discretionary", EVRI:"consumer-discretionary",
  PTON:"consumer-discretionary", EXPE:"consumer-discretionary",
  MELI:"consumer-discretionary", DASH:"consumer-discretionary",
  SCI:"consumer-discretionary", GPRO:"consumer-discretionary",
  HRB:"consumer-discretionary", NKLA:"consumer-discretionary",
  WKHS:"consumer-discretionary",

  // ─── Consumer Staples (additional) ────────────────────────────────
  K:"consumer-staples", LW:"consumer-staples",
  JJSF:"consumer-staples", COTY:"consumer-staples",
  SPB:"consumer-staples", ENR:"consumer-staples",
  CLX:"consumer-staples", UN:"consumer-staples",
  UL:"consumer-staples", DEO:"consumer-staples",
  SAM:"consumer-staples", TAP:"consumer-staples",
  BUD:"consumer-staples", TWNK:"consumer-staples",
  SMPL:"consumer-staples", HAIN:"consumer-staples",
  BYND:"consumer-staples", VITL:"consumer-staples",
  NTR:"consumer-staples",

  // ─── Health Care (additional) ─────────────────────────────────────
  COO:"health-care", HSIC:"health-care",
  WAT:"health-care", TFX:"health-care",
  ARWR:"health-care", BLUE:"health-care",
  FATE:"health-care", EDIT:"health-care",
  NTLA:"health-care", VERV:"health-care",
  SEER:"health-care", PACB:"health-care",
  PTGX:"health-care", LGND:"health-care",
  CORT:"health-care", HRMY:"health-care",
  ITCI:"health-care", SAVA:"health-care",
  ANIP:"health-care", HRTX:"health-care",
  PRAX:"health-care", DAWN:"health-care",
  RCUS:"health-care", AGIO:"health-care",
  HCAT:"health-care", ACCD:"health-care",
  AMWL:"health-care", CYH:"health-care",
  AMED:"health-care", EHAB:"health-care",
  BKD:"health-care", CLOV:"health-care",
  MNKD:"health-care", PRTA:"health-care",
  INVA:"health-care", KNTK:"health-care",

  // ─── Financials (additional) ───────────────────────────────────────
  MSCI:"financials", MCO:"financials",
  SPGI:"financials", FDS:"financials",
  LNC:"financials", THG:"financials",
  ERIE:"financials", KMPR:"financials",
  JRVR:"financials", FHN:"financials",
  WBS:"financials", BOKF:"financials",
  CBSH:"financials", WSFS:"financials",
  FFIN:"financials", FAF:"financials",
  STC:"financials", PIPR:"financials",
  VRTS:"financials", AMK:"financials",
  NAVI:"financials", OMF:"financials",
  TREE:"financials", OPFI:"financials",
  PRAA:"financials", WRLD:"financials",
  ENVA:"financials", CACC:"financials",
  ITIC:"financials", ARCC:"financials",
  FSK:"financials", PSEC:"financials",
  MAIN:"financials", HTGC:"financials",
  GBDC:"financials", TPVG:"financials",
  LU:"financials", NOAH:"financials",
  CANG:"financials", WF:"financials",
  NWG:"financials",

  // ─── Energy (additional) ───────────────────────────────────────────
  VTLE:"energy", CHX:"energy",
  CLMT:"energy", PARR:"energy",
  IMPP:"energy", HAFN:"energy",
  DHT:"energy", TRMD:"energy",
  ASC:"energy", WTTR:"energy",
  RES:"energy",

  // ─── Materials (additional) ────────────────────────────────────────
  OI:"materials", AZEK:"materials",
  WOR:"materials", RYI:"materials",
  AU:"materials", NGD:"materials",
  GFI:"materials", SBSW:"materials",
  OR:"materials", VALE:"materials",

  // ─── Industrials (additional) ──────────────────────────────────────
  VRSK:"industrials", IEX:"industrials",
  SPX:"industrials", AOS:"industrials",
  WMS:"industrials", AAON:"industrials",
  TKR:"industrials", NN:"industrials",
  DRS:"industrials", VSE:"industrials",
  AGX:"industrials", ASTE:"industrials",
  MYR:"industrials", HEES:"industrials",
  GBX:"industrials", FTAI:"industrials",
  MRTN:"industrials", HTLD:"industrials",
  ECHO:"industrials", KFRC:"industrials",
  KELYA:"industrials", HCSG:"industrials",
  SSD:"industrials", LYFT:"industrials",
  RDW:"industrials", KTOS:"industrials",
  ESLT:"industrials", AWI:"industrials",
  DOOR:"industrials", "MOG.A":"industrials",

  // ─── Real Estate (additional) ──────────────────────────────────────
  OPAD:"real-estate", HOUS:"real-estate",
  PGRE:"real-estate", GMRE:"real-estate",
  CHCT:"real-estate", BRT:"real-estate",
  KW:"real-estate", BEKE:"real-estate",

  // ─── Utilities (additional) ────────────────────────────────────────
  NWE:"utilities", MGEE:"utilities",
  OTTR:"utilities", ARTNA:"utilities",
  SJW:"utilities", YORW:"utilities",
  ENIA:"utilities", ELP:"utilities",
  OPAL:"utilities",

  // ─── Remaining active stocks ───────────────────────────────────────
  TTGT:"information-technology", VUZI:"information-technology",
  TCS:"information-technology",
  SKYW:"industrials", RAIL:"industrials",
  WLFC:"industrials",
  OMI:"health-care", VCNX:"health-care",
  UCB:"health-care",
  GEL:"energy", CAPL:"energy",
  AIN:"materials",
  PMP:"financials", RNST:"financials",
  PUBGY:"communication-services",
  BOSS:"consumer-discretionary", CHICO:"consumer-discretionary",
  GOEV:"consumer-discretionary",
  HEN3:"consumer-staples",
  PW:"real-estate",
};

/**
 * Returns the GICS sector for a US supplement stock, or null if not known.
 */
export function getSupplementSector(symbol: string): GicsSectorId | null {
  return (US_SECTOR_MAP[symbol] as GicsSectorId) ?? null;
}
